# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T17:01:26"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["test_and_op", "test_or_op", "test_and_expr", "test_or_expr", "test_not_op", "main"]
__private__ = []
__deps__ = []
cpdef int test_and_op():
    if True && False:
        return 1
    return 0
cpdef int test_or_op():
    if True || False:
        return 1
    return 0
cpdef bool test_and_expr():
    return True && False
cpdef bool test_or_expr():
    return True || False
cpdef int test_not_op():
    if !True:
        return 1
    return 0
cpdef int main():
    return 0