# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T16:55:27"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["test", "main"]
__private__ = []
__deps__ = []
cpdef int test():
    cdef float f = 3.14
    cdef int x = int(f)
    return x
cpdef int main():
    return 0