# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T16:55:10"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["test_if_elif", "test_return_unreachable", "test_empty_body", "test_multiline_expr", "test_nested_call", "test_var_in_if", "test_var_in_for", "test_list_literal", "main"]
__private__ = []
__deps__ = []
cpdef int test_if_elif(int x):
    if x > 10:
        return 3
    else:
        if x > 5:
            return 2
        else:
            if x > 0:
                return 1
            else:
                return 0
cpdef int test_return_unreachable():
    return 1
cpdef int test_empty_body():
    return 0
cpdef int test_multiline_expr():
    return 1 + 2 + 3 + 4 + 5
cpdef int test_nested_call():
    return 0
cpdef int test_var_in_if(int x):
    if x > 0:
        cdef int y = 1
        return y
    return 0
cpdef int test_var_in_for():
    cdef int total = 0
    for i in range(3):
        cdef int temp = i * 2
        total = total + temp
    return total
cpdef list[int] test_list_literal():
    return [1, 2, 3]
cpdef int main():
    return 0