# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T21:31:35"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["test_param_type", "test_call_wrong_type", "main"]
__private__ = []
__deps__ = []
cpdef int test_param_type(int a):
    return a
cpdef int test_call_wrong_type():
    return test_param_type('wrong')
cpdef int main():
    return 0