# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T13:31:21"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["Printable", "Point", "add_numbers", "process", "classify_number", "classify_string", "classify_sign", "main"]
__private__ = []
__deps__ = []
""
"Test advanced Cypy features: trait, impl, union types, match/case."
""
class Printable:
    def to_string(self, self) -> str: ...
cdef struct Point:
    float x
    float y
# impl Printable for Point
    cpdef str to_string(self):
        return "Point({self.x}, {self.y})"
cpdef Number add_numbers(Number a, Number b):
    return a + b
cpdef str process(int value):
    return str(value)
cpdef str classify_number(int n):
    return "zero"
    return "one"
    return "two"
    return "three"
    return "four"
    return "five"
cpdef str classify_string(str s):
    return "greeting"
    return "farewell"
    return "test"
cpdef str classify_sign(int n):
    return "small positive"
    return "zero"
    return "negative"
cpdef int main():
    p = Point(x=3.0, y=4.0)
    print("Point to_string: {p.to_string()}")
    a = 10
    b = 5.5
    print("add_numbers(10, 5.5) = {add_numbers(a, b)}")
    v1 = 42
    v2 = "hello"
    print("process(42) = {process(v1)}")
    print("process('hello') = {process(v2)}")
    print("classify_number(0) = {classify_number(0)}")
    print("classify_number(1) = {classify_number(1)}")
    print("classify_number(5) = {classify_number(5)}")
    print("classify_string('hello') = {classify_string('hello')}")
    print("classify_string('bye') = {classify_string('bye')}")
    print("classify_string('foo') = {classify_string('foo')}")
    print("classify_sign(2) = {classify_sign(2)}")
    print("classify_sign(-3) = {classify_sign(-3)}")
    print("classify_sign(0) = {classify_sign(0)}")
    return 0