# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T16:01:50"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["test_fstring"]
__private__ = []
__deps__ = []
cpdef str test_fstring():
    return f'Simple.x = {42}'