# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T17:02:30"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["Status", "Result", "test_enum_match", "test_struct_with_enum", "test_nested_match", "test_match_guard", "test_match_multi_pattern", "main"]
__private__ = []
__deps__ = []
from enum import IntEnum
class Status(IntEnum):
    Ok
    Err
cdef struct Result:
    int status
    int value
cpdef int test_enum_match():
    cdef int s = 0
    match s:
        case 0:
            return 1
        case 1:
            return 0
        case _:
            return -1
cpdef int test_struct_with_enum():
    cdef Result r = Result(status=0, value=42)
    return r.value
cpdef int test_nested_match():
    match 1:
        case 1:
            match 2:
                case 2:
                    return 42
                case _:
                    return 0
        case _:
            return 0
cpdef int test_match_guard():
    match 1:
        case 1:
            return 1
        case _:
            return 0
cpdef int test_match_multi_pattern():
    match 1:
        case 1:
            return 1
        case 2:
            return 2
        case _:
            return 0
cpdef int main():
    return 0