# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T17:02:30"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["test_nested_function", "test_closure", "test_recursive", "test_many_params", "test_default_param", "test_variadic", "test_lambda", "main"]
__private__ = []
__deps__ = []
cpdef int test_nested_function():
    cpdef int inner():
        return 42
    return inner()
cpdef int test_closure():
    cdef int x = 10
    cpdef int inner():
        return x
    return inner()
cpdef int test_recursive():
    if 0:
        return 0
    return 1
cpdef int test_many_params(int a, int b, int c, int d, int e):
    return a + b + c + d + e
cpdef int test_default_param():
    return 0
cpdef int test_variadic():
    return 0
cpdef int test_lambda():
    return 0
cpdef int main():
    return 0