# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T17:14:44"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["test_match_int", "main"]
__private__ = []
__deps__ = []
cpdef int test_match_int():
    match 1:
        case 1:
            return 1
        case _:
            return 0
cpdef int main():
    return 0