# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

str __name__ = "main"
str __file__ = "DEMO/16_testing/test_suite.lz"
str __package__ = "16_testing"
str __path__ = "DEMO/16_testing"
str __doc__ = ""
bint __is_macro__ = False
def test_add():
    assert_eq!(1 + 1, 2)

def test_sub():
    assert_eq!(5 - 3, 2)

def main(): pass
