# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Multiplier", "Adder", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class Multiplier:
    cdef public Py_ssize_t factor
    def __init__(self, Py_ssize_t factor):        self.factor = factor
    cdef Py_ssize_t __call__(self, Py_ssize_t x):    
        self.factor * x

cdef class Adder:
    cdef public Py_ssize_t base
    def __init__(self, Py_ssize_t base):        self.base = base
    cdef Py_ssize_t __call__(self, Py_ssize_t a, Py_ssize_t b):    
        self.base + a + b

cdef void main():
    doubler = Multiplier(_KwArg(name = "factor", value = 2))
    print(doubler.__call__(21))
    add5 = Adder(_KwArg(name = "base", value = 5))
    print(add5.__call__(1, 2))
    f = doubler
    print(f.__call__(10))

str __name__ = "main"
str __file__ = "DEMO/07_data_structures/callable_objects.lz"
str __package__ = "07_data_structures"
str __path__ = "DEMO/07_data_structures"
str __doc__ = ""
bint __is_macro__ = False
