# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Color", "Shape", "Option", "Result", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

class Color:
    pass

class Red(Color):
    pass
Red = Red()

class Green(Color):
    pass
Green = Green()

class Blue(Color):
    pass
Blue = Blue()

class Shape:
    pass

class Circle(Shape):
    def __init__(self, x, y, radius):
        self.x = x
        self.y = y
        self.radius = radius

class Rectangle(Shape):
    def __init__(self, width, height):
        self.width = width
        self.height = height

class Square(Shape):
    def __init__(self, side):
        self.side = side

# generic<T>
class Option:
    pass

class Some(Option):
    def __init__(self, value):
        self.value = value

class None(Option):
    pass
None_ = None()

def is_some(self) -> bint:
    __scrut_0 = self
    if __scrut_0 is not None:
        _ = __scrut_0
        return True
    elif __scrut_0 is None:
        return False
    else:
        pass
def is_none(self) -> bint:
    __scrut_1 = self
    if __scrut_1 is not None:
        _ = __scrut_1
        return False
    elif __scrut_1 is None:
        return True
    else:
        pass
def unwrap_or(self, object default) -> object:
    __scrut_2 = self
    if __scrut_2 is not None:
        v = __scrut_2
        return v
    elif __scrut_2 is None:
        return default
    else:
        pass
def map(self, object f) -> object:
    # generic<R>
    __scrut_3 = self
    if __scrut_3 is not None:
        v = __scrut_3
        return f(v)
    elif __scrut_3 is None:
        return None
    else:
        pass
def and_then(self, object f) -> object:
    # generic<R>
    __scrut_4 = self
    if __scrut_4 is not None:
        v = __scrut_4
        return f(v)
    elif __scrut_4 is None:
        return None
    else:
        pass

# generic<T, E>
class Result:
    pass

class Ok(Result):
    def __init__(self, value):
        self.value = value

class Err(Result):
    def __init__(self, error):
        self.error = error

def is_ok(self) -> bint:
    __scrut_5 = self
    if not isinstance(__scrut_5, BaseException):
        _ = __scrut_5
        return True
    elif isinstance(__scrut_5, BaseException):
        _ = __scrut_5
        return False
    else:
        pass
def is_err(self) -> bint:
    __scrut_6 = self
    if not isinstance(__scrut_6, BaseException):
        _ = __scrut_6
        return False
    elif isinstance(__scrut_6, BaseException):
        _ = __scrut_6
        return True
    else:
        pass
def unwrap(self) -> object:
    __scrut_7 = self
    if not isinstance(__scrut_7, BaseException):
        v = __scrut_7
        return v
    elif isinstance(__scrut_7, BaseException):
        e = __scrut_7
        raise LZError(f"called unwrap on Err: {e}")
    else:
        pass
def unwrap_or(self, object default) -> object:
    __scrut_8 = self
    if not isinstance(__scrut_8, BaseException):
        v = __scrut_8
        return v
    elif isinstance(__scrut_8, BaseException):
        _ = __scrut_8
        return default
    else:
        pass

def main():
    c = Red
    s = Circle(x = 0, y = 0, radius = 10)
    opt = 42
    res = 10
    __scrut_9 = c
    if __scrut_9 is Red:
        "red"
    elif __scrut_9 is Green:
        "green"
    elif __scrut_9 is Blue:
        "blue"
    else:
        pass
    desc = None
    __scrut_10 = s
    if isinstance(__scrut_10, Circle):
        _ = __scrut_10.x
        _ = __scrut_10.y
        r = __scrut_10.radius
        3.14 * r * r
    elif isinstance(__scrut_10, Rectangle):
        w = __scrut_10.width
        h = __scrut_10.height
        (float(w)) * (float(h))
    elif isinstance(__scrut_10, Square):
        s = __scrut_10.side
        (float(s)) * (float(s))
    else:
        pass
    area = None
    __scrut_11 = opt
    if __scrut_11 is not None:
        v = __scrut_11
        f"got {v}"
    elif __scrut_11 is None:
        "empty"
    else:
        pass
    msg = None
    __scrut_12 = res
    if not isinstance(__scrut_12, BaseException):
        v = __scrut_12
        f"success: {v}"
    elif isinstance(__scrut_12, BaseException):
        e = __scrut_12
        f"error: {e}"
    else:
        pass
    result_msg = None
    print(desc)
    print(area)
    print(msg)
    print(result_msg)
    opt2 = 42
    opt3 = None
    print(opt2.is_some())
    print(opt3.is_none())
    print(opt2.unwrap_or(0))
    print(opt3.unwrap_or(0))
    mapped = opt2.map(lambda x: x * 2)
    __scrut_13 = mapped
    if __scrut_13 is not None:
        v = __scrut_13
        f"mapped: {v}"
    elif __scrut_13 is None:
        "empty"
    else:
        pass
    mapped_msg = None
    print(mapped_msg)
    chained = opt2.and_then(lambda x: x + 1)
    __scrut_14 = chained
    if __scrut_14 is not None:
        v = __scrut_14
        f"chained: {v}"
    elif __scrut_14 is None:
        "empty"
    else:
        pass
    chained_msg = None
    print(chained_msg)
    ok_val = 5
    err_val = LZError("bad")
    print(ok_val.is_ok())
    print(err_val.is_err())
    print(ok_val.unwrap())
    nested = 7
    __scrut_15 = nested
    if not isinstance(__scrut_15, BaseException) and __scrut_15 is not None:
        v = __scrut_15
        f"nested value: {v}"
    elif not isinstance(__scrut_15, BaseException) and __scrut_15 is None:
        "nested empty"
    elif isinstance(__scrut_15, BaseException):
        e = __scrut_15
        f"error: {e}"
    else:
        pass
    nested_desc = None
    print(nested_desc)

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\07_data_structures\\enum.lz"  # const: str
__package__ = "07_data_structures"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\07_data_structures"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
