# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Vector", "Point", "MyList", "MyIterator", "Multiplier", "ManagedFile", "Config", "Account", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class Vector:
    cdef public double x
    cdef public double y
    def __init__(self, double x, double y):
        self.x = x
        self.y = y
    def __add__(self, Vector other) -> Vector:    
        return Vector(x = self.x + other.x, y = self.y + other.y)
    def __sub__(self, Vector other) -> Vector:    
        return Vector(x = self.x - other.x, y = self.y - other.y)
    def __mul__(self, double scalar) -> Vector:    
        return Vector(x = self.x * scalar, y = self.y * scalar)
    def __str__(self) -> str:    
        return f"Vector({self.x}, {self.y})"
    def __eq__(self, Vector other) -> bint:    
        return self.x == other.x and self.y == other.y

cdef class Point:
    cdef public Py_ssize_t x
    cdef public Py_ssize_t y
    def __init__(self, Py_ssize_t x, Py_ssize_t y):
        self.x = x
        self.y = y
    def __eq__(self, Point other) -> bint:    
        return self.x == other.x and self.y == other.y
    def __hash__(self) -> Py_ssize_t:    
        return self.x ^ self.y
    def __str__(self) -> str:    
        return f"Point({self.x}, {self.y})"

# generic<T>
cdef class MyList:
    cdef public list items
    def __init__(self, list items):
        self.items = items
    def __getitem__(self, Py_ssize_t index) -> object:    
        return self.items[index]
    def __setitem__(self, Py_ssize_t index, object value):    
        self.items[index] = value
    def __len__(self) -> Py_ssize_t:    
        return self.items.length()
    def __iter__(self) -> MyIterator:    
        return MyIterator(items = self.items, index = 0)

# generic<T>
cdef class MyIterator:
    cdef public list items
    cdef public Py_ssize_t index
    def __init__(self, list items, Py_ssize_t index):
        self.items = items
        self.index = index
    def __next__(self) -> object:    
        if self.index < self.items.length():
            val = self.items[self.index]
            self.index = self.index + 1
            val
            return val
        else:
            return None

cdef class Multiplier:
    cdef public Py_ssize_t factor
    def __init__(self, Py_ssize_t factor):
        self.factor = factor
    def __call__(self, Py_ssize_t x) -> Py_ssize_t:    
        return self.factor * x

cdef class ManagedFile:
    cdef public str name
    def __init__(self, str name):
        self.name = name
    def __enter__(self) -> ManagedFile:    
        print(f"opening {self.name}")
        return self
    def __exit__(self, ManagedFile _guard):    
        print(f"closing {self.name}")

cdef class Config:
    cdef public str host
    cdef public Py_ssize_t port
    cdef public bint debug
    def __init__(self, str host, Py_ssize_t port, bint debug):
        self.host = host
        self.port = port
        self.debug = debug

def Config__new__(str host, Py_ssize_t port):
    Config__new__(host, port, False)

cdef class Account:
    cdef public bint active
    cdef public Py_ssize_t balance
    def __init__(self, bint active, Py_ssize_t balance):
        self.active = active
        self.balance = balance
    def __bool__(self) -> bint:    
        return self.active and self.balance > 0

def main():
    v1 = Vector(x = 1.0, y = 2.0)
    v2 = Vector(x = 3.0, y = 4.0)
    v3 = v1.__add__(v2)
    v4 = v2.__sub__(v1)
    v5 = v1.__mul__(5.0)
    eq = v1.__eq__(v1)
    print(str(v3), str(v4), str(v5), eq)
    p1 = Point(x = 1, y = 2)
    p2 = Point(x = 1, y = 2)
    p3 = Point(x = 3, y = 4)
    print(p1.__eq__(p2))
    print(p1.__eq__(p3))
    print(str(p1))
    ml = MyList(items = [10, 20, 30])  # mut
    print(ml[0], ml[1])
    print(ml.len())
    ml[1] = 25
    print(ml[1])
    doubler = Multiplier(factor = 2)
    print(doubler.__call__(21))
    __with_f = ManagedFile(name = "test.txt")  # mut
    f = __with_f.__enter__()  # mut
    print(f.name)
    f.__exit__(f.clone())
    cfg = Config__new__(host = "localhost", port = 8080)
    print(cfg.host, cfg.port, cfg.debug)
    acc1 = Account(active = True, balance = 100)
    acc2 = Account(active = True, balance = 0)
    (print("acc1 is active") if acc1 else None)
    (print("acc2 is inactive") if not acc2 else None)

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\07_data_structures\\magic_methods.lz"  # const: str
__package__ = "07_data_structures"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\07_data_structures"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
