# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Point", "Rectangle", "Pair", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class Point:
    cdef public double x
    cdef public double y
    def __init__(self, double x, double y):        self.x = x
        self.y = y

cdef class Rectangle:
    cdef public double width
    cdef public double height
    def __init__(self, double width, double height):        self.width = width
        self.height = height
    cdef double area(self):    
        self.width * self.height
    cdef void scale(self, double factor):    
        self.width = self.width * factor
        self.height = self.height * factor

cdef class Pair:
    cdef public object first
    cdef public object second
    def __init__(self, object first, object second):        self.first = first
        self.second = second

cdef void main():
    p = Point(_KwArg(name = "x", value = 3), _KwArg(name = "y", value = 4))
    print(p.x, p.y)
    r = Rectangle(_KwArg(name = "width", value = 10), _KwArg(name = "height", value = 5))
    print(r.area())
    pair = Pair(_KwArg(name = "first", value = 1), _KwArg(name = "second", value = 2))
    print(pair.first)

str __name__ = "main"
str __file__ = "DEMO/07_data_structures/struct.lz"
str __package__ = "07_data_structures"
str __path__ = "DEMO/07_data_structures"
str __doc__ = ""
bint __is_macro__ = False
