# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Counter", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class Counter:
    cdef public Py_ssize_t count
    def __init__(self, Py_ssize_t count):        self.count = count
    cdef Py_ssize_t increment(self):    
        self.count = self.count + 1
        self.count
    cdef Py_ssize_t decrement(self):    
        self.count = self.count - 1
        self.count
    cdef void reset(self):    
        self.count = 0
    cdef Py_ssize_t snapshot(self):    
        self.count

cdef void main():
    c = Counter(_KwArg(name = "count", value = 0))
    print(c.increment())
    print(c.increment())
    print(c.decrement())
    print(c.snapshot())
    c.reset()
    print(c.snapshot())

str __name__ = "main"
str __file__ = "DEMO/07_data_structures/struct_more.lz"
str __package__ = "07_data_structures"
str __path__ = "DEMO/07_data_structures"
str __doc__ = ""
bint __is_macro__ = False
