# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Rectangle", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class Rectangle:
    cdef public double width
    cdef public double height
    def __init__(self, double width, double height):        self.width = width
        self.height = height

class Drawable:
    """Trait: Drawable"""
    def draw(self) -> tuple: ...
    def bounds(self) -> tuple: ...

# impl Drawable for Rectangle
# Drawable.draw → 注入到 Rectangle
# Drawable.bounds → 注入到 Rectangle

cdef void main():
    print("trait/impl demo")

str __name__ = "main"
str __file__ = "DEMO/07_data_structures/trait_impl.lz"
str __package__ = "07_data_structures"
str __path__ = "DEMO/07_data_structures"
str __doc__ = ""
bint __is_macro__ = False
