# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython

class _Moved:
    """Ownership sentinel: access after move raises RuntimeError"""
    def __getattr__(self, name): raise RuntimeError(f"access to moved value: {name}")
    def __setattr__(self, name, v): raise RuntimeError("assign to moved value")
    def __bool__(self): raise RuntimeError("use of moved value")
    def __repr__(self): return "<_Moved>"

_MOVED = _Moved()

def _MovedCheck(v):
   """Check if value has been moved; raise RuntimeError if so."""
   if isinstance(v, _Moved):
       raise RuntimeError("use of moved value")
   return v
__name__ = "basic"
__file__ = "TESTS/04_functions/basic.lz"
__all__ = ["double", "greet", "main"]

cpdef Py_ssize_t double(x: int):
    return x * 2

def greet(name: str) -> str:
    return f"Hello, {name}"

def main():
    print(double(5))
    print(greet("LZ"))
