# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "basic"
__file__ = "TESTS/04_functions/basic.lz"
__all__ = ["double", "greet", "main"]

cpdef double(x: int) -> int:
    x * 2

cpdef greet(name: str) -> str:
    f"Hello, {name}"

def main():
    print(double(5))
    print(greet("LZ"))
