# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T16:58:57"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["test_0", "main"]
__private__ = []
__deps__ = []
cpdef int test_0():
    try:
        while -100 - 0:
            break
    finally:
        cdef int cleanup = 0
cpdef int main():
    return 0