# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T16:58:52"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["Color", "main"]
__private__ = []
__deps__ = []
from enum import IntEnum
class Color(IntEnum):
    Red
    Green
    Blue
cpdef int main():
    return 0