# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython

class _Moved:
    """Ownership sentinel: access after move raises RuntimeError"""
    def __getattr__(self, name): raise RuntimeError(f"access to moved value: {name}")
    def __setattr__(self, name, v): raise RuntimeError("assign to moved value")
    def __bool__(self): raise RuntimeError("use of moved value")
    def __repr__(self): return "<_Moved>"

_MOVED = _Moved()

def _MovedCheck(v):
   """Check if value has been moved; raise RuntimeError if so."""
   if isinstance(v, _Moved):
       raise RuntimeError("use of moved value")
   return v
__name__ = "test_types"
__file__ = "TESTS/99_self_test/test_types.lz"
__all__ = ["main"]

def main():
    assert 42 == 42
    assert 255 == 255
    assert 10 == 10
    assert 63 == 63
    assert 3.14 == 3.14
    assert 10000000000.0 == 10000000000.0
    assert True
    assert not False
    assert "hello" == "hello"
    empty = ""
    assert empty == ""
    assert [1, 2, 3] == [1, 2, 3]
    t = (1, "hi")
    assert t[0] == 1
    d = {"a": 1}
    assert d["a"] == 1
    s = {1, 2}
    assert 1  in  s
    n = None
    assert n  is  None
    print("✅ 所有类型和字面量测试通过")
