# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __getitem__(self, i): return self._v
    def __setitem__(self, i, v): self._v = v
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __getitem__(self, i): return self._v
    def __setitem__(self, i, v): self._v = v
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __getitem__(self, i): return self._v
    def __setitem__(self, i, v): self._v = v
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def __lz_expect_fail(m): raise LZError(m)
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc
def _lz_dbg(v):
    if v is True: return "true"
    if v is False: return "false"
    if v is None: return "None"
    if isinstance(v, str):
        return '"' + v.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t") + '"'
    if isinstance(v, (list, tuple)):
        o, c = ("[", "]") if isinstance(v, list) else ("(", ")")
        s = ", ".join(_lz_dbg(x) for x in v)
        if not isinstance(v, list) and len(v) == 1: s += ","
        return o + s + c
    if isinstance(v, dict):
        return "{" + ", ".join(_lz_dbg(k) + ": " + _lz_dbg(x) for k, x in v.items()) + "}"
    if isinstance(v, BaseException):
        return _lz_dbg(str(v))
    return repr(v)

def _lz_idx_str(s, i):
    return ord(s[i]) if 0 <= i < len(s) else 0

def _lz_fs(v):
    return v if isinstance(v, str) else _lz_dbg(v)

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

def main():
    assert 1 + 2 == 3
    assert 5 - 3 == 2
    assert 4 * 5 == 20
    assert 10 // 2 == 5
    assert 10 % 3 == 1
    assert 2 ** 3 == 8
    assert 1 < 2
    assert 2 > 1
    assert 2 <= 2
    assert 2 >= 2
    assert not (1 == 2)
    assert True and True
    assert False or True
    assert not False
    assert (True and True)
    assert (False or True)
    assert not False
    x = 10  # mut
    x = x + 5
    assert x == 15
    x = x - 3
    assert x == 12
    x = x * 2
    assert x == 24
    print(_lz_dbg("✅ 所有运算测试通过"))

__name__ = "main"  # const: str
__file__ = "test_operators.lz"  # const: str
__package__ = "99_self_test"  # const: str
__path__ = "CY/TESTS/99_self_test"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
