# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "primitives"
__file__ = "TESTS/02_types/primitives.lz"
__all__ = ["main"]

def main():
    cdef int a = 42
    cdef float b = 3.14
    cdef str c = "hello"
    cdef bool d = True
    print(a, b, c, d)
