# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef void main():
    name = Some("Alice")
    fallback = name.__null_coalesce("guest")
    print(fallback)
    none_name = None
    print(none_name.__null_coalesce("guest"))
    a = None
    b = None
    c = Some(9)
    print(a.__null_coalesce(b).__null_coalesce(c).__null_coalesce(0))

str __name__ = "main"
str __file__ = "DEMO/05_expressions/null_coalesce.lz"
str __package__ = "05_expressions"
str __path__ = "DEMO/05_expressions"
str __doc__ = ""
bint __is_macro__ = False
