# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["consume_str", "pass_through", "just_read", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef Py_ssize_t consume_str(str s):
    s.len()

cdef Py_ssize_t pass_through(str s):
    consume_str(s)

cdef Py_ssize_t just_read(str s):
    s.len()

cdef void main():
    a = "hello"
    len_a = a
    print(len_a)
    b = "world"
    len_b = consume_str(b)
    print(len_b)
    c = "chain"
    len_c = pass_through(c)
    print(len_c)
    d = 1
    d = d + 1
    print(d)
    dd = d
    print(dd)
    e = "normal"
    print(just_read(e))
    print(just_read(e))
    print("owned binding tests done")

str __name__ = "main"
str __file__ = "DEMO/03_variables/owned_binding.lz"
str __package__ = "03_variables"
str __path__ = "DEMO/03_variables"
str __doc__ = ""
bint __is_macro__ = False
