# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["fetch_data", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef str fetch_data(Py_ssize_t id):
    f"data_{id}"

cdef void main():
    f1 = __go(fetch_data(10))
    f2 = __go(fetch_data(20))
    r1 = f1.await()
    r2 = f2.await()
    print(r1, r2)

str __name__ = "main"
str __file__ = "DEMO/11_concurrency/async_spawn.lz"
str __package__ = "11_concurrency"
str __path__ = "DEMO/11_concurrency"
str __doc__ = ""
bint __is_macro__ = False
