# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["fetch", "fetch_all", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef str fetch(Py_ssize_t id):
    f"result_{id}"

cdef list fetch_all():
    a = __go(fetch(1))
    b = __go(fetch(2))
    c = __go(fetch(3))
    [a.await(), b.await(), c.await()]

cdef void main():
    results = __go(fetch_all())
    print(results.await())
    single = __go(fetch(99))
    print(single.await())

str __name__ = "main"
str __file__ = "DEMO/11_concurrency/async_more.lz"
str __package__ = "11_concurrency"
str __path__ = "DEMO/11_concurrency"
str __doc__ = ""
bint __is_macro__ = False
