# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["compute", "greet", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

import std.math
import std.math as m
from std.math import sqrt, pow
from std.collections import List, Dict, Set
from self.models import User
from super.core import engine
from std.io import *
import std.bridge.rust.serde_json
cdef Py_ssize_t compute(Py_ssize_t a, Py_ssize_t b):
    a + b

cdef str greet(str name):
    f"Hello, {name}"

cdef void main():
    print(compute(2, 3))
    print(greet("world"))

str __name__ = "main"
str __file__ = "DEMO/08_modules/import_more.lz"
str __package__ = "08_modules"
str __path__ = "DEMO/08_modules"
str __doc__ = ""
bint __is_macro__ = False
