# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

import string_macros
from string_macros import check_eq
import string_macros as sm
import string_macros
cdef void main():
    msg = print("Hello, World!")
    print(msg)
    x = 5
    if (x) == (5):    
    else:
        panic("assert failed")
    if (x * 2) == (10):    
    else:
        panic("assert failed")
    if (x + 1) == (6):    
    else:
        panic("assert failed")
    acc = 100
    acc__m3 = 0
    print(f"acc: {acc}")
    print(square(4))

str __name__ = "main"
str __file__ = "DEMO/08_modules/use_macros.lz"
str __package__ = "08_modules"
str __path__ = "DEMO/08_modules"
str __doc__ = ""
bint __is_macro__ = False
