# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "if_match_expr"
__file__ = "TESTS/05_expressions/if_match_expr.lz"
__all__ = ["sign", "main"]

cpdef sign(n: int) -> str:
    ("positive" if n > 0 else ("negative" if n < 0 else "zero"))

def main():
    print(sign(5))
    print(sign(-3))
    print(sign(0))
