# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "operators"
__file__ = "TESTS/05_expressions/operators.lz"
__all__ = ["main"]

def main():
    cdef int a = 10 + 20
    cdef int b = 10 * 2
    cdef bool c = a > b
    cdef bool d = a == 30 and b == 20
    print(a, b, c, d)
