# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T16:59:00"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["test_0", "main"]
__private__ = []
__deps__ = []
cpdef int test_0():
    print(print(print(-1)))
    match -True:
        case 0:
            return 0
        case _:
            return -1
    x = -print(print(100))
cpdef int main():
    return 0