# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T16:59:12"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["Point", "main"]
__private__ = []
__deps__ = []
cdef struct Point:
    int x
    int y
cpdef int main():
    return 0