# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T16:58:49"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["Data", "main"]
__private__ = []
__deps__ = []
cdef str name = ''
cdef int age = 0
cpdef int main():
    return 0