# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T16:58:52"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["test", "main"]
__private__ = []
__deps__ = []
cpdef list[int] test():
    return [1, 2, 3, 4, 5]
cpdef int main():
    return 0