# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Celsius", "Fahrenheit", "Box2", "convert", "unwrap", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class Celsius:
    cdef public double value
    def __init__(self, double value):
        self.value = value
    def map(self) -> Fahrenheit:    
        return Fahrenheit(value = self.value * 9.0 / 5.0 + 32.0)

cdef class Fahrenheit:
    cdef public double value
    def __init__(self, double value):
        self.value = value
    def unmap(self) -> Celsius:    
        return Celsius(value = (self.value - 32.0) * 5.0 / 9.0)

# generic<T>
cdef class Box2:
    cdef public object value
    def __init__(self, object value):
        self.value = value
    def get(self) -> object:    
        return self.value

def convert(object c) -> object:
    # generic<T, R>
    return c.map()

def unwrap(object b) -> object:
    # generic<T, R>
    return b.get()

def main():
    c = Celsius(value = 0.0)
    f = convert(c)
    print(f"0C = {f.value}F")
    b = Box2(value = 42)
    v = unwrap(b)
    print(f"boxed = {v}")
    print("multi-generic duck demo done")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\02_types\\duck_multigen.lz"  # const: str
__package__ = "02_types"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\02_types"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
# generic<T, R>
class Mapper:
    """Duck type constraint: Mapper"""
    # def T.map(...) -> object
    # def R.unmap(...) -> object

# generic<T>
class Identity:
    """Duck type constraint: Identity"""
    # def get(...) -> object

