# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Person", "Point", "Text", "show_greeting", "render_any", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class Person:
    cdef public str name
    def __init__(self, str name):
        self.name = name
    def greet(self) -> str:    
        return "hi"

cdef class Point:
    cdef public Py_ssize_t x
    cdef public Py_ssize_t y
    def __init__(self, Py_ssize_t x, Py_ssize_t y):
        self.x = x
        self.y = y

cdef class Text:
    pass
    def render(self) -> str:    
        return "rendered"
    def get_size(self) -> Py_ssize_t:    
        return 10

def show_greeting(object p) -> str:
    # generic<T>
    return p.greet()

def render_any(object t) -> str:
    # generic<T>
    return t.render()

def main():
    p = Person(name = "bob")
    print(show_greeting(p))
    pt = Point(x = 1, y = 2)
    print(f"point: {pt.x},{pt.y}")
    tx = Text()
    print(render_any(tx))
    print("duck soft keywords demo done")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\02_types\\duck_soft.lz"  # const: str
__package__ = "02_types"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\02_types"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
class Named:
    """Duck type constraint: Named"""
    # field name: str

# satisfies Named
class Greeter:
    """Duck type constraint: Greeter"""
    # def greet(...) -> str

# sealed
class ExactPoint:
    """Duck type constraint: ExactPoint"""
    # field x: Py_ssize_t
    # field y: Py_ssize_t

class Renderable:
    """Duck type constraint: Renderable"""
    # def render(...) -> str
    # def fallback(...) -> str  # default

class MultiGetter:
    """Duck type constraint: MultiGetter"""

