# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["User", "Account", "link", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class User:
    cdef public Py_ssize_t id
    cdef public str name
    def __init__(self, Py_ssize_t id, str name):
        self.id = id
        self.name = name

cdef class Account:
    cdef public Py_ssize_t id
    cdef public str name
    def __init__(self, Py_ssize_t id, str name):
        self.id = id
        self.name = name

def link(object a, object b) -> bint:
    # generic<A, B>
    return a.id == b.id and a.name == b.name

def main():
    u = User(id = 7, name = "alice")
    acc = Account(id = 7, name = "alice")
    ok = link(u, acc)
    print(f"linked: {ok}")
    print("field relation duck demo done")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\02_types\\duck_field_rel.lz"  # const: str
__package__ = "02_types"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\02_types"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
# generic<A, B>
class LinkedFields:
    """Duck type constraint: LinkedFields"""
    # field A.id: object  # rel B.id
    # field A.name: object  # rel B.name

