# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "abort"]

def main():
    a = 42
    b = 3.14
    c = "hello"
    d = True
    u = ()
    None
    annotated = 100
    named = "world"
    inf_a = 42
    inf_b = "hello"
    inf_c = [1, 2, 3]
    inf_d = (1, "hi")
    inf_e = {"key": 42}
    inf_f = {1, 2, 3}
    n = ()
    empty = []
    t = (42, "hi", True)
    __destruct_x_y_z = t
    x = __destruct_x_y_z[0]
    y = __destruct_x_y_z[1]
    z = __destruct_x_y_z[2]
    first = t
    val = 42  # mut
    r = val  # ref
    s = val  # ref
    add = lambda x, y: x + y
    boxed = Box.new(99)
    bv = boxed[0]
    print(a)
    print(b)
    print(c)
    print(d)

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\02_types\\primitives.lz"  # const: str
__package__ = "02_types"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\02_types"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def abort(str msg):
    raise LZError(msg)

