# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "UserId", "NameList"]

cdef void main():
    id = 42
    print(id)

str __name__ = "main"
str __file__ = "DEMO/02_types/type_aliases.lz"
str __package__ = "02_types"
str __path__ = "DEMO/02_types"
str __doc__ = ""
bint __is_macro__ = False
# type UserId = Py_ssize_t
ctypedef Py_ssize_t UserId
# type NameList = list
