# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef void main():
    print("hello world")
    xs = [3, 1, 4, 1, 5, 9]
    n = len(xs)
    print(n)
    s = str(42)
    print(s)
    i = int("42")
    print(i)
    f = float(3)
    print(f)
    b = bool(1)
    print(b)
    h = hash("hello")
    has = contains([1, 2, 3], 2)
    print(has)
    it = iter([1, 2, 3])
    for (idx, val) in enumerate(["a", "b", "c"]):    
        print(f"{idx}: {val}")
    for (a, b) in zip([1, 2, 3], ["x", "y", "z"]):    
        print(f"{a}{b}")
    copy = clone(xs)
    print(copy)
    sorted_xs = sort(xs)
    print(sorted_xs)
    reversed_xs = reverse(xs)
    print(reversed_xs)
    msg = format("value: {}", 42)
    print(msg)
    hello = "hello world"
    print(hello.length())
    print(hello.starts_with("hello"))
    print(hello.ends_with("world"))
    parts = hello.split(" ")
    print(parts)
    print("  trim  ".trim())
    list = [1, 2, 3]
    list.append(4)
    print(list)
    last = list.pop()
    print(last)
    print(list.length())
    list.sort()
    print("prelude demonstrated")

str __name__ = "main"
str __file__ = "DEMO/99_prelude/prelude_demo.lz"
str __package__ = "99_prelude"
str __path__ = "DEMO/99_prelude"
str __doc__ = ""
bint __is_macro__ = False
