# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython

class _Moved:
    """Ownership sentinel: access after move raises RuntimeError"""
    def __getattr__(self, name): raise RuntimeError(f"access to moved value: {name}")
    def __setattr__(self, name, v): raise RuntimeError("assign to moved value")
    def __bool__(self): raise RuntimeError("use of moved value")
    def __repr__(self): return "<_Moved>"

_MOVED = _Moved()

def _MovedCheck(v):
   """Check if value has been moved; raise RuntimeError if so."""
   if isinstance(v, _Moved):
       raise RuntimeError("use of moved value")
   return v
__name__ = "operators"
__file__ = "TESTS/05_expressions/operators.lz"
__all__ = ["main"]

def main():
    a = 10 + 20  # type: Py_ssize_t
    b = 10 * 2  # type: Py_ssize_t
    c = a > b  # type: bint
    d = a == 30 and b == 20  # type: bint
    print(a, b, c, d)
