# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T15:39:49"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["test_shadow", "test_closure", "test_same_name", "test_let_in_loop", "test_deep_nested_func", "test_global_shadow", "test_if_scope"]
__private__ = []
__deps__ = []
cpdef int test_shadow():
    cdef int x = 10
    cpdef int inner():
        cdef int x = 20
        return x
    return inner()
cpdef int test_closure():
    cdef int x = 10
    cpdef int inner():
        return x
    return inner()
cpdef int test_same_name():
    cdef int x = 1
    if x > 0:
        cdef int y = x + 1
        return y
    return 0
cpdef int test_let_in_loop():
    cdef int total = 0
    cdef int counter = 0
    for i in range(3):
        cdef int doubled = counter * 2
        total = total + doubled
        counter = counter + 1
    return total
cpdef int test_deep_nested_func():
    cpdef int level1():
        cpdef int level2():
            cpdef int level3():
                return 42
            return level3()
        return level2()
    return level1()
cdef int GLOBAL_VAL = 100
cpdef int test_global_shadow():
    cdef int GLOBAL_VAL = 200
    return GLOBAL_VAL
cpdef int test_if_scope(bool flag):
    cdef int result = 0
    if flag:
        cdef int temp = 10
        result = temp
    return result