# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T16:55:10"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["test_paren_return", "test_paren_cond", "Status", "Outer", "Vec2", "test_return_vec", "test_param_vec", "Rect", "test_loop_var", "test_compound_assign", "main"]
__private__ = []
__deps__ = []
cpdef int test_paren_return():
    return 1 + 2
cpdef int test_paren_cond():
    if 1 == 1:
        return 1
    return 0
from enum import IntEnum
class Status(IntEnum):
    Ok
    Err
from enum import IntEnum
class Outer(IntEnum):
    A
    B
cdef struct Vec2:
    int x
    int y
cpdef Vec2 test_return_vec():
    return Vec2(x=1, y=2)
cpdef int test_param_vec(Vec2 v):
    return v.x + v.y
cdef struct Rect:
    int x
    int y
    int w
    int h
cpdef int test_loop_var():
    cdef int total = 0
    for i in range(3):
        cdef int doubled = i * 2
        total = total + doubled
    return total
cpdef int test_compound_assign():
    cdef int x = 0
    x = 1
    x = x + 2
    x = x * 3
    return x
cpdef int main():
    return 0