# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T17:13:16"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["test_not", "main"]
__private__ = []
__deps__ = []
cpdef bool test_not():
    return notTrue
cpdef int main():
    return 0