# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T17:02:30"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["Vec3", "test_struct_default", "test_struct_field_access", "test_struct_return", "test_struct_param", "test_list_type", "test_list_param", "test_tuple_type", "test_option_type", "test_result_type", "test_dict_type", "main"]
__private__ = []
__deps__ = []
cdef struct Vec3:
    int x
    int y
    int z
cpdef int test_struct_default():
    cdef Vec3 v = Vec3()
    return v.x
cpdef int test_struct_field_access():
    cdef Vec3 v = Vec3(x=1, y=2, z=3)
    return v.x + v.y + v.z
cpdef Vec3 test_struct_return():
    return Vec3(x=1, y=2, z=3)
cpdef int test_struct_param(Vec3 v):
    return v.x
cpdef list[int] test_list_type():
    return [1, 2, 3]
cpdef int test_list_param(list[int] lst):
    return lst[0]
cpdef tuple[int, int] test_tuple_type():
    return (Constant(line=28, col=13), Constant(line=28, col=16))
cpdef int test_option_type():
    return 0
cpdef int test_result_type():
    return 0
cpdef int test_dict_type():
    return 0
cpdef int main():
    return 0