# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T13:30:39"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["add_one", "double", "test_pipe", "test_var_build_block", "greet", "test_call_build_block", "process_items", "test_gen_build_block", "test_fstring", "test_as_cast", "main"]
__private__ = []
__deps__ = []
cpdef int add_one(int x):
    return x + 1
cpdef int double(int x):
    return x * 2
cpdef int test_pipe():
    cdef int result = double(add_one(5))
    print(result)
    return result
cpdef int test_var_build_block():
    result = (lambda: (    x = 10    y = 20    x + y)[-1])()
    return result
cpdef str greet(str name, int age):
    return "Hello {name}, age {age}"
cpdef str test_call_build_block():
    return greet
    (lambda: (    name = "World"    age = 42)[-1])()
cpdef int process_items(list items):
    for item in items:
        print(item)
    return 0
cpdef int test_gen_build_block():
    result = process_items
    (lambda: ()[-1])()
    return result
cpdef str test_fstring():
    cdef str name = "Cypy"
    cdef int version = 2
    return "Testing {name} version {version}"
cpdef float test_as_cast():
    cdef int a = 42
    cdef float b = <float>a
    cdef int c = <int>b
    return <float>a + c
cpdef int main():
    print("=== Testing Advanced Cypy Features ===")
    print("--- Pipe Operator ---")
    cdef int pipe_result = test_pipe()
    print("Pipe result: {pipe_result}")
    print("--- Variable Build Block ---")
    cdef int var_result = test_var_build_block()
    print("Var build block result: {var_result}")
    print("--- Call Build Block ---")
    cdef str call_result = test_call_build_block()
    print("Call build block result: {call_result}")
    print("--- Generator Build Block ---")
    cdef int gen_result = test_gen_build_block()
    print("Gen build block result: {gen_result}")
    print("--- F-string ---")
    cdef str fstr_result = test_fstring()
    print("F-string result: {fstr_result}")
    print("--- As Type Cast ---")
    cdef float cast_result = test_as_cast()
    print("As cast result: {cast_result}")
    print("=== All tests passed ===")
    return 0
main()