# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T16:55:28"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["test", "main"]
__private__ = []
__deps__ = []
cpdef int test():
    cdef int x = 0
    cdef int count = 0
    while x < 10:
        x = x + 1
        if x == 5:
            continue
        count = count + 1
    return count
cpdef int main():
    return 0