# Generated by Cypy compiler
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-07-25T17:11:49"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["test_for_range", "main"]
__private__ = []
__deps__ = []
cpdef int test_for_range():
    cdef int total = 0
    for i in range(3):
        total = total + i
    return total
cpdef int main():
    return 0