# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["demo_simple", "demo_conditional", "demo_nested", "demo_loop", "add", "greet", "volume", "demo_call_tuple", "demo_call_dict", "demo_call_computed", "demo_return_in_block", "demo_return_no_value", "demo_return_in_call_block", "demo_return_scope", "complex_demo", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "multiply"]

def demo_simple():
    x = (lambda : (y + 2))()
    print(x)
    result = (lambda : (a + b))()
    print(result)

def demo_conditional():
    grade = "B"  # mut
    score = (lambda : ((90 if grade == "A" else (80 if grade == "B" else 60))))()
    print(score)

def demo_nested():
    outer = (lambda : (inner + 10))()
    print(outer)

def demo_loop():
    total = (lambda : (s))()
    print(total)

def add(Py_ssize_t a, Py_ssize_t b) -> Py_ssize_t:
    return a + b

def greet(str greeting, str name) -> str:
    return greeting + ", " + name + "!"

def volume(double width, double height, double depth) -> double:
    return width * height * depth

def demo_call_tuple():
    r1 = add((lambda : ((10, 20)))()(0), (lambda : ((10, 20)))()(1))  # mut
    print(r1)
    r4 = volume((lambda : ((2.0, 3.0, 4.0)))()(0), (lambda : ((2.0, 3.0, 4.0)))()(1), (lambda : ((2.0, 3.0, 4.0)))()(2))  # mut
    print(r4)

def demo_call_dict():
    r2 = greet(greeting = "Hello", name = "Lang-Zone")  # mut
    print(r2)

def demo_call_computed():
    r3 = add((lambda : ((a, b)))()(0), (lambda : ((a, b)))()(1))  # mut
    print(r3)
    r5 = add((lambda : ((z, 10)))()(0), (lambda : ((z, 10)))()(1))  # mut
    print(r5)

def demo_return_in_block():
    x = (lambda : (99))()
    print(x)
    print("still here")

def demo_return_no_value():
    skip = True
    x = (lambda : (100))()
    print(x)

def demo_return_in_call_block():
    use_default = True
    r = add((lambda : ((a, b)))()(0), (lambda : ((a, b)))()(1))  # mut
    print(r)

def demo_return_scope():
    x = 5  # mut
    (print("this won't run") if x > 10 else None)
    val = (lambda : (x * 2))()
    print(val + 1)

def complex_demo():
    None
    factors = (lambda : ((a, b, c)))()
    result = multiply((lambda : (factors))()(0), (lambda : (factors))()(1), (lambda : (factors))()(2))  # mut
    print(f"product: {result}")
    transformed = (lambda : (processed - 50))()
    print(f"transformed: {transformed}")

def main():
    demo_simple()
    demo_conditional()
    demo_nested()
    demo_loop()
    demo_call_tuple()
    demo_call_dict()
    demo_call_computed()
    demo_return_in_block()
    demo_return_no_value()
    demo_return_in_call_block()
    demo_return_scope()
    complex_demo()
    print("=== build blocks demo complete ===")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\12_build_blocks\\var_call_block.lz"  # const: str
__package__ = "12_build_blocks"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\12_build_blocks"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def multiply(Py_ssize_t a, Py_ssize_t b, Py_ssize_t c) -> Py_ssize_t:
    return a * b * c

