# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "struct"
__file__ = "TESTS/07_data_structures/struct.lz"
__all__ = ["main", "Point"]

def main():
    cdef p = Point(/* unhandled expr */, /* unhandled expr */)
    print(p.area())
