# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef void main():
    a = 10
    a = a + 2
    a = a - 3
    a = a * 4
    a = a / 2
    a = a % 5
    a = a & 1
    a = a | 4
    a = a ^ 1
    a = a << 1
    a = a >> 1
    print(a)

str __name__ = "main"
str __file__ = "DEMO/13_operators/compound_assign_more.lz"
str __package__ = "13_operators"
str __path__ = "DEMO/13_operators"
str __doc__ = ""
bint __is_macro__ = False
