# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["LzError", "zero_division", "cast_error", "value_error", "type_error", "index_error", "key_error", "runtime_error", "not_implemented", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "safe_divide"]

class LzError:
    pass

class ValueError(LzError):
    def __init__(self, f0):
        self.f0 = f0

class TypeError(LzError):
    def __init__(self, f0):
        self.f0 = f0

class IndexError(LzError):
    def __init__(self, f0):
        self.f0 = f0

class KeyError(LzError):
    def __init__(self, f0):
        self.f0 = f0

class RuntimeError(LzError):
    def __init__(self, f0):
        self.f0 = f0

class NotImplementedError(LzError):
    def __init__(self, f0):
        self.f0 = f0

class AssertionError(LzError):
    def __init__(self, f0):
        self.f0 = f0

class OverflowError(LzError):
    def __init__(self, f0):
        self.f0 = f0

class ZeroDivisionError(LzError):
    def __init__(self, f0):
        self.f0 = f0

class CastError(LzError):
    def __init__(self, f0):
        self.f0 = f0

class IoError(LzError):
    def __init__(self, f0):
        self.f0 = f0

class FileNotFoundError(LzError):
    def __init__(self, f0):
        self.f0 = f0

class PermissionError(LzError):
    def __init__(self, f0):
        self.f0 = f0

class ParseError(LzError):
    def __init__(self, f0):
        self.f0 = f0

class CodecError(LzError):
    def __init__(self, f0):
        self.f0 = f0

class Error:
    """Trait: Error"""
    def source(self) -> object: ...
    def description(self) -> str: ...
    def chain_str(self) -> str: ...

#   fn message(self) -> str
#   fn kind(self) -> str
#   fn value_error(msg) -> object
#   fn type_error(msg) -> object
#   fn index_error(msg) -> object
#   fn key_error(msg) -> object
#   fn runtime_error(msg) -> object
#   fn not_implemented(msg) -> object
#   fn assertion_error(msg) -> object
#   fn overflow_error(msg) -> object
#   fn zero_division(msg) -> object
#   fn cast_error(msg) -> object
#   fn io_error(msg) -> object
#   fn file_not_found(msg) -> object
#   fn permission_error(msg) -> object
#   fn parse_error(msg) -> object
#   fn codec_error(msg) -> object
#   fn __str__(self) -> str
#   fn description(self) -> str
#   fn __eq__(self, other) -> bint

def zero_division(str msg) -> object:
    raise LZError(ZeroDivisionError(msg)) if not isinstance((ZeroDivisionError(msg)), BaseException) else (ZeroDivisionError(msg))

def cast_error(str msg) -> object:
    raise LZError(CastError(msg)) if not isinstance((CastError(msg)), BaseException) else (CastError(msg))

def value_error(str msg) -> object:
    raise LZError(ValueError(msg)) if not isinstance((ValueError(msg)), BaseException) else (ValueError(msg))

def type_error(str msg) -> object:
    raise LZError(TypeError(msg)) if not isinstance((TypeError(msg)), BaseException) else (TypeError(msg))

def index_error(str msg) -> object:
    raise LZError(IndexError(msg)) if not isinstance((IndexError(msg)), BaseException) else (IndexError(msg))

def key_error(str msg) -> object:
    raise LZError(KeyError(msg)) if not isinstance((KeyError(msg)), BaseException) else (KeyError(msg))

def runtime_error(str msg) -> object:
    raise LZError(RuntimeError(msg)) if not isinstance((RuntimeError(msg)), BaseException) else (RuntimeError(msg))

def not_implemented(str msg) -> object:
    raise LZError(NotImplementedError(msg)) if not isinstance((NotImplementedError(msg)), BaseException) else (NotImplementedError(msg))

def main():
    err = LzError.value_error("invalid value")
    assert err.kind() == "ValueError"
    assert err.message() == "invalid value"
    err = LzError.type_error("expected int")
    s = err.__str__()
    assert s.contains("TypeError")
    assert s.contains("expected int")
    a = LzError.index_error("out of bounds")
    b = LzError.index_error("out of bounds")
    c = LzError.index_error("other")
    assert a.__eq__(b)
    assert a != c
    None
    result = safe_divide(10, 0)  # mut
    assert result.is_err()
    result2 = safe_divide(10, 2)
    assert result2 == 5
    err = LzError.runtime_error("outer error")
    desc = err.description()
    assert desc.contains("outer error")
    print("error.lz — all tests passed!")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\lz_std\\error.lz"  # const: str
__package__ = "lz_std"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\lz_std"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def safe_divide(Py_ssize_t a, Py_ssize_t b) -> object:
    if b == 0:
        raise LZError(LZError(LzError.zero_division("division by zero")))
    return a // b

