# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Range", "RangeInclusive", "Once", "Repeat", "RepeatN", "Empty", "Zip", "StepRange", "range", "range_to", "range_inclusive", "once", "repeat", "repeat_n", "empty", "zip", "step_range", "for_each", "map", "filter", "fold", "collect_list", "all", "any", "find", "count_if", "sum", "product", "min", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class Range:
    cdef public Py_ssize_t current
    cdef public Py_ssize_t end
    def __init__(self, Py_ssize_t current, Py_ssize_t end):
        self.current = current
        self.end = end
    def __next__(self) -> object:    
        if self.current >= self.end:
            return None
        value = self.current  # mut
        self.current = self.current + 1
        return value
    def size_hint(self) -> tuple:    
        remaining = self.end - self.current  # mut
        if remaining < 0:
            return (0, 0)
        return (remaining, remaining)

cdef class RangeInclusive:
    cdef public Py_ssize_t current
    cdef public Py_ssize_t end
    cdef public bint done
    def __init__(self, Py_ssize_t current, Py_ssize_t end, bint done):
        self.current = current
        self.end = end
        self.done = done
    def __next__(self) -> object:    
        if self.done:
            return None
        if self.current > self.end:
            return None
        value = self.current  # mut
        if self.current == self.end:
            self.done = True
        else:
            self.current = self.current + 1
        return value

# generic<T>
cdef class Once:
    cdef public object value
    def __init__(self, object value):
        self.value = value
    def __next__(self) -> object:    
        # generic<T>
        taken = self.value
        self.value = None
        return taken
    def size_hint(self) -> tuple:    
        # generic<T>
        __scrut_0 = self.value
        if __scrut_0 is not None:
            _ = __scrut_0
            return (1, 1)
        elif __scrut_0 is None:
            return (0, 0)
        else:
            pass

# generic<T>
cdef class Repeat:
    cdef public object value
    def __init__(self, object value):
        self.value = value
    def __next__(self) -> object:    
        # generic<T>
        return self.value

# generic<T>
cdef class RepeatN:
    cdef public object value
    cdef public Py_ssize_t count
    cdef public Py_ssize_t remaining
    def __init__(self, object value, Py_ssize_t count, Py_ssize_t remaining):
        self.value = value
        self.count = count
        self.remaining = remaining
    def __next__(self) -> object:    
        # generic<T>
        if self.remaining <= 0:
            return None
        self.remaining = self.remaining - 1
        return self.value
    def size_hint(self) -> tuple:    
        # generic<T>
        return (self.remaining, self.remaining)

# generic<T>
cdef class Empty:
    cdef public tuple _lz_marker
    def __init__(self, tuple _lz_marker):
        self._lz_marker = _lz_marker
    def __next__(self) -> object:    
        # generic<T>
        return None
    def size_hint(self) -> tuple:    
        # generic<T>
        return (0, 0)

# generic<A, B>
cdef class Zip:
    cdef public object a
    cdef public object b
    def __init__(self, object a, object b):
        self.a = a
        self.b = b
    def __next__(self) -> object:    
        # generic<A, B>
        __scrut_1 = (self.a.__next__(), self.b.__next__())
        if isinstance(__scrut_1, tuple) and len(__scrut_1) == 2 and __scrut_1[0] is not None and __scrut_1[1] is not None:
            a_item = __scrut_1[0]
            b_item = __scrut_1[1]
            return (a_item, b_item)
        elif True:
            _ = __scrut_1
            return None
        else:
            pass
    def size_hint(self) -> tuple:    
        # generic<A, B>
        __destruct_lo_a_hi_a = self.a.size_hint()
        lo_a = __destruct_lo_a_hi_a[0]
        hi_a = __destruct_lo_a_hi_a[1]
        __destruct_lo_b_hi_b = self.b.size_hint()
        lo_b = __destruct_lo_b_hi_b[0]
        hi_b = __destruct_lo_b_hi_b[1]
        lo = min(lo_a, lo_b)
        __scrut_2 = (hi_a, hi_b)
        if isinstance(__scrut_2, tuple) and len(__scrut_2) == 2 and __scrut_2[0] is not None and __scrut_2[1] is not None:
            x = __scrut_2[0]
            y = __scrut_2[1]
            return min(x, y)
        elif True:
            _ = __scrut_2
            return None
        else:
            pass
        hi = None
        return (lo, hi)

cdef class StepRange:
    cdef public Py_ssize_t current
    cdef public Py_ssize_t end
    cdef public Py_ssize_t step
    def __init__(self, Py_ssize_t current, Py_ssize_t end, Py_ssize_t step):
        self.current = current
        self.end = end
        self.step = step
    def __next__(self) -> object:    
        if self.step > 0 and self.current >= self.end:
            return None
        if self.step < 0 and self.current <= self.end:
            return None
        value = self.current  # mut
        self.current = self.current + self.step
        return value

# impl Iterator for Range (methods injected into class Range)
# impl Iterator for RangeInclusive (methods injected into class RangeInclusive)
# impl Iterator for Once (methods injected into class Once)
# impl Iterator for Repeat (methods injected into class Repeat)
# impl Iterator for RepeatN (methods injected into class RepeatN)
# impl Iterator for Empty (methods injected into class Empty)
# impl Iterator for Zip (methods injected into class Zip)
# impl Iterator for StepRange (methods injected into class StepRange)
def range(Py_ssize_t start, Py_ssize_t end) -> Range:
    return Range(current = start, end = end)

def range_to(Py_ssize_t end) -> Range:
    return Range(current = 0, end = end)

def range_inclusive(Py_ssize_t start, Py_ssize_t end) -> RangeInclusive:
    return RangeInclusive(current = start, end = end, done = False)

def once(object value) -> Once:
    # generic<T>
    return Once(value = value)

def repeat(object value) -> Repeat:
    # generic<T>
    return Repeat(value = value)

def repeat_n(object value, Py_ssize_t n) -> RepeatN:
    # generic<T>
    return RepeatN(value = value, count = n, remaining = n)

def empty() -> Empty:
    # generic<T>
    return Empty(_lz_marker = ())

def zip(object a, object b) -> Zip:
    # generic<A, B>
    return Zip(a = a, b = b)

def step_range(Py_ssize_t start, Py_ssize_t end, Py_ssize_t step) -> StepRange:
    return StepRange(current = start, end = end, step = step)

def for_each(object iterable, object f):
    # generic<I>
    for item in iterable:
        f(item)

def map(object iterable, object f) -> list:
    # generic<I, U>
    result = List()  # mut
    for item in iterable:
        result.push(f(item))
    return result

def filter(object iterable, object predicate) -> list:
    # generic<I>
    result = List()  # mut
    for item in iterable:
        (result.push(item) if predicate(item) else None)
    return result

def fold(object iterable, object init, object f) -> object:
    # generic<I, U>
    acc = init  # mut
    for item in iterable:
        acc = f(acc, item)
    return acc

def collect_list(object iterable) -> list:
    # generic<I>
    result = List()  # mut
    for item in iterable:
        result.push(item)
    return result

def all(object iterable, object predicate) -> bint:
    # generic<I>
    for item in iterable:
        if not predicate(item):
            return False
    return True

def any(object iterable, object predicate) -> bint:
    # generic<I>
    for item in iterable:
        if predicate(item):
            return True
    return False

def find(object iterable, object predicate) -> object:
    # generic<I>
    for item in iterable:
        if predicate(item):
            return item
    return None

def count_if(object iterable, object predicate) -> Py_ssize_t:
    # generic<I>
    n = 0  # mut
    for item in iterable:
        if predicate(item):
            n = n + 1
    return n

def sum(object iterable) -> object:
    # generic<I>
    # where I.Item: object + object
    total = I.Item.default()  # mut
    for item in iterable:
        total = total + item
    return total

def product(object iterable) -> object:
    # generic<I>
    # where I.Item: object + object
    total = I.Item.default()  # mut
    first = True  # mut
    for item in iterable:
        if first:
            total = item
            first = False
        else:
            total = total * item
    return total

def min(Py_ssize_t a, Py_ssize_t b) -> Py_ssize_t:
    if a < b:
        return a
    return b

def main():
    def __lambda_3(x):
        nonlocal total
        total = total + x
        return total
    result = collect_list(range(0, 5))
    assert result == [0, 1, 2, 3, 4]
    result = collect_list(range_inclusive(1, 3))
    assert result == [1, 2, 3]
    result = collect_list(once(42))
    assert result == [42]
    result = collect_list(repeat_n("x", 3))
    assert result == ["x", "x", "x"]
    assert collect_list(empty()) == []
    a = range(0, 3)
    b = range(10, 13)
    result = collect_list(zip(a, b))
    assert result == [(0, 10), (1, 11), (2, 12)]
    result = collect_list(step_range(0, 10, 3))
    assert result == [0, 3, 6, 9]
    total = 0  # mut
    for_each([1, 2, 3], __lambda_3)
    assert total == 6
    result = map([1, 2, 3, 4], lambda x: x * x)
    assert result == [1, 4, 9, 16]
    evens = filter([1, 2, 3, 4, 5], lambda x: x % 2 == 0)
    assert evens == [2, 4]
    result = fold([1, 2, 3, 4], 0, lambda acc, x: acc + x)
    assert result == 10
    assert all([2, 4, 6], lambda x: x % 2 == 0)
    assert not all([2, 3, 6], lambda x: x % 2 == 0)
    assert any([1, 3, 5, 6], lambda x: x % 2 == 0)
    assert not any([1, 3, 5], lambda x: x % 2 == 0)
    assert find([1, 2, 3, 4], lambda x: x > 2) == 3
    assert find([1, 2, 3], lambda x: x > 5) == None
    assert sum([1, 2, 3, 4, 5]) == 15
    assert product([1, 2, 3, 4]) == 24
    print("iter.lz — all tests passed!")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\lz_std\\iter.lz"  # const: str
__package__ = "lz_std"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\lz_std"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
