# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Option", "OptionIter", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "safe_div"]

# generic<T>
class Option:
    pass

class Some(Option):
    def __init__(self, f0):
        self.f0 = f0

class None(Option):
    pass
None_ = None()

# generic<T>
cdef class OptionIter:
    cdef public object inner
    def __init__(self, object inner):
        self.inner = inner
    def __next__(self) -> object:    
        # generic<T>
        taken = self.inner
        self.inner = None
        return taken

#   fn is_some(self) -> bint
#   fn is_none(self) -> bint
#   fn is_some_and(self, predicate) -> bint
#   fn unwrap(self) -> object
#   fn unwrap_or(self, default) -> object
#   fn unwrap_or_else(self, f) -> object
#   fn expect(self, msg) -> object
#   fn map(self, f) -> object
#   fn map_or(self, default, f) -> object
#   fn map_or_else(self, default_fn, f) -> object
#   fn and(self, other) -> object
#   fn and_then(self, f) -> object
#   fn or(self, other) -> object
#   fn or_else(self, f) -> object
#   fn filter(self, predicate) -> object
#   fn ok_or(self, err) -> object
#   fn ok_or_else(self, err_fn) -> object
#   fn flatten(self) -> object
#   fn inspect(self, f) -> object
#   fn iter(self) -> OptionIter
#   fn iter_mut(self) -> OptionIter
#   fn __bool__(self) -> bint
#   fn __eq__(self, other) -> bint
#   fn __str__(self) -> str

# impl Iterator for OptionIter (methods injected into class OptionIter)
def main():
    some_val = 42
    none_val = None
    assert some_val.is_some()
    assert not some_val.is_none()
    assert none_val.is_none()
    assert not none_val.is_some()
    val = 10
    assert val.is_some_and(lambda x: x > 5)
    assert not val.is_some_and(lambda x: x > 20)
    assert 42.unwrap() == 42
    assert 42.unwrap_or(0) == 42
    assert (None).unwrap_or(0) == 0
    result = (None).unwrap_or_else(lambda : 99)
    assert result == 99
    result = 3.map(lambda x: x * x)
    assert result == 9
    assert (None).map(lambda x: x * x) == None
    None
    result = 10.and_then(lambda x: safe_div(x, 2))
    assert result == 5
    result2 = 10.and_then(lambda x: safe_div(x, 0))
    assert result2 == None
    a = None
    b = a.or_else(lambda : 100)
    assert b == 100
    val = 5
    assert val.filter(lambda x: x > 0) == 5
    assert val.filter(lambda x: x > 10) == None
    result = 42.ok_or("error")
    assert result == 42
    val = 5
    assert val.flatten() == 5
    count = 0  # mut
    val = 42
    for item in val.iter():
        count = count + 1
        assert item == 42
    assert count == 1
    print("option.lz — all tests passed!")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\lz_std\\option.lz"  # const: str
__package__ = "lz_std"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\lz_std"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def safe_div(Py_ssize_t a, Py_ssize_t b) -> object:
    if b == 0:
        return None
    return a // b

