# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["CharIter", "join", "format", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class CharIter:
    cdef public str s
    cdef public Py_ssize_t pos
    def __init__(self, str s, Py_ssize_t pos):
        self.s = s
        self.pos = pos
    def __next__(self) -> object:    
        if self.pos >= self.s.len():
            return None
        ch = self.s.slice(self.pos, self.pos + 1)
        self.pos = self.pos + 1
        return ch
    def size_hint(self) -> tuple:    
        remaining = self.s.len() - self.pos
        return (remaining, remaining)

#   fn len(self) -> Py_ssize_t
#   fn is_empty(self) -> bint
#   fn contains(self, substr) -> bint
#   fn starts_with(self, prefix) -> bint
#   fn ends_with(self, suffix) -> bint
#   fn find(self, substr) -> object
#   fn rfind(self, substr) -> object
#   fn char_at(self, index) -> object
#   fn slice(self, start, end) -> str
#   fn slice_from(self, start) -> str
#   fn slice_to(self, end) -> str
#   fn replace(self, from, to) -> str
#   fn trim(self) -> str
#   fn trim_start(self) -> str
#   fn trim_end(self) -> str
#   fn is_whitespace(self) -> bint
#   fn to_lower(self) -> str
#   fn to_upper(self) -> str
#   fn repeat(self, n) -> str
#   fn split(self, delimiter) -> list
#   fn lines(self) -> list
#   fn chars(self) -> CharIter
#   fn __len__(self) -> Py_ssize_t
#   fn __add__(self, other) -> str
#   fn __eq__(self, other) -> bint
#   fn __str__(self) -> str

# impl Iterator for CharIter (methods injected into class CharIter)
def join(list parts, str separator) -> str:
    if parts.is_empty():
        return ""
    result = parts.first().unwrap_or("")  # mut
    i = 1  # mut
    while i < parts.len():
        result = result + separator + parts.get(i).unwrap_or("")  # mut
        i = i + 1  # mut
    return result

def format(str tpl, list args) -> str:
    result = ""  # mut
    pos = 0  # mut
    arg_idx = 0  # mut
    while pos < tpl.len():
        __scrut_0 = tpl.slice_from(pos).find("{}")
        if __scrut_0 is not None:
            idx = __scrut_0
            result = result + tpl.slice(pos, pos + idx)
            if arg_idx < args.len():
                result = result + args.get(arg_idx).unwrap_or("")
                arg_idx = arg_idx + 1
            pos = pos + idx + 2
        elif __scrut_0 is None:
            result = result + tpl.slice_from(pos)
            break
        else:
            pass
    return result

def main():
    assert "hello".len() == 5
    assert "".is_empty()
    assert not "x".is_empty()
    assert "hello world".contains("world")
    assert not "hello".contains("xyz")
    assert "hello.txt".starts_with("hello")
    assert "hello.txt".ends_with(".txt")
    assert not "hello.txt".ends_with(".md")
    assert "hello hello".find("hello") == 0
    assert "hello hello".rfind("hello") == 6
    assert "abc".find("xyz") == None
    assert "hello".slice(1, 4) == "ell"
    assert "hello".slice_from(2) == "llo"
    assert "hello".slice_to(3) == "hel"
    assert "hello world".replace("world", "lz") == "hello lz"
    assert "aaa".replace("a", "b") == "bbb"
    assert "  hello  ".trim() == "hello"
    assert "  hello".trim_start() == "hello"
    assert "hello  ".trim_end() == "hello"
    assert "Hello".to_upper() == "HELLO"
    assert "Hello".to_lower() == "hello"
    assert "ab".repeat(3) == "ababab"
    parts = "a,b,c".split(",")
    assert parts == ["a", "b", "c"]
    result = ""  # mut
    for ch in "abc".chars():
        result = result + ch
    assert result == "abc"
    assert join(["a", "b", "c"], "-") == "a-b-c"
    assert format("Hello, {}!", ["World"]) == "Hello, World!"
    print("string.lz — all tests passed!")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\lz_std\\string.lz"  # const: str
__package__ = "lz_std"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\lz_std"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
