# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["apply", "adder", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "inner"]

cdef Py_ssize_t apply(object f, Py_ssize_t x):
    f(x)

cdef object adder(Py_ssize_t n):
    lambda x: object: x + n

cdef void main():
    double = lambda x: object: x * 2
    triple = lambda x: object: x * 3
    print(double(5), triple(4))
    print(apply(double, 10))
    plus3 = adder(3)
    print(plus3(7))
    None
    print(inner(2, 3))
    composed = lambda x: object: double(triple(x))
    print(composed(2))
    noop = lambda : 42
    print(noop())
    say_hi = lambda : print("hi from closure")
    say_hi()
    f = lambda : 99
    print(f())
    a = True or False
    b = lambda : True
    print(a, b())

str __name__ = "main"
str __file__ = "DEMO/04_functions/closures_more.lz"
str __package__ = "04_functions"
str __path__ = "DEMO/04_functions"
str __doc__ = ""
bint __is_macro__ = False
cdef Py_ssize_t inner(Py_ssize_t a, Py_ssize_t b):
    a + b

