# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["fn_capture", "fnmut_capture", "fnonce_capture", "mixed_capture", "apply_twice", "closure_as_param", "closure_in_box", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

def fn_capture():
    count = 10
    get_count = lambda : count
    print(get_count())
    print(get_count())
    print(count)

def fnmut_capture():
    def __lambda_0(x):
        nonlocal total
        total = total + x
        return total
    total = 0  # mut
    (__lambda_0)(5)
    (__lambda_0)(7)
    print(total)

def fnonce_capture():
    data = [1, 2, 3]
    consume = lambda : (print(f"consuming {len(data)} items"))
    consume()

def mixed_capture():
    def __lambda_1(x):
        nonlocal offset
        offset = offset + base + x
        return offset
    base = 100
    offset = 1  # mut
    (__lambda_1)(1)
    print(offset)

def apply_twice(object f, Py_ssize_t x) -> Py_ssize_t:
    return f(f(x))

def closure_as_param():
    factor = 3
    triple = lambda n: n * factor
    print(apply_twice(triple, 2))

def closure_in_box():
    msg = "hello"
    f = lambda : msg
    boxed = Box.new(f)
    print(boxed[0])

def main():
    fn_capture()
    fnmut_capture()
    fnonce_capture()
    mixed_capture()
    closure_as_param()
    closure_in_box()

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\04_functions\\closure_capture.lz"  # const: str
__package__ = "04_functions"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\04_functions"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
