# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["by_value", "read_ref", "modify_ref", "double_in_place", "consume_str", "pass_through", "modify_and_consume", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef Py_ssize_t by_value(Py_ssize_t x):
    x * 2

cdef Py_ssize_t read_ref(list data):
    data.len()

cdef void modify_ref(list data):
    data.push(42)

cdef Py_ssize_t double_in_place(Py_ssize_t x):
    x = x * 2
    x

cdef str consume_str(str s):
    return s

cdef str pass_through(str s):
    consume_str(s)

cdef str modify_and_consume(str s):
    s = s + "!"
    return s

cdef void main():
    print(by_value(21))
    xs = [1, 2, 3]
    print(read_ref(xs))
    modify_ref(xs)
    print(xs.len())
    print(double_in_place(21))
    msg = "hi"
    back1 = consume_str(msg)
    print(back1)
    s2 = "chain"
    back2 = pass_through(s2)
    print(back2)
    s3 = "lz"
    back3 = modify_and_consume(s3)
    print(back3)
    print("param modifiers tests done")

str __name__ = "main"
str __file__ = "DEMO/04_functions/param_modifiers.lz"
str __package__ = "04_functions"
str __path__ = "DEMO/04_functions"
str __doc__ = ""
bint __is_macro__ = False
