# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython

class _Moved:
    """Ownership sentinel: access after move raises RuntimeError"""
    def __getattr__(self, name): raise RuntimeError(f"access to moved value: {name}")
    def __setattr__(self, name, v): raise RuntimeError("assign to moved value")
    def __bool__(self): raise RuntimeError("use of moved value")
    def __repr__(self): return "<_Moved>"

_MOVED = _Moved()

def _MovedCheck(v):
   """Check if value has been moved; raise RuntimeError if so."""
   if isinstance(v, _Moved):
       raise RuntimeError("use of moved value")
   return v
__name__ = "impl_demo"
__file__ = "TESTS/07_data_structures/impl_demo.lz"
__all__ = ["main", "Point"]

cdef class Point:
    cdef public double x
    cdef public double y
    def __init__(self, double x, double y):
        self.x = x
        self.y = y
    @staticmethod
    def new(x: float, y: float) -> object:
        return Point(x = x, y = y)


# impl Point (methods injected into class)
def main():
    p = Point.new(3.0, 4.0)
    print(p.x, p.y)
