# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Option2", "NestedEnum", "match_nested", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

class Option2:
    pass

class Some2(Option2):
    def __init__(self, value):
        self.value = value

class None2(Option2):
    pass
None2 = None2()

class NestedEnum:
    pass

class Inner(NestedEnum):
    def __init__(self, value):
        self.value = value

class Outer(NestedEnum):
    def __init__(self, value):
        self.value = value

def match_nested(object x) -> Py_ssize_t:
    __scrut_0 = x
    if isinstance(__scrut_0, Inner) and isinstance(__scrut_0.value, Some2):
        v = __scrut_0.value.value
        return v
    elif isinstance(__scrut_0, Inner) and __scrut_0.value is None2:
        return -1
    elif isinstance(__scrut_0, Outer) and isinstance(__scrut_0.value, Some2):
        v = __scrut_0.value.value
        return v * 10
    elif isinstance(__scrut_0, Outer) and __scrut_0.value is None2:
        return -2
    else:
        pass

def main():
    a = match_nested(Inner(value = Some2(value = 42)))
    b = match_nested(Inner(value = None2))
    c = match_nested(Outer(value = Some2(value = 7)))
    d = match_nested(Outer(value = None2))
    print(a, b, c, d)

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\99_spec\\ir-edge-nested-match.lz"  # const: str
__package__ = "99_spec"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\99_spec"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
