# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["numeric_boundary", "string_boundary", "collection_boundary", "boolean_edge", "nested_expressions", "match_edge", "control_flow_edge", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

def numeric_boundary():
    big = 9223372036854775807
    zero = 0
    one = 1
    pi = 3.141592653589793
    zero_f64 = 0.0
    pow_zero = 2 ** 0
    shift_max = 1 << 63
    print(pow_zero, shift_max, big)

def string_boundary():
    empty = ""
    concat = "Hello, " + "World!"
    repeated = "a" in "abc"
    not_found = "z" in "abc"
    print(concat, repeated)

def collection_boundary():
    empty_list = []
    single_list = [42]
    in_empty = 1 in empty_list
    in_single = 42 in single_list
    first = single_list[0]
    print(first, in_empty, in_single)

def boolean_edge():
    t = True
    f = False
    chain1 = 1 < 2 < 3 and 3 < 4
    not_cmp = not True == False
    not_not = not not True
    print(chain1, not_cmp)

def nested_expressions():
    a = 1
    b = 2
    c = 3
    deep1 = ((a + b) * (c - a)) // (b + 1)
    deep2 = a + b + c + a + b + c
    print(deep1, deep2)

def match_edge(Py_ssize_t x) -> Py_ssize_t:
    __scrut_0 = x
    if __scrut_0 == 0:
        return 0
    elif __scrut_0 == 1:
        return 1
    elif True:
        _ = __scrut_0
        return x * 2
    else:
        pass

def control_flow_edge(Py_ssize_t n) -> Py_ssize_t:
    if n <= 0:
        return 0
    result = 0  # mut
    for i in range(1, n):
        if i % 2 == 0:
            continue
        result = result + i
    return result

def main():
    numeric_boundary()
    string_boundary()
    collection_boundary()
    boolean_edge()
    nested_expressions()
    print(match_edge(5))
    print(control_flow_edge(10))
    print("boundary tests done")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\99_spec\\ir-edge-boundary-values.lz"  # const: str
__package__ = "99_spec"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\99_spec"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
