# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["max_int", "min_int", "test_int_convert", "test_float_convert", "test_str_to_int", "test_str_to_float", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef Py_ssize_t max_int():
    9223372036854775807

cdef Py_ssize_t min_int():
    --9223372036854775808

cdef str test_int_convert(Py_ssize_t x):
    str(x)

cdef str test_float_convert(double x):
    str(x)

cdef Py_ssize_t test_str_to_int(str s):
    int(s)

cdef double test_str_to_float(str s):
    float(s)

cdef void main():
    a = max_int()
    b = min_int()
    sa = test_int_convert(a)
    sb = test_int_convert(b)
    sf = test_float_convert(3.14159)
    si = test_str_to_int("42")
    sfi = test_str_to_float("2.718")
    print(sa, sb, sf, si, sfi)

str __name__ = "main"
str __file__ = "DEMO/99_spec/ir-edge-type-boundary.lz"
str __package__ = "99_spec"
str __path__ = "DEMO/99_spec"
str __doc__ = ""
bint __is_macro__ = False
