# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef void main():
    i = 0
    while i < 3:    
        i = i + 1
    total = 0
    for k in Range(start = 1, end = 4):    
        total = total + k

str __name__ = "main"
str __file__ = "DEMO/99_spec/loop_else.lz"
str __package__ = "99_spec"
str __path__ = "DEMO/99_spec"
str __doc__ = ""
bint __is_macro__ = False
