# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "config"]

cdef void main():
    print(config)

str __name__ = "main"
str __file__ = "DEMO/99_spec/top_level_build.lz"
str __package__ = "99_spec"
str __path__ = "DEMO/99_spec"
str __doc__ = ""
bint __is_macro__ = False
cdef object config = (begin
    # Let { name: "host", ty: Str, value: Expr { kind: Lit(Str("localhost")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }
    # Let { name: "port", ty: Int, value: Expr { kind: Lit(Int(8080)), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }
    # ExprStmt { expr: Expr { kind: TupleLit([Expr { kind: Var("host"), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, Expr { kind: Var("port"), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }]), ty: Tuple([Str, Int]), span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }

)
