# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["sum3", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef Py_ssize_t sum3(Py_ssize_t a, Py_ssize_t b, Py_ssize_t c, Py_ssize_t d):
    a + b + c + d

cdef void main():
    f = lambda __p0: object, __p1: object: sum3(__p0, 2, 3, __p1)
    print(f(1, 4))

str __name__ = "main"
str __file__ = "DEMO/99_spec/underscore_partial_2.lz"
str __package__ = "99_spec"
str __path__ = "DEMO/99_spec"
str __doc__ = ""
bint __is_macro__ = False
