# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "comprehension_pipe"
__file__ = "TESTS/05_expressions/comprehension_pipe.lz"
__all__ = ["main"]

def main():
    cdef squares = [x * x for x in range(0, 10) if x % 2 == 0]
    print(squares)
    cdef double = lambda x: x * 2
    cdef result = double(5)
    print(result)
