# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "literals"
__file__ = "../DEMO/01_basics/literals.lz"
__all__ = ["main"]

def main():
    cdef Py_ssize_t dec = 42
    cdef Py_ssize_t hex = 255
    cdef Py_ssize_t oct = 63
    cdef Py_ssize_t bin = 10
    print("integers:", dec, hex, oct, bin)
    cdef double pi = 3.14
    cdef double sci = 10000000000.0
    cdef double small = 0.0025
    print("floats:", pi, sci, small)
    cdef str s = "hello LZ"
    cdef str name = "world"
    cdef str fs = f"hello {name}"
    cdef str raw = r"\d+\.\d+"
    cdef str multi = """line one
    line two
    line three"""
    cdef Py_ssize_t val = 42
    cdef str fmulti = f"""value is {val}
    next line"""
    cdef str rmulti = r""
    """d+.d+
    [a-z]+"""
    ""
    print("strings:", s, fs, raw)
    cdef bint t = True
    cdef bint f = False
    cdef object n = None
    cdef object sv = Some(42)
    cdef object ok = Ok(1)
    cdef object err = Err("fail")
    cdef void u = None
    cdef object empty = []
    # nested fn: loop_forever
    print("bool/special:", t, f, sv, ok)
    cdef object xs = [1, 2, 3]
    cdef object tp = (1, "hi")
    cdef object d = {"a": 1, "b": 2}
    cdef object st = {1, 2, 3}
    cdef object empty_dict = {}
    print("collections:", xs, tp, d, st)
    cdef object r1 = range(0, 10)
    cdef object r2 = range(0, 9 + 1)
    print("ranges:", r1, r2)
    print("All literals demonstrated successfully")
