# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython

class _Moved:
    """Ownership sentinel: access after move raises RuntimeError"""
    def __getattr__(self, name): raise RuntimeError(f"access to moved value: {name}")
    def __setattr__(self, name, v): raise RuntimeError("assign to moved value")
    def __bool__(self): raise RuntimeError("use of moved value")
    def __repr__(self): return "<_Moved>"

_MOVED = _Moved()
__name__ = "elif_test"
__file__ = "TESTS/05_expressions/elif_test.lz"
__all__ = ["describe"]

cpdef str describe(x):
    if x  is  int:
        "integer"
    elif x  is  str:
        return "string"
    else:
        return "unknown"
