# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "enum"
__file__ = "TESTS/07_data_structures/enum.lz"
__all__ = ["main", "Color"]

cdef class Color:
    cdef public Py_ssize_t _variant
    def __init__(self, Py_ssize_t variant):
        self._variant = variant
    @staticmethod
    def Red():
        return Color(0)
    @staticmethod
    def Green():
        return Color(1)
    @staticmethod
    def Blue():
        return Color(2)

def main():
    cdef c = Color.Red
    print(c)
