# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "enum_data"
__file__ = "TESTS/07_data_structures/enum_data.lz"
__all__ = ["main", "Shape"]

cdef class Shape:
    cdef public Py_ssize_t _variant
    cdef public object _data
    def __init__(self, Py_ssize_t variant, object data = None):
        self._variant = variant
        self._data = data
    @staticmethod
    def Circle(p0: float, p1: float, p2: float):
        return Shape(0, (p0, p1, p2))
    @staticmethod
    def Rect(p0: float, p1: float):
        return Shape(1, (p0, p1))
    @staticmethod
    def Point():
        return Shape(2, None)

def main():
    cdef c = Shape.Circle(0.0, 0.0, 5.0)
    cdef r = Shape.Rect(10.0, 20.0)
    cdef p = Shape.Point()
    print(c)
    print(r)
    print(p)
