# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython

class _Moved:
    """Ownership sentinel: access after move raises RuntimeError"""
    def __getattr__(self, name): raise RuntimeError(f"access to moved value: {name}")
    def __setattr__(self, name, v): raise RuntimeError("assign to moved value")
    def __bool__(self): raise RuntimeError("use of moved value")
    def __repr__(self): return "<_Moved>"

_MOVED = _Moved()
__name__ = "enum_multi"
__file__ = "TESTS/07_data_structures/enum_multi.lz"
__all__ = ["main", "Color", "Shape"]

cdef class Color:
    cdef public Py_ssize_t _variant
    def __init__(self, Py_ssize_t variant, object data = None):
        self._variant = variant
    @staticmethod
    def Red():
        return Color(0, None)
    @staticmethod
    def Green():
        return Color(1, None)
    @staticmethod
    def Blue():
        return Color(2, None)

cdef class Shape:
    cdef public Py_ssize_t _variant
    cdef public object _data
    def __init__(self, Py_ssize_t variant, object data = None):
        self._variant = variant
        self._data = data
    @staticmethod
    def Circle(x: float, y: float, radius: float):
        return Shape(0, dict(x=x, y=y, radius=radius))
    @staticmethod
    def Point():
        return Shape(1, None)

def main():
    print("ok")
