# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "generics_test"
__file__ = "TESTS/02_types/generics_test.lz"
__all__ = ["sum_list", "main"]

cpdef Py_ssize_t sum_list(xs: list[int]):
    cdef total = 0
    for x in xs:
        total += x
    return total

def main():
    cdef object nums = [1, 2, 3, 4, 5]
    print(sum_list(nums))
