# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "literals"
__file__ = "../DEMO/01_basics/literals.lz"
__all__ = ["main"]

def main():
    cdef int dec = 42
    cdef int hex = 255
    cdef int oct = 63
    cdef int bin = 10
    print("integers:", dec, hex, oct, bin)
    cdef float pi = 3.14
    cdef float sci = 10000000000.0
    cdef float small = 0.0025
    print("floats:", pi, sci, small)
    cdef str s = "hello LZ"
    cdef str name = "world"
    cdef str fs = f"hello {name}"
    cdef str raw = r"\d+\.\d+"
    cdef str multi = """line one
    line two
    line three"""
    cdef int val = 42
    cdef str fmulti = f"""value is {val}
    next line"""
    cdef str rmulti = r""
    """d+.d+
    [a-z]+"""
    ""
    print("strings:", s, fs, raw)
    cdef bool t = True
    cdef bool f = False
    cdef Optional[int] n = None
    cdef Optional[int] sv = Some(42)
    cdef Union[int] ok = Ok(1)
    cdef Union[int] err = Err("fail")
    cdef None u = None
    cdef object empty = []
    # nested fn: loop_forever
    print("bool/special:", t, f, sv, ok)
    cdef list[int] xs = [1, 2, 3]
    cdef (int, str) tp = (1, "hi")
    cdef dict[str, int] d = {"a": 1, "b": 2}
    cdef set[int] st = {1, 2, 3}
    cdef dict[str, int] empty_dict = {}
    print("collections:", xs, tp, d, st)
    cdef range r1 = range(0, 10)
    cdef range r2 = range(0, 9 + 1)
    print("ranges:", r1, r2)
    print("All literals demonstrated successfully")
