# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "match_demo"
__file__ = "TESTS/05_expressions/match_demo.lz"
__all__ = ["describe", "main"]

cpdef str describe(n: int):
    return (lambda __v: "zero" if __v == 0 else "one" if __v == 1 else "other")(n)

def main():
    print(describe(0))
    print(describe(1))
    print(describe(2))
