# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "trait_demo"
__file__ = "TESTS/07_data_structures/trait_demo.lz"
__all__ = ["main"]

class Drawable:
    from abc import abstractmethod
    @abstractmethod
    def draw(self) -> (): ...
    @abstractmethod
    def name(self) -> str:
        pass

def main():
    print("trait test")
