# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "try_catch"
__file__ = "TESTS/10_error_handling/try_catch.lz"
__all__ = ["main"]

def main():
    try:
        print("trying")
    except e as e:
        print("caught")
    finally:
        print("cleanup")
    print("done")
