# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "mutable_let"
__file__ = "TESTS/03_variables/mutable_let.lz"
__all__ = ["main"]

def main():
    cdef int x = 42
    cdef y = "hello"
    cdef y = "world"
    print(x, y)
