# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "box_rc_arc"
__file__ = "TESTS/14_pointers/box_rc_arc.lz"
__all__ = ["main"]

def main():
    cdef object[int] x = Box.new(42)
    cdef object[str] y = Rc.new("hello")
    print(x[0], y[0])
