# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["fib", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef Py_ssize_t fib(Py_ssize_t n):
    (n if n <= 1 else fib(n - 1) + fib(n - 2))

cdef void main():
    print(fib(10))

str __name__ = "main"
str __file__ = "DEMO/memoize_demo.lz"
str __package__ = "DEMO"
str __path__ = "DEMO"
str __doc__ = ""
bint __is_macro__ = False
