# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["add", "add", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef Py_ssize_t add__0(Py_ssize_t a, Py_ssize_t b):
    a + b

cdef str add__1(str a, str b):
    a + b

cdef void main():
    print(add(1, 2))
    print(add("hello", " world"))

str __name__ = "main"
str __file__ = "DEMO/overload_test.lz"
str __package__ = "DEMO"
str __path__ = "DEMO"
str __doc__ = ""
bint __is_macro__ = False
def add(*args):
    if len(args) == 2: return add__0(*args)
    elif len(args) == 2: return add__1(*args)
    else: raise TypeError(f"add: no matching overload for {len(args)} args")

