# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["classify", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef str classify(Py_ssize_t n):
    # match n
    if __scrutinee__ == 0:    
        "empty"
    elif __scrutinee__ == 1:    
        "single"
    _ = __scrutinee__
    elif True  # bind _:    
        ("big" if n > 10 else "small")

cdef void main():
    print(classify(0))
    print(classify(1))
    print(classify(20))

str __name__ = "main"
str __file__ = "DEMO/combo-syntax/combo_match_ternary.lz"
str __package__ = "combo-syntax"
str __path__ = "DEMO/combo-syntax"
str __doc__ = ""
bint __is_macro__ = False
