# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Counter", "add", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class Counter:
    cdef public Py_ssize_t value
    def __init__(self, Py_ssize_t value):        self.value = value
    cdef Py_ssize_t bump(self):    
        inc = lambda __p0: object: add(__p0, 1)
        inc(self.value)

cdef Py_ssize_t add(Py_ssize_t a, Py_ssize_t b):
    a + b

cdef void main():
    c = Counter(_KwArg(name = "value", value = 10))
    print(c.bump())

str __name__ = "main"
str __file__ = "DEMO/combo-syntax/combo_struct_method_partial.lz"
str __package__ = "combo-syntax"
str __path__ = "DEMO/combo-syntax"
str __doc__ = ""
bint __is_macro__ = False
