# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["counter", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef Py_ssize_t counter(Py_ssize_t n):
    i = 0
    while i < n:    
        yield i
        i = i + 1

cdef void main():
    for x in counter(3):    
        print(x)

str __name__ = "main"
str __file__ = "DEMO/15_generators/yield_infer.lz"
str __package__ = "15_generators"
str __path__ = "DEMO/15_generators"
str __doc__ = ""
bint __is_macro__ = False
