# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "identifiers"
__file__ = "TESTS/01_basics/identifiers.lz"
__all__ = ["main"]

def main():
    cdef x = 1
    cdef my_var = 2
    cdef _private = 3
    print(x + my_var + _private)
