# Generated by lzcyc — LZ → Cython compiler
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: nonecheck=False

import cython
__name__ = "literals"
__file__ = "TESTS/01_basics/literals.lz"
__all__ = ["main"]

def main():
    print(42)
    print(3.14)
    print("hello")
    print(True)
    print(False)
    print(None)
