# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["User", "Container", "Resource", "Score", "Book", "Calculator", "process_user", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class User:
    cdef public Py_ssize_t id
    cdef public str name
    def __init__(self, Py_ssize_t id, str name):
        self.id = id
        self.name = name
    def validate(self) -> bint:    
        return self.id > 0 and self.name != ""

# generic<T>
cdef class Container:
    cdef public object data
    def __init__(self, object data):
        self.data = data
    def is_present(self) -> bint:    
        __scrut_0 = self.data
        if __scrut_0 is not None:
            _ = __scrut_0
            return True
        elif __scrut_0 is None:
            return False
        else:
            pass
    def get_or(self, object default) -> object:    
        __scrut_1 = self.data
        if __scrut_1 is not None:
            v = __scrut_1
            return v
        elif __scrut_1 is None:
            return default
        else:
            pass
    def map(self, object f) -> Container:    
        # generic<R>
        return Container(data = (None))

cdef class Resource:
    cdef public Py_ssize_t id
    def __init__(self, Py_ssize_t id):
        self.id = id
    def __enter__(self) -> Resource:    
        print(f"enter:{self.id}")
        return self
    def __exit__(self):    
        print(f"exit:{self.id}")
    def work(self) -> Py_ssize_t:    
        return self.id * 10

cdef class Score:
    cdef public Py_ssize_t math
    cdef public Py_ssize_t english
    def __init__(self, Py_ssize_t math, Py_ssize_t english):
        self.math = math
        self.english = english
    def grade(self) -> str:    
        avg = (self.math + self.english) // 2
        __scrut_2 = avg
        if (True) and (__scrut_2 >= 90):
            v = __scrut_2
            return "A"
        elif (True) and (__scrut_2 >= 80):
            v = __scrut_2
            return "B"
        elif (True) and (__scrut_2 >= 70):
            v = __scrut_2
            return "C"
        elif (True) and (__scrut_2 >= 60):
            v = __scrut_2
            return "D"
        elif True:
            _ = __scrut_2
            return "F"
        else:
            pass
    def is_pass(self) -> bint:    
        return self.math >= 60 and self.english >= 60

cdef class Book:
    cdef public str title
    cdef public Py_ssize_t pages
    def __init__(self, str title, Py_ssize_t pages):
        self.title = title
        self.pages = pages
    def format(self) -> str:    
        return f"Book({self.title}, {self.pages}p)"

class Calculator:
    pass

class Add(Calculator):
    def __init__(self, f0, f1):
        self.f0 = f0
        self.f1 = f1

class Mul(Calculator):
    def __init__(self, f0, f1):
        self.f0 = f0
        self.f1 = f1

class Div(Calculator):
    def __init__(self, f0, f1):
        self.f0 = f0
        self.f1 = f1

class Printable:
    """Trait: Printable"""
    def format(self) -> str: ...

# impl Printable for Book (methods injected into class Book)
#   fn compute(self) -> object
#   fn apply(self, f) -> object

def process_user(User u) -> str:
    if u.validate():
        pass
    else:
        return "invalid_user"
    try:
        f"user_{u.id}:{u.name}"
    except BaseException as e:
        "error"
    return

def main():
    print("=== combo-struct-method ===")
    print(process_user(User(id = 1, name = "Alice")))
    print(process_user(User(id = -1, name = "")))
    print(process_user(User(id = 2, name = "")))
    c1 = Container(data = 42)
    c2 = Container(data = None)
    print(c1.is_present())
    print(c2.is_present())
    print(c1.get_or(0))
    print(c2.get_or(0))
    c3 = c1.map(lambda x: x * 2)
    print(c3.get_or(0))
    __with_res = Resource(id = 1)  # mut
    res = __with_res.__enter__()  # mut
    print(res.work())
    res.__exit__()
    s1 = Score(math = 85, english = 92)
    s2 = Score(math = 55, english = 65)
    print(s1.grade())
    print(s2.grade())
    print(s1.is_pass())
    print(s2.is_pass())
    book = Book(title = "LZ Guide", pages = 200)
    print(book.format())
    calc1 = Add(10, 20)
    calc2 = Div(100, 0)
    calc3 = Mul(5, 6)
    print(calc1.compute())
    print(calc2.compute())
    print(calc3.compute())
    calc4 = calc1.apply(lambda x: x + 1)
    print(calc4.compute())
    print("combo-struct-method done")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage\\combo-struct-method.lz"  # const: str
__package__ = "boundary-coverage"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
