# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["DataBlock", "Expr", "Adder", "sum_measures", "process_dual", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class DataBlock:
    cdef public Py_ssize_t size
    cdef public str label
    def __init__(self, Py_ssize_t size, str label):
        self.size = size
        self.label = label
    def measure(self) -> Py_ssize_t:    
        return self.size

class Expr:
    pass

class Literal(Expr):
    def __init__(self, f0):
        self.f0 = f0

class Add(Expr):
    def __init__(self, f0, f1):
        self.f0 = f0
        self.f1 = f1

cdef class Adder:
    cdef public Py_ssize_t delta
    def __init__(self, Py_ssize_t delta):
        self.delta = delta
    def measure(self) -> Py_ssize_t:    
        f = lambda x: x + self.delta
        return f(0)

class Measurable:
    """Trait: Measurable"""
    def measure(self) -> Py_ssize_t: ...
    def describe(self) -> str: ...

class ValueHolder:
    """Trait: ValueHolder"""
    def get_value(self) -> Py_ssize_t: ...

class Resettable:
    """Trait: Resettable"""
    def reset(self) -> void: ...

# supertraits: object
class Configurable:
    """Trait: Configurable"""
    def configure(self, dict params) -> void: ...

# impl Measurable for DataBlock (methods injected into class DataBlock)
# impl ValueHolder for Expr (std target: methods not injectable)
#   fn get_value(self) -> Py_ssize_t

# impl Measurable for Adder (methods injected into class Adder)
def sum_measures(list items) -> Py_ssize_t:
    # generic<T>
    total = 0  # mut
    for item in items:
        total = total + item.measure()
    return total

def process_dual(object a, object b) -> Py_ssize_t:
    # generic<A, B>
    return a.measure() + b.measure()

def main():
    print("=== combo-trait-impl ===")
    data = DataBlock(size = 100, label = "test")
    print(data.measure())
    print(data.describe())
    items = [DataBlock(size = 10, label = "a"), DataBlock(size = 20, label = "b")]
    print(sum_measures(items))
    a = DataBlock(size = 30, label = "x")
    b = DataBlock(size = 40, label = "y")
    print(process_dual(a, b))
    expr = Add(Literal(5), Literal(10))
    print(expr.get_value())
    adder = Adder(delta = 100)
    print(adder.measure())
    print("combo-trait-impl done")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage\\combo-trait-impl.lz"  # const: str
__package__ = "boundary-coverage"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
