# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["build_if_else", "build_match", "build_try", "build_from_for", "process_data", "build_call", "build_index_conditional", "multiply_pair", "build_closure_value", "nested_build_blocks", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "pairs"]

def build_if_else(bint flag) -> Py_ssize_t:
    result = (lambda : ((100 if flag else 0)))()
    return result

def build_match(Py_ssize_t x) -> str:
    description = (lambda : (None))()
    return description

def build_try(Py_ssize_t a, Py_ssize_t b) -> Py_ssize_t:
    result = (lambda : ((None)))()
    return result

def build_from_for(list items) -> list:
    doubled = (lambda : ([(lambda x: x * 2)(__cv) for __cv in (items)]))()
    return doubled

def process_data(Py_ssize_t a, Py_ssize_t b, Py_ssize_t c) -> tuple:
    return (a * 1, b * 2, c * 3)

def build_call():
    result = process_data((lambda : ((1, 2, 3)))()(0), (lambda : ((1, 2, 3)))()(1), (lambda : ((1, 2, 3)))()(2))
    print(result)

def build_index_conditional(list xs, bint flag) -> Py_ssize_t:
    idx = (lambda : ((0 if flag else xs.len() - 1)))()
    return idx

def multiply_pair(Py_ssize_t a, Py_ssize_t b) -> tuple:
    return (a, b, a * b)

def build_closure_value():
    compute = (lambda : (add(10, mul(2, 3))))()

def nested_build_blocks(Py_ssize_t a) -> Py_ssize_t:
    base = (lambda : (inner + 5))()
    return base

def main():
    print("=== combo-build-block ===")
    print(build_if_else(True))
    print(build_if_else(False))
    print(build_match(0))
    print(build_match(1))
    print(build_match(5))
    print(build_try(10, 2))
    print(build_try(10, 0))
    print(build_from_for([1, 2, 3, 4]))
    build_call()
    print(build_index_conditional([100, 200, 300], True))
    print(build_index_conditional([100, 200, 300], False))
    for p in pairs:
        print(p)
    print(build_closure_value())
    print(nested_build_blocks(3))
    print("combo-build-block done")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage\\combo-build-block.lz"  # const: str
__package__ = "boundary-coverage"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
pairs = None  # gen_build multiply_pair (3 stmts)  # const: list
