# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["FileHandle", "Wrap", "defer_lifo_order", "defer_guard_combo", "guard_try_catch", "all_combined", "with_defer_try", "guard_let_try", "nested_with", "try_else_guard", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class FileHandle:
    cdef public str path
    def __init__(self, str path):
        self.path = path
    def __enter__(self) -> FileHandle:    
        print(f"open:{self.path}")
        return self
    def __exit__(self):    
        print(f"close:{self.path}")

class Wrap:
    pass

class Data(Wrap):
    def __init__(self, value):
        self.value = value

class Empty(Wrap):
    pass
Empty = Empty()

def defer_lifo_order():
    print("body")
    print("defer_3")
    print("defer_2")
    print("defer_1")

def defer_guard_combo(Py_ssize_t x) -> str:
    if x > 0:
        pass
    else:
        return "negative"
    if x != 5:
        pass
    else:
        return "is_five"
    return f"positive:{x}"
    print(f"finally:{x}")

def guard_try_catch(Py_ssize_t value) -> Py_ssize_t:
    if value != 0:
        pass
    else:
        return 0
    try:
        100 // value
    except BaseException as e:
        -1
    return

def all_combined(Py_ssize_t data) -> Py_ssize_t:
    if data >= 0:
        pass
    else:
        return -100
    try:
        result = 1000 // (data + 1)
        result
    except BaseException as e:
        -200
    finally:
        print("attempted")
    return
    print("cleanup_step")

def with_defer_try(str path) -> Py_ssize_t:
    __with_f = FileHandle(path = path)  # mut
    f = __with_f.__enter__()  # mut
    try:
        if path == "":
            raise LZError("empty_path") if not isinstance(("empty_path"), BaseException) else ("empty_path")
        path.len()
    except BaseException as e:
        0
    f.__exit__()
    print("defer_cleanup")

def guard_let_try(object w) -> Py_ssize_t:
    __scrut_0 = w
    if isinstance(__scrut_0, Data):
        v = __scrut_0.value
        try:
            v * 10
        except BaseException as e:
            -2
        return
    elif True:
        return -1
    else:
        pass

def nested_with():
    __with_f1 = FileHandle(path = "a.txt")  # mut
    f1 = __with_f1.__enter__()  # mut
    f2 = FileHandle(path = "b.txt")  # mut
    f3 = FileHandle(path = "c.txt")  # mut
    print("nested_work")
    f1.__exit__()

def try_else_guard(Py_ssize_t x) -> str:
    try:
        if x != 0:
            pass
        else:
            raise LZError("zero") if not isinstance(("zero"), BaseException) else ("zero")
        100 // x
    except BaseException as e:
        "caught"
    else:
        "success"
    return

def main():
    print("=== combo-defer-guard ===")
    defer_lifo_order()
    print(defer_guard_combo(10))
    print(defer_guard_combo(-1))
    print(defer_guard_combo(5))
    print(guard_try_catch(10))
    print(guard_try_catch(0))
    print(all_combined(9))
    print(all_combined(-1))
    print(with_defer_try("hello"))
    print(with_defer_try(""))
    print(guard_let_try(Data(value = 5)))
    print(guard_let_try(Empty))
    nested_with()
    print(try_else_guard(2))
    print(try_else_guard(0))
    print("combo-defer-guard done")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage\\combo-defer-guard.lz"  # const: str
__package__ = "boundary-coverage"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
