# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["deep_pipe_chain", "inc", "double", "dec", "pipe_with_lambda", "pipe_match", "add3", "pipe_partial", "if_func", "pipe_conditional", "async_double", "async_add", "pipe_async", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

def deep_pipe_chain(Py_ssize_t x) -> Py_ssize_t:
    return inc(dec(double(double(inc(inc(inc(x)))))))

def inc(Py_ssize_t x) -> Py_ssize_t:
    return x + 1

def double(Py_ssize_t x) -> Py_ssize_t:
    return x * 2

def dec(Py_ssize_t x) -> Py_ssize_t:
    return x - 1

def pipe_with_lambda(list data) -> Py_ssize_t:
    return fold(map(filter(data, lambda x: x > 0), lambda x: x * 3), 0, lambda acc, x: acc + x)

def pipe_match(Py_ssize_t val) -> str:
    return (lambda x: (None))(double(val))

def add3(Py_ssize_t a, Py_ssize_t b, Py_ssize_t c) -> Py_ssize_t:
    return a + b + c

def pipe_partial(list data) -> list:
    return map(data, lambda __p0: add3(__p0, 10, 20))

def if_func(bint flag) -> object:
    return (double if flag else inc)

def pipe_conditional(Py_ssize_t x, bint flag) -> Py_ssize_t:
    return if_func(flag)(x)

async def async_double(Py_ssize_t x) -> Py_ssize_t:
    return x * 2

async def async_add(Py_ssize_t x, Py_ssize_t y) -> Py_ssize_t:
    return x + y

async def pipe_async(Py_ssize_t x) -> object:
    r = __go(async_double(x))
    v = await r
    result = async_add(v, 5)
    return await result

async def main():
    print("=== combo-pipe-lambda ===")
    print(deep_pipe_chain(1))
    print(pipe_with_lambda([1, -2, 3, 0, 5]))
    print(pipe_match(3))
    print(pipe_match(25))
    print(pipe_match(200))
    print(pipe_partial([1, 2, 3]))
    print(pipe_conditional(5, True))
    print(pipe_conditional(5, False))
    print(await pipe_async(3))
    print("combo-pipe-lambda done")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage\\combo-pipe-lambda.lz"  # const: str
__package__ = "boundary-coverage"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
