# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["fetch_safe", "spawn_with_error_handling", "slow_double", "multiple_spawn", "go_with_defer", "go_in_loop", "classify_async", "async_with_match", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

async def fetch_safe(Py_ssize_t id) -> object:
    try:
        if id < 0:
            raise LZError("invalid_id") if not isinstance(("invalid_id"), BaseException) else ("invalid_id")
        id * 10
    except BaseException as e:
        LZError(e)
    return

async def spawn_with_error_handling():
    future = __go(fetch_safe(5))
    result = await future
    __scrut_0 = result
    if not isinstance(__scrut_0, BaseException):
        v = __scrut_0
        print(f"ok:{v}")
    elif isinstance(__scrut_0, BaseException):
        e = __scrut_0
        print(f"err:{e}")
    else:
        pass

async def slow_double(Py_ssize_t x) -> Py_ssize_t:
    return x * 2

async def multiple_spawn():
    f1 = __go(slow_double(10))
    f2 = __go(slow_double(20))
    f3 = __go(slow_double(30))
    r1 = await f1
    r2 = await f2
    r3 = await f3
    print(r1, r2, r3)

def go_with_defer():
    __go(print("concurrent_task"))
    print("main_task")
    print("main_cleanup")

def go_in_loop(Py_ssize_t n):
    for i in range(0, n):
        __go(print(f"worker_{i}"))

async def classify_async(Py_ssize_t x) -> str:
    __scrut_1 = x
    if (True) and (__scrut_1 < 0):
        v = __scrut_1
        return "negative"
    elif __scrut_1 == 0:
        return "zero"
    elif True:
        _ = __scrut_1
        return "positive"
    else:
        pass

async def async_with_match():
    f = __go(classify_async(42))
    result = await f
    print(result)

async def main():
    print("=== combo-async-await ===")
    await __go(spawn_with_error_handling())
    bad = __go(fetch_safe(-1))
    bad_result = await bad
    __scrut_2 = bad_result
    if not isinstance(__scrut_2, BaseException):
        v = __scrut_2
        print(f"unexpected:{v}")
    elif isinstance(__scrut_2, BaseException):
        e = __scrut_2
        print(f"expected_err:{e}")
    else:
        pass
    await __go(multiple_spawn())
    go_with_defer()
    go_in_loop(3)
    await __go(async_with_match())
    print("combo-async-await done")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage\\combo-async-await.lz"  # const: str
__package__ = "boundary-coverage"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
