# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["int_boundaries", "f64_boundaries", "empty_collections", "none_boundaries", "literal_boundaries", "string_boundaries", "bool_boundaries", "operator_boundaries", "collection_boundaries", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

def int_boundaries():
    max_i64 = 9223372036854775807
    min_i64 = --9223372036854775808
    zero = 0
    one = 1
    neg_one = -1
    print(zero, one, neg_one)
    print(max_i64, min_i64)

def f64_boundaries():
    zero_f = 0.0
    neg_zero = -0.0
    one_f = 1.0
    very_small = 0.0000000001
    very_large = 100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.0
    inf_positive = 1.0 / 0.0
    nan = 0.0 / 0.0
    print(zero_f, one_f, very_small)

def empty_collections():
    empty_list = []
    empty_dict = {}
    single_set = {1}
    empty_str = ""
    print(empty_list, empty_dict, single_set)
    print(empty_str, empty_str.len())

def none_boundaries():
    none_val = None
    some_zero = 0
    some_none = None
    print(none_val, some_zero, some_none)

def literal_boundaries():
    hex_max = 9223372036854775807
    oct_min = 0
    bin_max = 255
    sci_large = 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
    sci_small = 99000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.0
    print(hex_max, oct_min, bin_max)
    print(sci_large, sci_small)

def string_boundaries():
    empty = ""
    single = "x"
    unicode = "你好世界"
    escaped = "tab:\there"
    raw = "\\n\\t\\0"
    multi = "line1\nline2\nline3"
    f_empty = f""
    f_nested = f"x={1 + 2}"
    print(empty, single, unicode)
    print(escaped, raw)
    print(multi, f_empty, f_nested)

def bool_boundaries():
    t = True
    f = False
    and_tt = True and True
    and_tf = True and False
    and_ff = False and False
    or_tt = True or True
    or_tf = True or False
    not_t = not True
    not_f = not False
    triple_not = not not not True
    print(and_tt, and_tf, and_ff)
    print(or_tt, or_tf)
    print(not_t, not_f, triple_not)

def operator_boundaries():
    shift_max = 1 << 62
    shift_zero = 1 >> 1
    pow_zero = 0 ** 0
    pow_one = 999 ** 0
    neg_max = -9223372036854775807
    mod_by_one = 100 % 1
    div_neg = -10 // 3
    print(shift_max, shift_zero)
    print(pow_zero, pow_one)
    print(neg_max, mod_by_one, div_neg)

def collection_boundaries():
    single = [42]
    access_first = single[0]
    out_of_range = single.len()
    empty_check = 1 in []
    single_check = 42 in single
    not_in_check = 99 not in single
    print(access_first, out_of_range)
    print(empty_check, single_check, not_in_check)

def main():
    print("=== edge-values-boundary ===")
    int_boundaries()
    f64_boundaries()
    empty_collections()
    none_boundaries()
    literal_boundaries()
    string_boundaries()
    bool_boundaries()
    operator_boundaries()
    collection_boundaries()
    print("edge-values-boundary done")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage\\edge-values-boundary.lz"  # const: str
__package__ = "boundary-coverage"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
