# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["MagicBox", "keyword_downgrade", "add", "underscore_semantics", "special_literals", "identifiers_with_special_chars", "comment_boundaries", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class MagicBox:
    cdef public Py_ssize_t value
    def __init__(self, Py_ssize_t value):
        self.value = value
    def __init__(self, Py_ssize_t value):
        self.value = value
    def __str__(self) -> str:    
        return f"MagicBox({self.value})"
    def __add__(self, MagicBox other) -> MagicBox:    
        return MagicBox(value = self.value + other.value)
    def __eq__(self, MagicBox other) -> bint:    
        return self.value == other.value
    def __getitem__(self, Py_ssize_t index) -> Py_ssize_t:    
        return (self.value if index == 0 else LZError("bad_index"))
    def __len__(self) -> Py_ssize_t:    
        return 1

def keyword_downgrade():
    Ok = 100
    Some = 200
    None_ = 300
    Err = 400
    print(Ok + Some + None + Err)

def add(Py_ssize_t a, Py_ssize_t b) -> Py_ssize_t:
    return a + b

def underscore_semantics():
    _ = print("side_effect")  # mut
    add5 = lambda __p0: add(__p0, 5)
    print(add5(10))
    sum3 = lambda __p0, __p1: add(__p0, __p1)
    print(sum3(1, 2))
    __scrut_0 = 42
    if __scrut_0 == 0:
        "zero"
    elif True:
        _ = __scrut_0
        "not_zero"
    else:
        pass
    v = None
    print(v)

def special_literals():
    unit_val = ()
    option_none = None
    option_some = 42
    result_ok = 10
    result_err = LZError("failed")
    print(unit_val, option_none, option_some)
    print(result_ok, result_err)

def identifiers_with_special_chars():
    my_var_123 = 42
    _hidden = "secret"
    camelCase = 10
    snake_case = 20
    print(my_var_123, _hidden, camelCase, snake_case)

def comment_boundaries():
    x = 1
    y = 2
    z = 3
    w = 4
    print(x, y, z, w)

def main():
    print("=== edge-keyword-identifier ===")
    keyword_downgrade()
    underscore_semantics()
    box1 = MagicBox(value = 10)
    box2 = MagicBox(value = 20)
    box3 = box1.__add__(box2)
    print(box3)
    print(box1.__eq__(box2))
    print(box1.__eq__(MagicBox(value = 10)))
    print(box1[0])
    print(box1.__len__())
    special_literals()
    identifiers_with_special_chars()
    comment_boundaries()
    print("edge-keyword-identifier done")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage\\edge-keyword-identifier.lz"  # const: str
__package__ = "boundary-coverage"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
