# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["deep_arithmetic", "deep_logical", "deep_mixed", "add_one", "mul_two", "sub_three", "deep_call_chain", "deep_ternary", "deep_method_chain", "deep_pipe", "deep_comprehension", "deep_match_expr", "deep_if_expr", "deep_mixed_compare", "deep_fstring", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

def deep_arithmetic(Py_ssize_t a, Py_ssize_t b, Py_ssize_t c, Py_ssize_t d, Py_ssize_t e) -> Py_ssize_t:
    return ((a + b) * (c - d)) // ((e + a) % (b + 1)) + ((a ** 2) - (b ** 2))

def deep_logical(Py_ssize_t a, Py_ssize_t b, Py_ssize_t c, Py_ssize_t d) -> bint:
    return (a > 0 and b > 0) or (c < 0 and d < 0) and not (a == b) or (c != d)

def deep_mixed(Py_ssize_t a, Py_ssize_t b, Py_ssize_t c) -> Py_ssize_t:
    return ((a & b) | (c << 2)) ^ ((a >> 1) & (b | c)) + (a * b - c)

def add_one(Py_ssize_t x) -> Py_ssize_t:
    return x + 1

def mul_two(Py_ssize_t x) -> Py_ssize_t:
    return x * 2

def sub_three(Py_ssize_t x) -> Py_ssize_t:
    return x - 3

def deep_call_chain(Py_ssize_t x) -> Py_ssize_t:
    return add_one(mul_two(sub_three(add_one(mul_two(x)))))

def deep_ternary(Py_ssize_t a, Py_ssize_t b, Py_ssize_t c, Py_ssize_t d) -> str:
    return ("abcd_pos" if a > 0 and b > 0 and c > 0 and d > 0 else ("abc_pos" if a > 0 and b > 0 and c > 0 else ("ab_pos" if a > 0 and b > 0 else ("a_pos" if a > 0 else "all_nonpos"))))

def deep_method_chain(list xs) -> Py_ssize_t:
    return xs.iter().filter(lambda x: x > 0).map(lambda x: x * 2).take(3).sum()

def deep_pipe(Py_ssize_t x) -> Py_ssize_t:
    return mul_two(add_one(sub_three(mul_two(add_one(x)))))

def deep_comprehension(Py_ssize_t limit) -> list:
    return [(lambda x: [(lambda y: x * y)(__cv) for __cv in (range(0, limit)) if (lambda y: x + y < limit)])(__cv) for __cv in (range(0, limit))]

def deep_match_expr(Py_ssize_t a, Py_ssize_t b) -> Py_ssize_t:
    __scrut_0 = a
    if __scrut_0 == 0:
        __scrut_1 = b
        if __scrut_1 == 0:
            return 0
        elif True:
            _ = __scrut_1
            return 1
        else:
            pass
    elif True:
        _ = __scrut_0
        __scrut_2 = b
        if __scrut_2 == 0:
            return 2
        elif True:
            _ = __scrut_2
            return a + b
        else:
            pass
    else:
        pass

def deep_if_expr(Py_ssize_t a, Py_ssize_t b, Py_ssize_t c) -> Py_ssize_t:
    return a + ((1 if a > 0 else 0)) + ((10 if b > 0 else 0)) + ((100 if c > 0 else 0))

def deep_mixed_compare(Py_ssize_t x, Py_ssize_t y, Py_ssize_t z) -> bint:
    return 0 < x and x < y and y < z and z < 1000 and x + y + z > 0

def deep_fstring(str name, Py_ssize_t age, str city) -> str:
    return f"user: {name}, age: {age}, city: {city}, sum: {age + 10}, check: {age > 18}"

def main():
    print("=== nesting-expressions ===")
    print(deep_arithmetic(5, 3, 10, 2, 1))
    print(deep_logical(1, 2, -3, -4))
    print(deep_mixed(7, 3, 5))
    print(deep_call_chain(5))
    print(deep_ternary(1, 1, 1, 1))
    print(deep_ternary(1, 1, 0, 0))
    print(deep_ternary(0, 0, 0, 0))
    print(deep_method_chain([1, -2, 3, -4, 5, 6]))
    print(deep_pipe(3))
    print(deep_comprehension(3))
    print(deep_match_expr(0, 0))
    print(deep_match_expr(0, 5))
    print(deep_match_expr(3, 7))
    print(deep_if_expr(1, 2, 3))
    print(deep_if_expr(-1, 0, -1))
    print(deep_mixed_compare(1, 50, 999))
    print(deep_mixed_compare(10, 5, 20))
    print(deep_fstring("Alice", 25, "NYC"))
    print("nesting-expressions done")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage\\nesting-expressions.lz"  # const: str
__package__ = "boundary-coverage"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
