# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["triple_nested_closure", "make_adder", "make_multiplier", "compose", "capture_multilevel", "sum4", "partial_nested", "closure_collection", "closure_with_match", "closure_with_ifexpr", "factory_chain", "complex_closure_pipe", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

def triple_nested_closure():
    outer = lambda a: (middle)
    print(outer(1)(2)(3))

def make_adder(Py_ssize_t n) -> object:
    return lambda x: x + n

def make_multiplier(Py_ssize_t factor) -> object:
    return lambda x: x * factor

def compose(object f, object g) -> object:
    return lambda x: f(g(x))

def capture_multilevel(Py_ssize_t base) -> object:
    a = base * 2
    b = base * 3
    return lambda x: a + b + x + base

def sum4(Py_ssize_t a, Py_ssize_t b, Py_ssize_t c, Py_ssize_t d) -> Py_ssize_t:
    return a + b + c + d

def partial_nested():
    f1 = lambda __p0, __p1: sum4(__p0, 10, __p1, 20)
    f2 = lambda __p0: f1(__p0, 30)
    print(f2(1))

def closure_collection():
    ops = [lambda x: x + 1, lambda x: x * 2, lambda x: x ** 2]
    base = 5
    for op in ops:
        print(op(base))

def closure_with_match(Py_ssize_t threshold):
    classify = lambda x: (None)
    print(classify(5))
    print(classify(10))
    print(classify(20))

def closure_with_ifexpr():
    conditional = lambda x, y: ((x + y if x > 0 else x - y))
    print(conditional(5, 3))
    print(conditional(-2, 3))

def factory_chain(Py_ssize_t x) -> object:
    return lambda a: (lambda b: (x + a + b))

def complex_closure_pipe(list data, Py_ssize_t threshold) -> list:
    above = lambda x: x > threshold
    double = lambda x: x * 2
    return [(lambda x: double(x))(__cv) for __cv in (data) if (lambda x: above(x))]

def main():
    print("=== nesting-closure-lambda ===")
    triple_nested_closure()
    add5 = make_adder(5)
    mul3 = make_multiplier(3)
    print(add5(10))
    print(mul3(10))
    composed = compose(add5, mul3)  # mut
    print(composed(4))
    f = capture_multilevel(10)
    print(f(1))
    partial_nested()
    closure_collection()
    closure_with_match(10)
    closure_with_ifexpr()
    chain = factory_chain(1)(2)
    print(chain(3))
    print(chain(10))
    print(complex_closure_pipe([1, 5, 10, 15, 20], 8))
    print("nesting-closure-lambda done")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage\\nesting-closure-lambda.lz"  # const: str
__package__ = "boundary-coverage"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\boundary-coverage"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
