# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Person", "adult", "age_group", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "describe_age", "stats", "double"]

cdef class Person:
    cdef public str name
    cdef public Py_ssize_t age
    def __init__(self, str name, Py_ssize_t age):
        self.name = name
        self.age = age

def adult(Person p) -> bint:
    return p.age >= 18

def age_group(Person p) -> str:
    return ("child" if p.age < 13 else ("teen" if p.age < 20 else "adult"))

def main():
    people = [Person(name = "A", age = 10), Person(name = "B", age = 25), Person(name = "C", age = 17), Person(name = "D", age = 30)]
    adult_count = 0  # mut
    adult_names = []  # mut
    for p in people:
        if adult(p):
            adult_count = adult_count + 1
            adult_names.push(p.name)
    assert adult_count == 2
    assert adult_names == ["B", "D"]
    None
    assert describe_age(Person(name = "A", age = 10)) == "A is young"
    assert describe_age(Person(name = "B", age = 25)) == "B is grown"
    assert describe_age(Person(name = "C", age = 17)) == "C is teen"
    grid_sums = []  # mut
    for i in range(1, 4):
        row_sum = 0  # mut
        for j in range(1, 4):
            row_sum = row_sum + i * j
        grid_sums.push(row_sum)
    assert grid_sums == [6, 12, 18]
    None
    __destruct_sum_count = stats([1, 2, 3, 4])
    sum = __destruct_sum_count[0]
    count = __destruct_sum_count[1]
    assert sum == 10
    assert count == 4
    shout = ""  # mut
    for ch in "lz":
        shout = shout + str(ch).to_upper()
    assert shout == "LZ"
    prices = {"a": 10, "b": 20}
    total_price = 0  # mut
    for k in ["a", "b"]:
        total_price = total_price + prices[k]
    assert total_price == 30
    labels = []  # mut
    for i in range(1, 5):
        if i % 2 == 0:
            label = ("big-even" if i > 2 else "small-even")
            labels.push(label)
    assert labels == ["small-even", "big-even"]
    None
    doubled = []  # mut
    for v in [1, 2, 3]:
        doubled.push(double(v))
    assert doubled == [2, 4, 6]
    print("R18 combined OK")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\01_basics\\combined.lz"  # const: str
__package__ = "01_basics"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\01_basics"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def describe_age(Person p) -> str:
    __scrut_0 = age_group(p)
    if __scrut_0 == "child":
        return p.name + " is young"
    elif __scrut_0 == "teen":
        return p.name + " is teen"
    elif True:
        _ = __scrut_0
        return p.name + " is grown"
    else:
        pass

def stats(list xs) -> tuple:
    total = 0  # mut
    cnt = 0  # mut
    for x in xs:
        total = total + x
        cnt = cnt + 1
    return (total, cnt)

def double(Py_ssize_t x) -> Py_ssize_t:
    return x * 2

