# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef void main():
    r = 0
    ((begin
    # Let { name: "r", ty: Int, value: Expr { kind: Lit(Int(1)), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if True else None)
    assert_eq!(r, 1)
    r = 0
    ((begin
    # Let { name: "r", ty: Int, value: Expr { kind: Lit(Int(1)), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if False else (begin
    # Let { name: "r", ty: Int, value: Expr { kind: Lit(Int(2)), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

))
    assert_eq!(r, 2)
    tag = ""
    x = 7
    ((begin
    # Let { name: "tag", ty: Str, value: Expr { kind: Lit(Str("neg")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if x < 0 else ((begin
    # Let { name: "tag", ty: Str, value: Expr { kind: Lit(Str("zero")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if x == 0 else ((begin
    # Let { name: "tag", ty: Str, value: Expr { kind: Lit(Str("small")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if x < 10 else (begin
    # Let { name: "tag", ty: Str, value: Expr { kind: Lit(Str("big")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

))))
    assert_eq!(tag, "small")
    tag = ""
    y = -3
    ((begin
    # Let { name: "tag", ty: Str, value: Expr { kind: Lit(Str("neg")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if y < 0 else ((begin
    # Let { name: "tag", ty: Str, value: Expr { kind: Lit(Str("zero")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if y == 0 else (begin
    # Let { name: "tag", ty: Str, value: Expr { kind: Lit(Str("pos")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

)))
    assert_eq!(tag, "neg")
    tag = ""
    z = 100
    ((begin
    # Let { name: "tag", ty: Str, value: Expr { kind: Lit(Str("neg")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if z < 0 else ((begin
    # Let { name: "tag", ty: Str, value: Expr { kind: Lit(Str("zero")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if z == 0 else ((begin
    # Let { name: "tag", ty: Str, value: Expr { kind: Lit(Str("small")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if z < 10 else (begin
    # Let { name: "tag", ty: Str, value: Expr { kind: Lit(Str("big")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

))))
    assert_eq!(tag, "big")
    a = 5
    sign = ("positive" if a > 0 else "non-positive")
    assert_eq!(sign, "positive")
    b = -5
    sign2 = ("positive" if b > 0 else "non-positive")
    assert_eq!(sign2, "non-positive")
    max_val = (10 if 10 > 20 else 20)
    assert_eq!(max_val, 20)
    min_val = (10 if 10 < 20 else 20)
    assert_eq!(min_val, 10)
    depth = 0
    n = 15
    (((begin
    # Let { name: "depth", ty: Int, value: Expr { kind: Lit(Int(2)), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if n > 10 else (begin
    # Let { name: "depth", ty: Int, value: Expr { kind: Lit(Int(1)), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

)) if n > 0 else (begin
    # Let { name: "depth", ty: Int, value: Expr { kind: UnOp { op: Neg, operand: Expr { kind: Lit(Int(1)), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }, ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

))
    assert_eq!(depth, 2)
    depth = 0
    m = 5
    (((begin
    # Let { name: "depth", ty: Int, value: Expr { kind: Lit(Int(2)), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if m > 10 else (begin
    # Let { name: "depth", ty: Int, value: Expr { kind: Lit(Int(1)), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

)) if m > 0 else (begin
    # Let { name: "depth", ty: Int, value: Expr { kind: UnOp { op: Neg, operand: Expr { kind: Lit(Int(1)), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }, ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

))
    assert_eq!(depth, 1)
    score = ""
    marks = 75
    ((begin
    # Let { name: "score", ty: Str, value: Expr { kind: Lit(Str("A")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if marks >= 90 else ((begin
    # Let { name: "score", ty: Str, value: Expr { kind: Lit(Str("B")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if marks >= 75 else ((begin
    # Let { name: "score", ty: Str, value: Expr { kind: Lit(Str("C")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if marks >= 60 else (begin
    # Let { name: "score", ty: Str, value: Expr { kind: Lit(Str("F")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

))))
    assert_eq!(score, "B")
    is_leap = True
    ((begin
    # Let { name: "score", ty: Str, value: Expr { kind: Lit(Str("B+")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if (marks > 50) and is_leap else None)
    assert_eq!(score, "B+")
    visible = "init"
    cond = 3 < 4
    ((begin
    # Let { name: "visible", ty: Str, value: Expr { kind: Lit(Str("changed")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }
    # Let { name: "inner", ty: Int, value: Expr { kind: Lit(Int(99)), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }
    # ExprStmt { expr: Expr { kind: Call { callee: Expr { kind: Var("assert_eq!"), ty: Any, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, args: [Expr { kind: Var("inner"), ty: Any, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, Expr { kind: Lit(Int(99)), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }], type_args: [] }, ty: Unit, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }

) if cond else None)
    assert_eq!(visible, "changed")
    p = 3
    nested_expr = ((("big-positive" if p > 2 else "small-positive")) if p > 0 else "negative")
    assert_eq!(nested_expr, "big-positive")
    skipped = 0
    ((begin
    # Let { name: "skipped", ty: Int, value: Expr { kind: Lit(Int(1)), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if 1 > 2 else None)
    assert_eq!(skipped, 0)
    print("R3 control OK")

str __name__ = "main"
str __file__ = "DEMO/01_basics/control_flow.lz"
str __package__ = "01_basics"
str __path__ = "DEMO/01_basics"
str __doc__ = ""
bint __is_macro__ = False
