# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef void main():
    assert_eq!(42, 42)
    assert_eq!(31, 31)
    assert_eq!(15, 15)
    assert_eq!(10, 10)
    assert_eq!(1000000, 1000000)
    assert_eq!(3.14, 3.14)
    assert_eq!(2500, 2500)
    assert_eq!(7 + 3, 10)
    assert_eq!(7 - 3, 4)
    assert_eq!(7 * 3, 21)
    assert_eq!(7 / 2, 3)
    assert_eq!(7 / 2, 3.5)
    assert_eq!(7 % 3, 1)
    assert_eq!(2 ** 10, 1024)
    assert_eq!(-5 + 3, -2)
    assert_eq!((2 + 3) * 4, 20)
    assert_eq!(2 + 3 * 4, 14)
    assert_eq!(3 + 0.5, 3.5)
    assert_eq!(2 * 1.5, 3)
    assert!(1 < 2)
    assert!(2 <= 2)
    assert!(3 > 2)
    assert!(3 >= 3)
    assert_eq!(4, 4)
    assert!(4 != 5)
    assert!(0.1 + 0.2 > 0.3)
    assert_eq!("abc", "abc")
    assert!("abc" != "abd")
    assert!(True != False)
    assert!(True and True)
    assert!(not False)
    assert!(True or False)
    assert!((1 < 2) and (2 < 3))
    assert!((1 > 2) or (2 > 1))
    assert!(not (1 > 2))
    sc1 = False and (1 / 0 == 0)
    assert_eq!(sc1, False)
    sc2 = True or (1 / 0 == 0)
    assert_eq!(sc2, True)
    assert_eq!("hello", "hello")
    assert_eq!("single", "single")
    assert!("tab	here" != "tabhere")
    assert!("newline
" != "newline")
    assert_eq!("", "")
    assert_eq!("a" + "b", "ab")
    assert_eq!(((1 + 2) * (3 + 4)) - (10 / 2), 16)
    assert_eq!((2 ** 3) + (4 % 3) + (6 / 2), 12)
    assert!((5 > 3) and ((2 < 4) or (1 == 2)))
    big = 9223372036854775807
    print(big)
    print("R1 literals OK")

str __name__ = "main"
str __file__ = "DEMO/01_basics/expr_literals.lz"
str __package__ = "01_basics"
str __path__ = "DEMO/01_basics"
str __doc__ = ""
bint __is_macro__ = False
