# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["add", "sub", "greet", "no_ret", "default_params", "multi_ret", "fib", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "inner", "square"]

def add(Py_ssize_t a, Py_ssize_t b) -> Py_ssize_t:
    return a + b

def sub(Py_ssize_t a, Py_ssize_t b) -> Py_ssize_t:
    return a - b

def greet(str name) -> str:
    return "Hello, " + name

def no_ret(Py_ssize_t x) -> Py_ssize_t:
    return x * 2

def default_params(Py_ssize_t a, Py_ssize_t b = 10) -> Py_ssize_t:
    return a + b

def multi_ret(Py_ssize_t x) -> tuple:
    return (x * 2, x * 3)

def fib(Py_ssize_t n) -> Py_ssize_t:
    if n <= 1:
        return n
    return fib(n - 1) + fib(n - 2)

def main():
    assert add(3, 4) == 7
    assert sub(10, 4) == 6
    assert greet("LZ") == "Hello, LZ"
    assert sub(20, 5) == 15
    assert default_params(1, 2) == 3
    assert default_params(1) == 11
    __destruct_d_t = multi_ret(5)
    d = __destruct_d_t[0]
    t = __destruct_d_t[1]
    assert d == 10
    assert t == 15
    assert fib(0) == 0
    assert fib(1) == 1
    assert fib(5) == 5
    assert fib(10) == 55
    no_ret(7)
    None
    assert inner(3) == 300
    fn_ref = add
    assert fn_ref(10, 20) == 30
    assert add(fib(5), sub(20, 5)) == 20
    assert greet(str(sub(5, 0))) == "Hello, 5"
    assert add(add(1, 2), add(3, 4)) == 10
    None
    assert square(6) == 36
    print("R6 functions OK")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\01_basics\\functions.lz"  # const: str
__package__ = "01_basics"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\01_basics"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def inner(Py_ssize_t x) -> Py_ssize_t:
    return x * 100

def square(Py_ssize_t n) -> Py_ssize_t:
    return n * n

