# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["MyStruct", "my_function", "underscore_demo", "compute", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "my_var", "x1", "instance", "_private_val", "z9", "café", "名称", "MyType", "accepts", "handler"]

cdef class MyStruct:
    cdef public Py_ssize_t data
    def __init__(self, Py_ssize_t data):
        self.data = data
    def __str__(self) -> str:    
        return "MyStruct"
    def __add__(self, MyStruct other) -> MyStruct:    
        return MyStruct(data = self.data + other.data)

def my_function(Py_ssize_t a, Py_ssize_t b) -> Py_ssize_t:
    return a + b

def underscore_demo():
    __scrut_0 = 5
    if __scrut_0 == 0:
        "zero"
    elif True:
        _ = __scrut_0
        "other"
    else:
        pass
    desc = None
    __destruct_a___c = (1, 2, 3)
    a = __destruct_a___c[0]
    c = __destruct_a___c[2]
    __scrut_1 = 42
    if __scrut_1 is not None:
        _ = __scrut_1
        _ = compute()
        None
        None
        handler(100)
        pass
    elif True:
        print("no value")
    else:
        pass

def compute() -> Py_ssize_t:
    return 42

def main():
    print(my_var, x1, instance)
    print(café, 名称)
    s1 = MyStruct(data = 100)
    s2 = MyStruct(data = 200)
    print(str(s1))
    s3 = s1.__add__(s2)
    print(str(s3))
    underscore_demo()
    print("identifiers done")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\01_basics\\identifiers.lz"  # const: str
__package__ = "01_basics"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\01_basics"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
my_var = 10  # const: Py_ssize_t
x1 = 20  # const: Py_ssize_t
instance = 30  # const: object
_private_val = 40  # const: Py_ssize_t
z9 = 50  # const: Py_ssize_t
café = "nice"  # const: str
名称 = "中文名"  # const: str
# type MyType = Py_ssize_t
ctypedef Py_ssize_t MyType
def accepts(Py_ssize_t a, Py_ssize_t b, Py_ssize_t c) -> Py_ssize_t:
    return a + b + c

def handler(Py_ssize_t _):
    print("called")

