# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

def main():
    sum = 0  # mut
    for i in range(0, 5):
        sum = sum + i
    assert sum == 10
    total = 0  # mut
    for v in [1, 2, 3, 4]:
        total = total + v
    assert total == 10
    chars = 0  # mut
    for c in "abcd":
        chars = chars + 1
    assert chars == 4
    evens = 0  # mut
    for i in range(0, 6):
        if not (i % 2 == 0): continue
        evens = evens + i
    assert evens == 6
    n = 10  # mut
    steps = 0  # mut
    while n > 0:
        n = n - 3  # mut
        steps = steps + 1  # mut
    assert steps == 4
    v = 1  # mut
    count = 0  # mut
    while v < 100:
        v = v * 2  # mut
        count = count + 1  # mut
    assert count == 7
    found = -1  # mut
    for i in range(0, 10):
        if i == 4:
            found = i
            break
    assert found == 4
    odd_sum = 0  # mut
    for i in range(0, 6):
        if i % 2 == 0:
            continue
        odd_sum = odd_sum + i
    assert odd_sum == 9
    first_match = -1  # mut
    for i in range(0, 100):
        if i * i >= 50:
            first_match = i
            break
    assert first_match == 8
    w = 0  # mut
    wsum = 0  # mut
    while True:
        w = w + 1  # mut
        if w == 2:
            continue
        if w >= 5:
            break
        wsum = wsum + w  # mut
    assert wsum == 8
    ran_else = False  # mut
    for i in range(0, 3):
        pass
    else:
        ran_else = True  # mut
    assert ran_else == True
    products = []  # mut
    for i in range(1, 4):
        for j in range(1, 4):
            products.push(i * j)
    assert products == [1, 2, 3, 2, 4, 6, 3, 6, 9]
    pairs = []  # mut
    for i in range(1, 4):
        for j in range(1, 4):
            if j >= i:
                break
            pairs.push(i * 10 + j)
    assert pairs == [21, 31, 32]
    after = 0  # mut
    for k in range(0, 3):
        after = after + 1
    assert after == 3
    empty_sum = 0  # mut
    for e in range(0, 0):
        empty_sum = empty_sum + 1
    assert empty_sum == 0
    for e in []:
        empty_sum = empty_sum + 1
    assert empty_sum == 0
    print("R4 loops OK")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\01_basics\\loops.lz"  # const: str
__package__ = "01_basics"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\01_basics"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
