# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef void main():
    sum = 0
    for i in Range(start = 0, end = 5):    
        sum = sum + i
    assert_eq!(sum, 10)
    total = 0
    for v in [1, 2, 3, 4]:    
        total = total + v
    assert_eq!(total, 10)
    chars = 0
    for c in "abcd":    
        chars = chars + 1
    assert_eq!(chars, 4)
    evens = 0
    for i in Range(start = 0, end = 6):    
        evens = evens + i
    assert_eq!(evens, 6)
    n = 10
    steps = 0
    while n > 0:    
        n = n - 3
        steps = steps + 1
    assert_eq!(steps, 4)
    v = 1
    count = 0
    while v < 100:    
        v = v * 2
        count = count + 1
    assert_eq!(count, 7)
    found = -1
    for i in Range(start = 0, end = 10):    
        ((begin
    # Assign { target: Expr { kind: Var("found"), ty: Any, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, value: Expr { kind: Var("i"), ty: Any, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }
    # Break

) if i == 4 else None)
    assert_eq!(found, 4)
    odd_sum = 0
    for i in Range(start = 0, end = 6):    
        ((begin
    # Continue

) if i % 2 == 0 else None)
        odd_sum = odd_sum + i
    assert_eq!(odd_sum, 9)
    first_match = -1
    for i in Range(start = 0, end = 100):    
        ((begin
    # Assign { target: Expr { kind: Var("first_match"), ty: Any, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, value: Expr { kind: Var("i"), ty: Any, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }
    # Break

) if i * i >= 50 else None)
    assert_eq!(first_match, 8)
    w = 0
    wsum = 0
    while True:    
        w = w + 1
        ((begin
    # Continue

) if w == 2 else None)
        ((begin
    # Break

) if w >= 5 else None)
        wsum = wsum + w
    assert_eq!(wsum, 8)
    ran_else = False
    for i in Range(start = 0, end = 3):    
        pass
    assert_eq!(ran_else, True)
    products = []
    for i in Range(start = 1, end = 4):    
        for j in Range(start = 1, end = 4):        
            products.push(i * j)
    assert_eq!(products, [1, 2, 3, 2, 4, 6, 3, 6, 9])
    pairs = []
    for i in Range(start = 1, end = 4):    
        for j in Range(start = 1, end = 4):        
            ((begin
    # Break

) if j >= i else None)
            pairs.push(i * 10 + j)
    assert_eq!(pairs, [21, 31, 32])
    after = 0
    for k in Range(start = 0, end = 3):    
        after = after + 1
    assert_eq!(after, 3)
    empty_sum = 0
    for e in Range(start = 0, end = 0):    
        empty_sum = empty_sum + 1
    assert_eq!(empty_sum, 0)
    for e in []:    
        empty_sum = empty_sum + 1
    assert_eq!(empty_sum, 0)
    print("R4 loops OK")

str __name__ = "main"
str __file__ = "DEMO/01_basics/loops.lz"
str __package__ = "01_basics"
str __path__ = "DEMO/01_basics"
str __doc__ = ""
bint __is_macro__ = False
