# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef void main():
    assert_eq!(42, 42)
    assert_eq!(31, 31)
    assert_eq!(42, 42)
    assert_eq!(15, 15)
    assert_eq!(16, 16)
    assert_eq!(10, 10)
    assert_eq!(3, 3)
    assert_eq!(1000000, 1000000)
    assert_eq!(123, 123)
    assert_eq!(255, 255)
    assert_eq!(10.5, 10.5)
    assert_eq!(3.14, 3.14)
    assert_eq!(0.5, 0.5)
    assert_eq!(2500, 2500)
    assert_eq!(100, 100)
    assert_eq!(150, 150)
    assert!(0.1 + 0.2 > 0.3)
    assert!(0.1 + 0.2 < 0.31)
    assert_eq!(3 + 0.5, 3.5)
    assert_eq!(10 / 4, 2)
    assert_eq!(10 / 4, 2.5)
    assert_eq!(7 % 3, 1)
    assert_eq!("a	b", "a	b")
    assert!("a
b" != "ab")
    assert_eq!("a\"b", "a\"b")
    assert_eq!("a\b", "a\b")
    raw = "a\tb"
    assert_eq!(raw, "a\tb")
    assert_eq!(len(raw), 4)
    multi = "line1
line2"
    assert_eq!(multi, "line1
line2")
    x = 5
    s1 = f"x is {x}"
    assert_eq!(s1, "x is 5")
    name = "LZ"
    s2 = f"hello {name}"
    assert_eq!(s2, "hello \"LZ\"")
    assert_eq!(True, True)
    assert_eq!(False, False)
    assert!(True != False)
    assert!(not False)
    nothing = None
    assert_eq!(nothing, None)
    assert_eq!((16 + 8 + 2), 26)
    assert_eq!((1000 + 2000), 3000)
    assert_eq!((2.5 * 4), 10)
    print("P1 literals OK")

str __name__ = "main"
str __file__ = "DEMO/01_basics/polish_01_literals.lz"
str __package__ = "01_basics"
str __path__ = "DEMO/01_basics"
str __doc__ = ""
bint __is_macro__ = False
