# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["fetch_value", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "plain"]

cdef Py_ssize_t fetch_value(Py_ssize_t x):
    x * 2

cdef void main():
    fut = fetch_value(21)
    val = fut.await()
    assert_eq!(val, 42)
    f1 = fetch_value(1)
    f2 = fetch_value(2)
    r1 = f1.await()
    r2 = f2.await()
    assert_eq!(r1, 2)
    assert_eq!(r2, 4)
    None
    assert_eq!(plain(1), 101)
    total = 0
    for i in Range(start = 0, end = 5):    
        total = total + i
    assert_eq!(total, 10)
    print("P23 async OK")

str __name__ = "main"
str __file__ = "DEMO/01_basics/polish_23_async.lz"
str __package__ = "01_basics"
str __path__ = "DEMO/01_basics"
str __doc__ = ""
bint __is_macro__ = False
cdef Py_ssize_t plain(Py_ssize_t x):
    x + 100

