# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef void main():
    total = 0
    for i in Range(start = 0, end = 5):    
        total = total + i
    assert_eq!(total, 10)
    x = 1
    ((begin
    # Let { name: "x", ty: Int, value: Expr { kind: Lit(Int(2)), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: false, is_ref: false }
    # ExprStmt { expr: Expr { kind: Call { callee: Expr { kind: Var("assert_eq!"), ty: Any, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, args: [Expr { kind: Var("x"), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, Expr { kind: Lit(Int(2)), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }], type_args: [] }, ty: Unit, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }

) if True else None)
    assert_eq!(x, 1)
    print("P17 blocks OK")

str __name__ = "main"
str __file__ = "DEMO/01_basics/polish_17_blocks.lz"
str __package__ = "01_basics"
str __path__ = "DEMO/01_basics"
str __doc__ = ""
bint __is_macro__ = False
