# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "vowel", "fizzbuzz", "classify_point", "head_tail", "abs_val", "day_type", "combo", "age_group"]

def main():
    None
    assert vowel("a")
    assert vowel("e")
    assert vowel("z") == False
    None
    assert fizzbuzz(15) == "FizzBuzz"
    assert fizzbuzz(9) == "Fizz"
    assert fizzbuzz(10) == "Buzz"
    assert fizzbuzz(7) == "7"
    None
    assert classify_point((0, 0)) == "origin"
    assert classify_point((5, 0)) == "on-x"
    assert classify_point((0, 5)) == "on-y"
    assert classify_point((1, 2)) == "quadrant"
    None
    assert head_tail([]) == "empty"
    assert head_tail([1]) == "single"
    assert head_tail([1, 2, 3]) == "has-many"
    None
    assert abs_val(5) == 5
    assert abs_val(-5) == 5
    None
    assert day_type("sat") == "weekend"
    assert day_type("mon") == "weekday"
    None
    assert combo(0, 5) == "zero-a"
    assert combo(5, 0) == "zero-b"
    assert combo(5, 5) == "both-nonzero"
    None
    assert age_group(-1) == "invalid"
    assert age_group(12) == "child"
    assert age_group(19) == "teen"
    assert age_group(64) == "adult"
    assert age_group(65) == "senior"
    print("P5 match OK")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\01_basics\\polish_05_match.lz"  # const: str
__package__ = "01_basics"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\01_basics"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def vowel(str ch) -> bint:
    __scrut_0 = ch
    if __scrut_0 == "a":
        return True
    elif __scrut_0 == "e":
        return True
    elif __scrut_0 == "i":
        return True
    elif __scrut_0 == "o":
        return True
    elif __scrut_0 == "u":
        return True
    elif True:
        _ = __scrut_0
        return False
    else:
        pass

def fizzbuzz(Py_ssize_t n) -> str:
    __scrut_1 = n
    if (True) and (__scrut_1 % 15 == 0):
        x = __scrut_1
        return "FizzBuzz"
    elif (True) and (__scrut_1 % 3 == 0):
        x = __scrut_1
        return "Fizz"
    elif (True) and (__scrut_1 % 5 == 0):
        x = __scrut_1
        return "Buzz"
    elif True:
        _ = __scrut_1
        return str(n)
    else:
        pass

def classify_point(tuple pt) -> str:
    __scrut_2 = pt
    if isinstance(__scrut_2, tuple) and len(__scrut_2) == 2 and __scrut_2[0] == 0 and __scrut_2[1] == 0:
        return "origin"
    elif isinstance(__scrut_2, tuple) and len(__scrut_2) == 2 and __scrut_2[1] == 0:
        x = __scrut_2[0]
        return "on-x"
    elif isinstance(__scrut_2, tuple) and len(__scrut_2) == 2 and __scrut_2[0] == 0:
        y = __scrut_2[1]
        return "on-y"
    elif isinstance(__scrut_2, tuple) and len(__scrut_2) == 2:
        x = __scrut_2[0]
        y = __scrut_2[1]
        return "quadrant"
    else:
        pass

def head_tail(list items) -> str:
    __scrut_3 = items
    if isinstance(__scrut_3, list) and len(__scrut_3) == 0:
        return "empty"
    elif isinstance(__scrut_3, list) and len(__scrut_3) == 1:
        x = __scrut_3[0]
        return "single"
    elif isinstance(__scrut_3, list) and len(__scrut_3) >= 1:
        x = __scrut_3[0]
        return "has-many"
    else:
        pass

def abs_val(Py_ssize_t n) -> Py_ssize_t:
    __scrut_4 = n
    if (True) and (__scrut_4 >= 0):
        x = __scrut_4
        return x
    elif True:
        x = __scrut_4
        return -x
    else:
        pass

def day_type(str day) -> str:
    __scrut_5 = day
    if __scrut_5 == "sat":
        return "weekend"
    elif __scrut_5 == "sun":
        return "weekend"
    elif True:
        _ = __scrut_5
        return "weekday"
    else:
        pass

def combo(Py_ssize_t a, Py_ssize_t b) -> str:
    __scrut_6 = a
    if __scrut_6 == 0:
        return "zero-a"
    elif True:
        _ = __scrut_6
        __scrut_7 = b
        if __scrut_7 == 0:
            return "zero-b"
        elif True:
            _ = __scrut_7
            return "both-nonzero"
        else:
            pass
    else:
        pass

def age_group(Py_ssize_t age) -> str:
    __scrut_8 = age
    if (True) and (__scrut_8 < 0):
        x = __scrut_8
        return "invalid"
    elif (True) and (__scrut_8 < 13):
        x = __scrut_8
        return "child"
    elif (True) and (__scrut_8 < 20):
        x = __scrut_8
        return "teen"
    elif (True) and (__scrut_8 < 65):
        x = __scrut_8
        return "adult"
    elif True:
        _ = __scrut_8
        return "senior"
    else:
        pass

