# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "merge"]

cdef void main():
    config = Dict(_k0 = "db", _v0 = Dict(_k0 = "host", _v0 = "localhost", _k1 = "port", _v1 = "5432"), _k1 = "app", _v1 = Dict(_k0 = "mode", _v0 = "debug"))
    assert_eq!(config["db"]["host"], "localhost")
    assert_eq!(config["db"]["port"], "5432")
    assert_eq!(config["app"]["mode"], "debug")
    settings = Dict(_k0 = "theme", _v0 = Dict(_k0 = "color", _v0 = "dark", _k1 = "size", _v1 = "14"))
    settings["theme"]["color"] = "light"
    assert_eq!(settings["theme"]["color"], "light")
    settings["theme"]["size"] = "16"
    assert_eq!(settings["theme"]["size"], "16")
    settings["extra"] = Dict(_k0 = "lang", _v0 = "LZ")
    assert_eq!(settings["extra"]["lang"], "LZ")
    inventory = Dict(_k0 = "ids", _v0 = [1, 2, 3], _k1 = "codes", _v1 = [4, 5])
    assert_eq!(inventory["ids"][1], 2)
    assert_eq!(inventory["codes"][0], 4)
    assert_eq!(len(inventory["ids"]), 3)
    person = Dict(_k0 = "name", _v0 = "LZ", _k1 = "age", _v1 = "30", _k2 = "city", _v2 = "BJ")
    keys = ["name", "age", "city"]
    found_all = True
    for k in keys:    
        ((begin
    # Assign { target: Expr { kind: Var("found_all"), ty: Bool, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, value: Expr { kind: Lit(Bool(false)), ty: Bool, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }

) if k not in person else None)
    assert_eq!(found_all, True)
    assert_eq!(len(person), 3)
    assert!("name" in person)
    assert!("xyz" not in person)
    None
    m = merge(Dict(_k0 = "a", _v0 = 1, _k1 = "x", _v1 = 2), Dict(_k0 = "x", _v0 = 10, _k1 = "y", _v1 = 20))
    assert_eq!(m["a"], 1)
    assert_eq!(m["x"], 10)
    assert_eq!(m["y"], 20)
    scores = Dict(_k0 = "a", _v0 = 10, _k1 = "b", _v1 = 20, _k2 = "c", _v2 = 30)
    score_total = 0
    for k in ["a", "b", "c"]:    
        score_total = score_total + scores[k]
    assert_eq!(score_total, 60)
    empty = Dict()
    assert_eq!(len(empty), 0)
    assert!("k" not in empty)
    nums = Dict(_k0 = "one", _v0 = 1, _k1 = "two", _v1 = 2, _k2 = "three", _v2 = 3)
    assert_eq!(nums["one"] + nums["two"] + nums["three"], 6)
    db_config = Dict(_k0 = "prod", _v0 = Dict(_k0 = "port", _v0 = 80), _k1 = "dev", _v1 = Dict(_k0 = "port", _v0 = 8080))
    prod_port = 0
    ((begin
    # Let { name: "prod_port", ty: Int, value: Expr { kind: IndexGet { base: Expr { kind: IndexGet { base: Expr { kind: Var("db_config"), ty: Named { path: "Dict", args: [Str, Named { path: "Dict", args: [Str, Int] }] }, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, key: Expr { kind: Lit(Str("prod")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }, ty: Named { path: "Dict", args: [Str, Int] }, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, key: Expr { kind: Lit(Str("port")), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }, ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: true, is_ref: false }

) if "prod" in db_config else None)
    assert_eq!(prod_port, 80)
    assert_eq!(db_config["dev"]["port"], 8080)
    print("P9 dicts OK")

str __name__ = "main"
str __file__ = "DEMO/01_basics/polish_09_dicts.lz"
str __package__ = "01_basics"
str __path__ = "DEMO/01_basics"
str __doc__ = ""
bint __is_macro__ = False
cdef dict merge(dict d1, dict d2):
    out = d1
    for k in ["x", "y"]:    
        ((begin
    # Let { name: "val", ty: Int, value: Expr { kind: IndexGet { base: Expr { kind: Var("d2"), ty: Named { path: "Dict", args: [Str, Int] }, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, key: Expr { kind: Var("k"), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }, ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: false, is_ref: false }
    # Assign { target: Expr { kind: IndexGet { base: Expr { kind: Var("out"), ty: Named { path: "Dict", args: [Str, Int] }, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, key: Expr { kind: Var("k"), ty: Str, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }, ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, value: Expr { kind: Var("val"), ty: Any, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }

) if k in d2 else None)
    return out

