# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Point", "Circle", "Rect", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "translate"]

cdef class Point:
    cdef public Py_ssize_t x
    cdef public Py_ssize_t y
    def __init__(self, Py_ssize_t x, Py_ssize_t y):
        self.x = x
        self.y = y
    def scaled(self, Py_ssize_t k) -> Point:    
        return Point(x = self.x * k, y = self.y * k)
    def shifted(self, Py_ssize_t dx, Py_ssize_t dy) -> Point:    
        return Point(x = self.x + dx, y = self.y + dy)
    def with_x(self, Py_ssize_t new_x) -> Point:    
        self.x = new_x
        return self

cdef class Circle:
    cdef public Point center
    cdef public Py_ssize_t radius
    def __init__(self, Point center, Py_ssize_t radius):
        self.center = center
        self.radius = radius
    def area(self) -> Py_ssize_t:    
        return 3 * self.radius * self.radius
    def describe(self) -> str:    
        return "circle@" + str(self.center.x) + "," + str(self.center.y)

cdef class Rect:
    cdef public Point top_left
    cdef public Py_ssize_t w
    cdef public Py_ssize_t h
    def __init__(self, Point top_left, Py_ssize_t w, Py_ssize_t h):
        self.top_left = top_left
        self.w = w
        self.h = h
    def area(self) -> Py_ssize_t:    
        return self.w * self.h

def main():
    c = Circle(center = Point(x = 1, y = 2), radius = 5)
    assert c.center.x == 1
    assert c.center.y == 2
    assert c.radius == 5
    r = Rect(top_left = Point(x = 0, y = 0), w = 10, h = 4)
    assert r.top_left.x == 0
    assert r.w == 10
    assert r.h == 4
    c2 = Circle(center = Point(x = 0, y = 0), radius = 1)  # mut
    c2.center.x = 7
    c2.radius = 9
    assert c2.center.x == 7
    assert c2.center.y == 0
    assert c2.radius == 9
    None
    None
    p = Point(x = 2, y = 3)
    p2 = p.scaled(10).shifted(1, 1)
    assert p2.x == 21
    assert p2.y == 31
    None
    p3 = Point(x = 0, y = 0).with_x(42)
    assert p3.x == 42
    assert p3.y == 0
    None
    None
    assert c.area() == 75
    assert c.describe() == "circle@1,2"
    shapes = [Circle(center = Point(x = 0, y = 0), radius = 2), Circle(center = Point(x = 1, y = 1), radius = 3)]
    total_area = 0  # mut
    for s in shapes:
        total_area = total_area + s.area()
    assert total_area == 39
    None
    moved = translate(Point(x = 5, y = 5), 10, -2)
    assert moved.x == 15
    assert moved.y == 3
    None
    assert r.area() == 40
    print("P10 structs OK")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\01_basics\\polish_10_structs.lz"  # const: str
__package__ = "01_basics"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\01_basics"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def translate(Point pp, Py_ssize_t dx, Py_ssize_t dy) -> Point:
    return Point(x = pp.x + dx, y = pp.y + dy)

