# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef void main():
    raw = "a\tb\nc"
    assert_eq!(raw, "a\tb\nc")
    assert_eq!(len(raw), 7)
    multi = "line1
line2
line3"
    assert_eq!(multi, "line1
line2
line3")
    s = "  Hello World  "
    assert_eq!(s.trim(), "Hello World")
    assert_eq!(s.trim().to_lower(), "hello world")
    assert_eq!(s.trim().to_upper(), "HELLO WORLD")
    name = "LZ"
    ver = 2
    msg = f"lang-zone v{ver} by {name}"
    assert_eq!(msg, "lang-zone v2 by \"LZ\"")
    parts = ["a", "b", "c"]
    joined = ""
    for p in parts:    
        joined = joined + p
    assert_eq!(joined, "abc")
    assert_eq!(len("hello"), 5)
    assert_eq!("hello"[0], 104)
    assert_eq!("hello"[4], 111)
    assert_eq!("abc", "abc")
    assert!("abc" < "abd")
    assert!("abc" != "ABC")
    greeting = "Hello, " + name + "!"
    assert_eq!(greeting, "Hello, LZ!")
    assert_eq!(greeting.len(), 10)
    print("P28 strings OK")

str __name__ = "main"
str __file__ = "DEMO/01_basics/polish_28_strings.lz"
str __package__ = "01_basics"
str __path__ = "DEMO/01_basics"
str __doc__ = ""
bint __is_macro__ = False
