# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["greet", "pow2", "minmax", "fact", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "fib", "inner", "inner2", "outer", "make_adder", "double", "inc", "dbl", "countdown", "fmt"]

def greet(str name, str prefix = "Hello") -> str:
    return prefix + ", " + name

def pow2(Py_ssize_t n, Py_ssize_t times = 1) -> Py_ssize_t:
    return n ** times

def minmax(list xs) -> tuple:
    return (xs[0], xs[len(xs) - 1])

def fact(Py_ssize_t n) -> Py_ssize_t:
    if n <= 1:
        return 1
    return n * fact(n - 1)

def main():
    assert greet("LZ") == "Hello, LZ"
    assert greet("LZ", "Hi") == "Hi, LZ"
    assert pow2(3) == 3
    assert pow2(2, 10) == 1024
    __destruct_lo_hi = minmax([1, 5, 9])
    lo = __destruct_lo_hi[0]
    hi = __destruct_lo_hi[1]
    assert lo == 1
    assert hi == 9
    assert fact(5) == 120
    None
    assert fib(10) == 55
    None
    assert outer(5) == 25
    None
    add5 = make_adder(5)
    add100 = make_adder(100)
    assert add5(10) == 15
    assert add100(10) == 110
    None
    assert double(21) == 42
    None
    None
    assert dbl(inc(dbl(inc(1)))) == 10
    None
    assert countdown(100) == 100
    None
    assert fmt(1) == "1-0"
    assert fmt(1, "+") == "1+0"
    assert fmt(1, "*", 9) == "1*9"
    print("P6 functions OK")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\01_basics\\polish_06_functions.lz"  # const: str
__package__ = "01_basics"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\01_basics"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def fib(Py_ssize_t n) -> Py_ssize_t:
    if n <= 1:
        return n
    return fib(n - 1) + fib(n - 2)

def inner(Py_ssize_t y) -> Py_ssize_t:
    return y * 2

def inner2(Py_ssize_t z) -> Py_ssize_t:
    return z + 10

def outer(Py_ssize_t x) -> Py_ssize_t:
    None
    None
    return inner(x) + inner2(x)

def make_adder(Py_ssize_t n) -> object:
    return lambda x: x + n

def double(Py_ssize_t x) -> Py_ssize_t:
    return x * 2

def inc(Py_ssize_t x) -> Py_ssize_t:
    return x + 1

def dbl(Py_ssize_t x) -> Py_ssize_t:
    return x * 2

def countdown(Py_ssize_t n) -> Py_ssize_t:
    if n == 0:
        return 0
    return 1 + countdown(n - 1)

def fmt(Py_ssize_t a, str b = "-", Py_ssize_t c = 0) -> str:
    return str(a) + b + str(c)

