# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

def main():
    assert 42 == 42
    assert 31 == 31
    assert 42 == 42
    assert 15 == 15
    assert 16 == 16
    assert 10 == 10
    assert 3 == 3
    assert 1000000 == 1000000
    assert 123 == 123
    assert 255 == 255
    assert 10.5 == 10.5
    assert 3.14 == 3.14
    assert 0.5 == 0.5
    assert 2500.0 == 2500.0
    assert 100.0 == 100.0
    assert 150.0 == 150.0
    assert 0.1 + 0.2 > 0.3
    assert 0.1 + 0.2 < 0.31
    assert 3 + 0.5 == 3.5
    assert 10 // 4 == 2
    assert 10.0 / 4 == 2.5
    assert 7 % 3 == 1
    assert "a\tb" == "a\tb"
    assert "a\nb" != "ab"
    assert "a\"b" == "a\"b"
    assert "a\\b" == "a\\b"
    raw = "a\\tb"
    assert raw == "a\\tb"
    assert len(raw) == 4
    multi = "line1\nline2"
    assert multi == "line1\nline2"
    x = 5
    s1 = f"x is {x}"
    assert s1 == "x is 5"
    name = "LZ"
    s2 = f"hello {name}"
    assert s2 == "hello \"LZ\""
    assert True == True
    assert False == False
    assert True != False
    assert not False
    nothing = None
    assert nothing == None
    assert (16 + 8 + 2) == 26
    assert (1000 + 2000) == 3000
    assert (2.5 * 4) == 10.0
    print("P1 literals OK")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\01_basics\\polish_01_literals.lz"  # const: str
__package__ = "01_basics"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\01_basics"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
