# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Shape", "Result2", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "area", "Wrapper", "describe", "classify", "is_circle"]

class Shape:
    pass

class Point(Shape):
    pass
Point = Point()

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius

class Rect(Shape):
    def __init__(self, w, h):
        self.w = w
        self.h = h

class Triangle(Shape):
    def __init__(self, base, height):
        self.base = base
        self.height = height

class Result2:
    pass

class Success(Result2):
    def __init__(self, value):
        self.value = value

class Failure(Result2):
    def __init__(self, msg):
        self.msg = msg

def main():
    s1 = Point
    s2 = Circle(radius = 5)
    s3 = Rect(w = 3, h = 4)
    s4 = Triangle(base = 6, height = 2)
    None
    assert area(s1) == 0
    assert area(s2) == 75
    assert area(s3) == 12
    assert area(s4) == 6
    None
    w1 = ShapeWrap(Circle(radius = 2))
    w2 = NumWrap(100)
    unwrap_area = lambda w: (None)
    assert unwrap_area(w1) == 12
    assert unwrap_area(w2) == 100
    shapes = [Circle(radius = 1), Rect(w = 2, h = 3)]
    total = 0  # mut
    for sh in shapes:
        total = total + area(sh)
    assert total == 9
    None
    assert describe(Success(50)) == "success-50"
    assert describe(Success(200)) == "big-success"
    assert describe(Failure("err")) == "fail-err"
    None
    assert classify(Circle(radius = 5)) == "big-circle"
    assert classify(Circle(radius = 2)) == "small-circle"
    assert classify(Rect(w = 1, h = 1)) == "other"
    None
    assert is_circle(Circle(radius = 1)) == True
    assert is_circle(Point) == False
    print("P11 enums OK")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\01_basics\\polish_11_enums.lz"  # const: str
__package__ = "01_basics"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\01_basics"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def area(object s) -> Py_ssize_t:
    __scrut_0 = s
    if __scrut_0 is Point:
        return 0
    elif isinstance(__scrut_0, Circle):
        radius = __scrut_0.radius
        return 3 * radius * radius
    elif isinstance(__scrut_0, Rect):
        w = __scrut_0.w
        h = __scrut_0.h
        return w * h
    elif isinstance(__scrut_0, Triangle):
        base = __scrut_0.base
        height = __scrut_0.height
        return base * height // 2
    else:
        pass

class Wrapper:
    pass

class ShapeWrap(Wrapper):
    def __init__(self, s):
        self.s = s

class NumWrap(Wrapper):
    def __init__(self, n):
        self.n = n

def describe(object r) -> str:
    __scrut_1 = r
    if (isinstance(__scrut_1, Success)) and (__scrut_1.value > 100):
        value = __scrut_1.value
        return "big-success"
    elif isinstance(__scrut_1, Success):
        value = __scrut_1.value
        return "success-" + str(value)
    elif isinstance(__scrut_1, Failure):
        msg = __scrut_1.msg
        return "fail-" + msg
    else:
        pass

def classify(object s) -> str:
    __scrut_2 = s
    if isinstance(__scrut_2, Circle):
        radius = __scrut_2.radius
        __scrut_3 = radius
        if (True) and (__scrut_3 > 3):
            r = __scrut_3
            return "big-circle"
        elif True:
            _ = __scrut_3
            return "small-circle"
        else:
            pass
    elif True:
        _ = __scrut_2
        return "other"
    else:
        pass

def is_circle(object s) -> bint:
    __scrut_4 = s
    if isinstance(__scrut_4, Circle):
        radius = __scrut_4.radius
        return True
    elif True:
        _ = __scrut_4
        return False
    else:
        pass

