# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["safe_div", "clamp", "is_valid", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "grade2"]

def safe_div(Py_ssize_t a, Py_ssize_t b) -> Py_ssize_t:
    if b != 0:
        pass
    else:
        raise LZError("division by zero") if not isinstance(("division by zero"), BaseException) else ("division by zero")
    return a // b

def clamp(Py_ssize_t v, Py_ssize_t lo, Py_ssize_t hi) -> Py_ssize_t:
    if v >= lo:
        pass
    else:
        return lo
    if v <= hi:
        pass
    else:
        return hi
    return v

def is_valid(Py_ssize_t x) -> bint:
    if x >= 0:
        pass
    else:
        return False
    if x < 100:
        pass
    else:
        return False
    return True

def main():
    assert clamp(5, 0, 10) == 5
    assert clamp(-3, 0, 10) == 0
    assert clamp(99, 0, 10) == 10
    assert clamp(0, 0, 10) == 0
    assert clamp(10, 0, 10) == 10
    assert is_valid(0) == True
    assert is_valid(50) == True
    assert is_valid(-1) == False
    assert is_valid(100) == False
    assert is_valid(99) == True
    assert safe_div(10, 2) == 5
    assert safe_div(-8, 4) == -2
    assert clamp(7, 0, 10) == 7
    if not clamp(8, 0, 10) == 8:
        print("CHECK failed", file=sys.stderr)
    None
    assert grade2(75) == "pass"
    assert grade2(40) == "fail"
    assert grade2(-5) == "invalid"
    assert grade2(150) == "invalid"
    print("P21 errors OK")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\01_basics\\polish_21_errors.lz"  # const: str
__package__ = "01_basics"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\01_basics"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def grade2(Py_ssize_t score) -> str:
    if score >= 0:
        pass
    else:
        return "invalid"
    if score <= 100:
        pass
    else:
        return "invalid"
    if score >= 60:
        return "pass"
    return "fail"

