# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

def main():
    assert (5 & 3) == 1
    assert (5 | 3) == 7
    assert (5 ^ 3) == 6
    assert (1 << 4) == 16
    assert (16 >> 2) == 4
    assert (1 << 10) == 1024
    assert ((240 | 15)) == 255
    assert ((255 & 15)) == 15
    assert ((1 << 8) | (1 << 2)) == 260
    a = 10  # mut
    a = a + 5
    assert a == 15
    a = a - 3
    assert a == 12
    a = a * 2
    assert a == 24
    a = a // 4
    assert a == 6
    a = a % 4
    assert a == 2
    b = 1  # mut
    b = b << 4
    assert b == 16
    b = b >> 2
    assert b == 4
    assert (True and True) and (False or True)
    assert not (True and False)
    assert (5 > 3) and (2 < 4)
    assert 7 // 2 == 3
    assert 7.0 / 2 == 3.5
    assert -7 % 3 == -1 or 7 % 3 == 1
    print("P26 bitwise OK")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\01_basics\\polish_26_bitwise.lz"  # const: str
__package__ = "01_basics"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\01_basics"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
