# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "grade", "classify2", "pick"]

def main():
    None
    assert grade(95) == "A"
    assert grade(85) == "B"
    assert grade(75) == "C"
    assert grade(65) == "D"
    assert grade(50) == "F"
    assert grade(90) == "A"
    assert grade(89) == "B"
    assert grade(60) == "D"
    assert grade(59) == "F"
    a = 10
    bigger = ("big" if a > 5 else "small")
    assert bigger == "big"
    smaller = ("big" if a < 5 else "small")
    assert smaller == "small"
    x = 7
    desc = ((("pos-big" if x > 5 else "pos-small")) if x > 0 else "non-pos")
    assert desc == "pos-big"
    y = 3
    desc2 = ((("pos-big" if y > 5 else "pos-small")) if y > 0 else "non-pos")
    assert desc2 == "pos-small"
    z = -1
    desc3 = ((("pos-big" if z > 5 else "pos-small")) if z > 0 else "non-pos")
    assert desc3 == "non-pos"
    level = 0  # mut
    n = 25
    if n > 0:
        if n > 10:
            if n > 20:
                level = 3  # mut
            else:
                level = 2  # mut
        else:
            level = 1  # mut
    else:
        level = -1  # mut
    assert level == 3
    result = ""  # mut
    if True:
        temp = "from-block"
        result = temp  # mut
    assert result == "from-block"
    None
    assert classify2(0) == "zero"
    assert classify2(3) == "three"
    assert classify2(10) == "many"
    None
    combined = pick(("yes" if 1 > 0 else "no"), "-suffix")
    assert combined == "yes-suffix"
    p = 15
    q = 20
    r = 25
    if (p < q) and (q < r):
        assert True
    else:
        assert False
    print("P3 ifelif OK")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\01_basics\\polish_03_ifelif.lz"  # const: str
__package__ = "01_basics"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\01_basics"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def grade(Py_ssize_t score) -> str:
    return ("A" if score >= 90 else ("B" if score >= 80 else ("C" if score >= 70 else ("D" if score >= 60 else "F"))))

def classify2(Py_ssize_t v) -> str:
    return ("zero" if v == 0 else ("one" if v == 1 else ("two" if v == 2 else ("three" if v == 3 else "many"))))

def pick(str a, str b) -> str:
    return a + b

