# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Builder", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class Builder:
    cdef public Py_ssize_t value
    cdef public list history
    def __init__(self, Py_ssize_t value, list history):        self.value = value
        self.history = history

# impl Builder
# Builder.add → 注入到 Builder

cdef void main():
    b = Builder(_KwArg(name = "value", value = 0), _KwArg(name = "history", value = []))
    b2 = b.add(5).add(3).add(10)
    assert_eq!(b2.value, 18)
    assert_eq!(b2.history, [5, 8, 18])
    b3 = Builder(_KwArg(name = "value", value = 100), _KwArg(name = "history", value = []))
    b4 = b3.add(1)
    assert_eq!(b4.value, 101)
    assert_eq!(b4.history, [101])
    total = 0
    for i in Range(start = 0, end = 5):    
        total = total + i
    assert_eq!(total, 10)
    print("P25 self OK")

str __name__ = "main"
str __file__ = "DEMO/01_basics/polish_25_self.lz"
str __package__ = "01_basics"
str __path__ = "DEMO/01_basics"
str __doc__ = ""
bint __is_macro__ = False
