# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["add", "mul", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "CONST_V"]

cdef Py_ssize_t add(Py_ssize_t a, Py_ssize_t b):
    a + b

cdef Py_ssize_t mul(Py_ssize_t a, Py_ssize_t b):
    a * b

str __name__ = "main"
str __file__ = "DEMO/01_basics/polish_27_lib.lz"
str __package__ = "01_basics"
str __path__ = "DEMO/01_basics"
str __doc__ = ""
bint __is_macro__ = False
Py_ssize_t CONST_V = 100
def main(): pass
