# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "apply_twice", "curried_add", "compose", "sum_to_fn", "sort_desc"]

cdef void main():
    add = lambda a: object, b: object: a + b
    assert_eq!(add(1, 2), 3)
    base = 10
    add_base = lambda x: object: x + base
    assert_eq!(add_base(5), 15)
    None
    dbl = lambda x: object: x * 2
    assert_eq!(apply_twice(dbl, 5), 20)
    ops = [lambda x: object: x + 1, lambda x: object: x * 2, lambda x: object: x * x]
    assert_eq!(ops[0](3), 4)
    assert_eq!(ops[1](3), 6)
    assert_eq!(ops[2](3), 9)
    None
    add5 = curried_add(5)
    add100 = curried_add(100)
    assert_eq!(add5(3), 8)
    assert_eq!(add100(3), 103)
    None
    inc = lambda x: object: x + 1
    square = lambda x: object: x * x
    inc_then_square = compose(square, inc)
    assert_eq!(inc_then_square(3), 16)
    square_then_inc = compose(inc, square)
    assert_eq!(square_then_inc(3), 10)
    None
    assert_eq!(sum_to_fn(5), 10)
    a = 2
    b = 3
    c = 4
    combo = lambda x: object: a * x * x + b * x + c
    assert_eq!(combo(1), 9)
    assert_eq!(combo(2), 18)
    assert_eq!((lambda x: object: x + 100)(1), 101)
    None
    sorted = sort_desc([3, 1, 2])
    assert_eq!(sorted, [3, 2, 1])
    print("P7 closures OK")

str __name__ = "main"
str __file__ = "DEMO/01_basics/polish_07_closures.lz"
str __package__ = "01_basics"
str __path__ = "DEMO/01_basics"
str __doc__ = ""
bint __is_macro__ = False
cdef Py_ssize_t apply_twice(object f, Py_ssize_t x):
    f(f(x))

cdef object curried_add(Py_ssize_t a):
    lambda b: object: a + b

cdef object compose(object f, object g):
    lambda x: object: f(g(x))

cdef Py_ssize_t sum_to_fn(Py_ssize_t n):
    total = 0
    for i in Range(start = 0, end = n):    
        total = total + i
    return total

cdef list sort_desc(list xs):
    result = xs
    i = 0
    while i < len(result):    
        j = i + 1
        while j < len(result):        
            ((begin
    # Let { name: "tmp", ty: Int, value: Expr { kind: IndexGet { base: Expr { kind: Var("result"), ty: Named { path: "List", args: [Int] }, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, key: Expr { kind: Var("i"), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }, ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, is_mut: false, is_ref: false }
    # Assign { target: Expr { kind: IndexGet { base: Expr { kind: Var("result"), ty: Named { path: "List", args: [Int] }, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, key: Expr { kind: Var("i"), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }, ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, value: Expr { kind: IndexGet { base: Expr { kind: Var("result"), ty: Named { path: "List", args: [Int] }, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, key: Expr { kind: Var("j"), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }, ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }
    # Assign { target: Expr { kind: IndexGet { base: Expr { kind: Var("result"), ty: Named { path: "List", args: [Int] }, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, key: Expr { kind: Var("j"), ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }, ty: Int, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, value: Expr { kind: Var("tmp"), ty: Any, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }

) if result[j] > result[i] else None)
            j = j + 1
        i = i + 1
    return result

