# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Animal", "Vehicle", "Square2", "Circle2", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class Animal:
    cdef public str n
    cdef public Py_ssize_t s
    def __init__(self, str n, Py_ssize_t s):        self.n = n
        self.s = s

cdef class Vehicle:
    cdef public str model
    cdef public Py_ssize_t wheels
    def __init__(self, str model, Py_ssize_t wheels):        self.model = model
        self.wheels = wheels

cdef class Square2:
    cdef public Py_ssize_t side
    def __init__(self, Py_ssize_t side):        self.side = side

cdef class Circle2:
    cdef public Py_ssize_t radius
    def __init__(self, Py_ssize_t radius):        self.radius = radius

class Named:
    """Trait: Named"""
    def name(self) -> str: ...

class Sized2:
    """Trait: Sized2"""
    def size(self) -> Py_ssize_t: ...

class Area2:
    """Trait: Area2"""
    def area(self) -> Py_ssize_t: ...
    def doubled(self) -> Py_ssize_t: ...

# impl Named for Animal
# Named.name → 注入到 Animal

# impl Sized2 for Animal
# Sized2.size → 注入到 Animal

# impl Named for Vehicle
# Named.name → 注入到 Vehicle

# impl Sized2 for Vehicle
# Sized2.size → 注入到 Vehicle

# impl Area2 for Square2
# Area2.area → 注入到 Square2

# impl Area2 for Circle2
# Area2.area → 注入到 Circle2
# Area2.doubled → 注入到 Circle2

cdef void main():
    dog = Animal(_KwArg(name = "n", value = "Rex"), _KwArg(name = "s", value = 10))
    car = Vehicle(_KwArg(name = "model", value = "Sedan"), _KwArg(name = "wheels", value = 4))
    assert_eq!(dog.name(), "Rex")
    assert_eq!(car.name(), "Sedan")
    assert_eq!(dog.size(), 10)
    assert_eq!(car.size(), 4)
    sq = Square2(_KwArg(name = "side", value = 4))
    assert_eq!(sq.area(), 16)
    assert_eq!(sq.doubled(), 32)
    c2 = Circle2(_KwArg(name = "radius", value = 2))
    assert_eq!(c2.area(), 12)
    assert_eq!(c2.doubled(), 36)
    bird = Animal(_KwArg(name = "n", value = "Tweety"), _KwArg(name = "s", value = 3))
    assert_eq!(bird.name() + str(bird.size()), "Tweety3")
    print("P13 traits OK")

str __name__ = "main"
str __file__ = "DEMO/01_basics/polish_13_traits.lz"
str __package__ = "01_basics"
str __path__ = "DEMO/01_basics"
str __doc__ = ""
bint __is_macro__ = False
