# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Dog", "Circle3", "Square3", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "show_name", "total_area", "area_plus"]

cdef class Dog:
    cdef public str n
    def __init__(self, str n):
        self.n = n
    def name(self) -> str:    
        return self.n

cdef class Circle3:
    cdef public Py_ssize_t radius
    def __init__(self, Py_ssize_t radius):
        self.radius = radius
    def area(self) -> Py_ssize_t:    
        return 3 * self.radius * self.radius

cdef class Square3:
    cdef public Py_ssize_t side
    def __init__(self, Py_ssize_t side):
        self.side = side
    def area(self) -> Py_ssize_t:    
        return self.side * self.side

def main():
    dog = Dog(n = "Rex")
    c = Circle3(radius = 3)
    sq = Square3(side = 4)
    None
    assert show_name(dog) == "Rex"
    None
    assert total_area(c) == 27
    assert total_area(sq) == 16
    None
    assert area_plus(c) == 28
    assert area_plus(sq) == 17
    assert dog.name() == "Rex"
    assert c.area() == 27
    assert sq.area() == 16
    print("P16 duck OK")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\01_basics\\polish_16_duck.lz"  # const: str
__package__ = "01_basics"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\01_basics"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
class HasName:
    """Duck type constraint: HasName"""
    # def name(...) -> str

class HasArea:
    """Duck type constraint: HasArea"""
    # def area(...) -> Py_ssize_t

def show_name(object x) -> str:
    # generic<T>
    return x.name()

def total_area(object x) -> Py_ssize_t:
    # generic<T>
    return x.area()

def area_plus(object x) -> Py_ssize_t:
    # generic<T>
    return x.area() + 1

