# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "safe_div"]

cdef void main():
    empty_list = []
    assert_eq!(len(empty_list), 0)
    empty_dict = Dict()
    assert_eq!(len(empty_dict), 0)
    empty_str = ""
    assert_eq!(len(empty_str), 0)
    sum_empty = 0
    for v in empty_list:    
        sum_empty = sum_empty + 1
    assert_eq!(sum_empty, 0)
    single = [42]
    assert_eq!(len(single), 1)
    assert_eq!(single[0], 42)
    c0 = 0
    for i in Range(start = 0, end = 0):    
        c0 = c0 + 1
    assert_eq!(c0, 0)
    c1 = 0
    for i in Range(start = 0, end = 1):    
        c1 = c1 + 1
    assert_eq!(c1, 1)
    None
    assert_eq!(safe_div(10, 2), 5)
    assert_eq!(safe_div(10, 0), 0)
    big = 9223372036854775807
    assert!(big > 0)
    neg = --9223372036854775808
    assert!(neg < 0)
    assert_eq!(big + 0, big)
    assert_eq!(neg + 0, neg)
    xs = [1, 2, 3]
    assert_eq!(xs[0], 1)
    assert_eq!(xs[len(xs) - 1], 3)
    empty_grid = []
    assert_eq!(len(empty_grid), 0)
    grid_with_empty = [[], []]
    assert_eq!(len(grid_with_empty), 2)
    assert_eq!(len(grid_with_empty[0]), 0)
    assert_eq!("a"[0], 97)
    assert_eq!("ab"[1], 98)
    assert_eq!("a"[0], "a"[0])
    total = 0
    for i in Range(start = 0, end = 1000):    
        total = total + 1
    assert_eq!(total, 1000)
    print("P30 edge OK")

str __name__ = "main"
str __file__ = "DEMO/01_basics/polish_30_edge.lz"
str __package__ = "01_basics"
str __path__ = "DEMO/01_basics"
str __doc__ = ""
bint __is_macro__ = False
cdef Py_ssize_t safe_div(Py_ssize_t a, Py_ssize_t b):
    if b != 0:    
    else:
        return 0
    a / b

