# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef void main():
    print("P20 testing OK")

str __name__ = "main"
str __file__ = "DEMO/01_basics/polish_20_testing.lz"
str __package__ = "01_basics"
str __path__ = "DEMO/01_basics"
str __doc__ = ""
bint __is_macro__ = False
def test_basic_assert():
    assert_eq!(1 + 1, 2)
    assert_eq!(2 * 3, 6)

def test_string_ops():
    assert_eq!("abc" + "def", "abcdef")
    assert_eq!(len("hello"), 5)

def test_list_ops():
    xs = [1, 2, 3]
    assert_eq!(len(xs), 3)
    assert_eq!(xs[0], 1)

