# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Money", "Vec2", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "total_money"]

cdef class Money:
    cdef public Py_ssize_t amount
    def __init__(self, Py_ssize_t amount):
        self.amount = amount
    def __add__(self, Money other) -> Money:    
        return Money(amount = self.amount + other.amount)
    def __eq__(self, Money other) -> bint:    
        return self.amount == other.amount
    def __lt__(self, Money other) -> bint:    
        return self.amount < other.amount

cdef class Vec2:
    cdef public Py_ssize_t x
    cdef public Py_ssize_t y
    def __init__(self, Py_ssize_t x, Py_ssize_t y):
        self.x = x
        self.y = y
    def __add__(self, Vec2 other) -> Vec2:    
        return Vec2(x = self.x + other.x, y = self.y + other.y)
    def __sub__(self, Vec2 other) -> Vec2:    
        return Vec2(x = self.x - other.x, y = self.y - other.y)
    def __mul__(self, Py_ssize_t k) -> Vec2:    
        return Vec2(x = self.x * k, y = self.y * k)
    def __eq__(self, Vec2 other) -> bint:    
        return self.x == other.x and self.y == other.y

def main():
    m1 = Money(amount = 10)
    m2 = Money(amount = 5)
    m3 = m1.__add__(m2)
    assert m3.amount == 15
    assert m1.__eq__(Money(amount = 10))
    assert m1 != m2
    assert (m1.__add__(m2)).__eq__(Money(amount = 15))
    assert m2.__lt__(m1)
    assert not (m1.__lt__(m2))
    assert m1.__lt__(Money(amount = 100))
    assert m1.amount < m2.amount == False
    v1 = Vec2(x = 3, y = 4)
    v2 = Vec2(x = 1, y = 2)
    sum = v1.__add__(v2)
    assert sum.x == 4
    assert sum.y == 6
    diff = v1.__sub__(v2)
    assert diff.x == 2
    assert diff.y == 2
    scaled = v1.__mul__(2)
    assert scaled.x == 6
    assert scaled.y == 8
    combo = (v1.__add__(v2)).__sub__(Vec2(x = 1, y = 1))
    assert combo.x == 3
    assert combo.y == 5
    assert (v1.__add__(v2)).__eq__(Vec2(x = 4, y = 6))
    assert (v1.__mul__(0)).__eq__(Vec2(x = 0, y = 0))
    None
    combined = total_money(Money(amount = 1), Money(amount = 2))
    assert combined.amount == 3
    print("P14 operators OK")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\01_basics\\polish_14_operators.lz"  # const: str
__package__ = "01_basics"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\01_basics"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def total_money(Money a, Money b) -> Money:
    return a.__add__(b)

