# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "make_range"]

def main():
    sum = 0  # mut
    for row in [[1, 2], [3, 4]]:
        for cell in row:
            sum = sum + cell
    assert sum == 10
    n = 10  # mut
    count = 0  # mut
    while n > 0 and count < 5:
        n = n - 1  # mut
        count = count + 1  # mut
    assert count == 5
    assert n == 5
    else_ran = False  # mut
    for i in range(0, 3):
        pass
    else:
        else_ran = True  # mut
    assert else_ran == True
    acc = 0  # mut
    for i in range(0, 10):
        if not (i % 3 == 0): continue
        acc = acc + i
    assert acc == 18
    outer_total = 0  # mut
    for v in [1, 2]:
        v = v * 100
        outer_total = outer_total + v
    assert outer_total == 300
    found_pair = []  # mut
    for i in range(1, 4):
        for j in range(1, 4):
            if i == j:
                break
            found_pair.push(i * 10 + j)
    assert found_pair == [21, 31, 32]
    cont_sum = 0  # mut
    for i in range(1, 5):
        if i == 2:
            continue
        cont_sum = cont_sum + i
    assert cont_sum == 8
    nums = [1, 2, 3, 4]  # mut
    popped_sum = 0  # mut
    while True:
        __wlv_0 = nums.pop()
        if not (__wlv_0 is not None):
            break
        top = __wlv_0
        popped_sum = popped_sum + top  # mut
    assert popped_sum == 10
    assert len(nums) == 0
    pair_sum = 0  # mut
    for (a, b) in [(1, 2), (3, 4)]:
        pair_sum = pair_sum + a * b
    assert pair_sum == 14
    None
    total = 0  # mut
    for x in make_range(5):
        total = total + x
    assert total == 10
    steps = 0  # mut
    while True:
        steps = steps + 1  # mut
        if steps >= 4:
            break
    assert steps == 4
    print("P4 loops OK")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\01_basics\\polish_04_loops.lz"  # const: str
__package__ = "01_basics"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\01_basics"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def make_range(Py_ssize_t n) -> list:
    out = []  # mut
    for i in range(0, n):
        out.push(i)
    return out

