# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "minmax"]

cdef void main():
    t = (1, "two", 3)
    assert_eq!(t[0], 1)
    assert_eq!(t[1], "two")
    assert_eq!(t[2], 3)
    __destruct_a_b_c = (10, 20, 30)
    a = __destruct_a_b_c.0
    b = __destruct_a_b_c.1
    c = __destruct_a_b_c.2
    assert_eq!(a, 10)
    assert_eq!(b, 20)
    assert_eq!(c, 30)
    pair = (5, "five")
    assert_eq!(pair[0], 5)
    assert_eq!(pair[1], "five")
    s = set!(1, 2, 3)
    assert!(1 in s)
    assert!(3 in s)
    assert!(9 not in s)
    assert_eq!(len(s), 3)
    ms = set!(1, 2)
    ms.add(3)
    assert!(3 in ms)
    assert_eq!(len(ms), 3)
    ms.add(3)
    assert_eq!(len(ms), 3)
    ms.remove(2)
    assert!(2 not in ms)
    assert_eq!(len(ms), 2)
    s1 = set!(1, 2, 3)
    s2 = set!(3, 4, 5)
    s1_has_3 = False
    for v in s1:    
        ((begin
    # Assign { target: Expr { kind: Var("s1_has_3"), ty: Bool, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } }, value: Expr { kind: Lit(Bool(true)), ty: Bool, span: Span { start: 0, end: 0, line: 0, col: 0, file: None } } }

) if v == 3 else None)
    assert!(s1_has_3)
    set_sum = 0
    for v in set!(1, 2, 3, 4):    
        set_sum = set_sum + v
    assert_eq!(set_sum, 10)
    assert_eq!(set!(1, 2, 3), set!(1, 2, 3))
    assert!(set!(1, 2, 3) != set!(1, 2))
    None
    __destruct_lo_hi = minmax([7, 8, 9])
    lo = __destruct_lo_hi.0
    hi = __destruct_lo_hi.1
    assert_eq!(lo, 7)
    assert_eq!(hi, 9)
    dup = [1, 1, 2, 2, 3]
    unique = set_comp!(lambda v: object: v, dup)
    assert_eq!(len(unique), 3)
    assert!(1 in unique)
    assert!(3 in unique)
    print("R10 set_tuple OK")

str __name__ = "main"
str __file__ = "DEMO/01_basics/set_tuple.lz"
str __package__ = "01_basics"
str __path__ = "DEMO/01_basics"
str __doc__ = ""
bint __is_macro__ = False
cdef tuple minmax(list xs):
    mn = xs[0]
    mx = xs[len(xs) - 1]
    return (mn, mx)

