# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Point", "Rect", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "shift"]

cdef class Point:
    cdef public Py_ssize_t x
    cdef public Py_ssize_t y
    def __init__(self, Py_ssize_t x, Py_ssize_t y):
        self.x = x
        self.y = y
    def sum(self) -> Py_ssize_t:    
        return self.x + self.y
    def double_mut(self):    
        self.x = self.x * 2
        self.y = self.y * 2
    def describe(self) -> str:    
        return "(" + str(self.x) + ", " + str(self.y) + ")"

cdef class Rect:
    cdef public Point top_left
    cdef public Py_ssize_t w
    cdef public Py_ssize_t h
    def __init__(self, Point top_left, Py_ssize_t w, Py_ssize_t h):
        self.top_left = top_left
        self.w = w
        self.h = h

def main():
    p = Point(x = 3, y = 4)
    assert p.x == 3
    assert p.y == 4
    q = Point(x = 0, y = 0)  # mut
    q.x = 10
    q.y = 20
    assert q.x == 10
    assert q.y == 20
    dist_sq = p.x * p.x + p.y * p.y
    assert dist_sq == 25
    None
    moved = shift(p, 1, 1)
    assert moved.x == 4
    assert moved.y == 5
    assert p.x == 3
    None
    assert p.sum() == 7
    None
    r = Point(x = 1, y = 2)  # mut
    r.double_mut()
    assert r.x == 2
    assert r.y == 4
    points = [Point(x = 1, y = 2), Point(x = 3, y = 4)]
    assert points[0].x == 1
    assert points[1].y == 4
    total = 0  # mut
    for pt in points:
        total = total + pt.sum()
    assert total == 10
    rect = Rect(top_left = Point(x = 0, y = 0), w = 5, h = 3)
    assert rect.top_left.x == 0
    assert rect.w == 5
    assert rect.h == 3
    assert rect.top_left.sum() == 0
    p1 = Point(x = 1, y = 2)
    p3 = Point(x = 1, y = 3)
    assert p1.x == 1 and p1.y == 2
    assert p3.y == 3
    assert p1.x == p3.x
    assert p1.y != p3.y
    None
    p4 = Point(x = 7, y = 8)
    assert p4.describe() == "(7, 8)"
    print("R11 structs OK")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\01_basics\\structs.lz"  # const: str
__package__ = "01_basics"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\01_basics"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def shift(Point pp, Py_ssize_t dx, Py_ssize_t dy) -> Point:
    return Point(x = pp.x + dx, y = pp.y + dy)

