# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Point", "Rect", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "shift", "Point.sum", "Point.double_mut", "Point.describe"]

cdef class Point:
    cdef public Py_ssize_t x
    cdef public Py_ssize_t y
    def __init__(self, Py_ssize_t x, Py_ssize_t y):        self.x = x
        self.y = y

cdef class Rect:
    cdef public Point top_left
    cdef public Py_ssize_t w
    cdef public Py_ssize_t h
    def __init__(self, Point top_left, Py_ssize_t w, Py_ssize_t h):        self.top_left = top_left
        self.w = w
        self.h = h

cdef void main():
    p = Point(x = 3, y = 4)
    assert p.x == 3
    assert p.y == 4
    q = Point(x = 0, y = 0)
    q.x = 10
    q.y = 20
    assert q.x == 10
    assert q.y == 20
    dist_sq = p.x * p.x + p.y * p.y
    assert dist_sq == 25
    None
    moved = shift(p, 1, 1)
    assert moved.x == 4
    assert moved.y == 5
    assert p.x == 3
    None
    assert p.sum() == 7
    None
    r = Point(x = 1, y = 2)
    r.double_mut()
    assert r.x == 2
    assert r.y == 4
    points = [Point(x = 1, y = 2), Point(x = 3, y = 4)]
    assert points[0].x == 1
    assert points[1].y == 4
    total = 0
    for pt in points:    
        total = total + pt.sum()
    assert total == 10
    rect = Rect(top_left = Point(x = 0, y = 0), w = 5, h = 3)
    assert rect.top_left.x == 0
    assert rect.w == 5
    assert rect.h == 3
    assert rect.top_left.sum() == 0
    p1 = Point(x = 1, y = 2)
    p3 = Point(x = 1, y = 3)
    assert p1.x == 1 and p1.y == 2
    assert p3.y == 3
    assert p1.x == p3.x
    assert p1.y != p3.y
    None
    p4 = Point(x = 7, y = 8)
    assert p4.describe() == "(7, 8)"
    print("R11 structs OK")

str __name__ = "main"
str __file__ = "DEMO/01_basics/structs.lz"
str __package__ = "01_basics"
str __path__ = "DEMO/01_basics"
str __doc__ = ""
bint __is_macro__ = False
cdef Point shift(Point pp, Py_ssize_t dx, Py_ssize_t dy):
    Point(x = pp.x + dx, y = pp.y + dy)

cdef Py_ssize_t Point.sum(object self):
    self.x + self.y

cdef void Point.double_mut(object self):
    self.x = self.x * 2
    self.y = self.y * 2

cdef str Point.describe(object self):
    "(" + str(self.x) + ", " + str(self.y) + ")"

