# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["Dog", "Cat", "Square", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef class Dog:
    cdef public str name
    cdef public Py_ssize_t age
    def __init__(self, str name, Py_ssize_t age):        self.name = name
        self.age = age

cdef class Cat:
    cdef public str name
    def __init__(self, str name):        self.name = name

cdef class Square:
    cdef public Py_ssize_t side
    def __init__(self, Py_ssize_t side):        self.side = side

class Describable:
    """Trait: Describable"""
    def describe(self) -> str: ...

class ShapeOps:
    """Trait: ShapeOps"""
    def area(self) -> Py_ssize_t: ...
    def perimeter(self) -> Py_ssize_t: ...

# impl Describable for Dog
# Describable.describe → 注入到 Dog

# impl Describable for Cat
# Describable.describe → 注入到 Cat

# impl ShapeOps for Square
# ShapeOps.area → 注入到 Square

cdef void main():
    d = Dog(_KwArg(name = "name", value = "Rex"), _KwArg(name = "age", value = 3))
    c = Cat(_KwArg(name = "name", value = "Tom"))
    assert_eq!(d.describe(), "Dog(Rex)")
    assert_eq!(c.describe(), "Cat(Tom)")
    sq = Square(_KwArg(name = "side", value = 4))
    assert_eq!(sq.area(), 16)
    assert_eq!(sq.perimeter(), 32)
    sq2 = Square(_KwArg(name = "side", value = 3))
    assert_eq!(sq2.area() + sq2.perimeter(), 9 + 18)
    print("R13 traits OK")

str __name__ = "main"
str __file__ = "DEMO/01_basics/traits.lz"
str __package__ = "01_basics"
str __path__ = "DEMO/01_basics"
str __doc__ = ""
bint __is_macro__ = False
