# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

def main():
    a = 10
    assert a == 10
    b = 20
    assert b == 20
    c = "str"
    assert c == "str"
    d = True
    assert d == True
    e = 3.5
    assert e == 3.5
    x = 1  # mut
    x = 2  # mut
    assert x == 2
    x = x + 10  # mut
    assert x == 12
    s = "hello"  # mut
    s = "world"  # mut
    assert s == "world"
    n = 10  # mut
    n = n + 5
    assert n == 15
    n = n - 3
    assert n == 12
    n = n * 2
    assert n == 24
    n = n // 4
    assert n == 6
    n = n % 4
    assert n == 2
    f = 1.5  # mut
    f = f + 2.0
    assert f == 3.5
    st = "foo"  # mut
    st = st + "bar"
    assert st == "foobar"
    first = "LZ"
    last = "lang"
    full = first + "-" + last
    assert full == "LZ-lang"
    assert len(full) == 7
    assert "abc"[0] == 97
    assert "abc"[2] == 99
    assert "abc" + "def" == "abcdef"
    p = 3
    q = 4
    r = p * p + q * q
    assert r == 25
    acc = 0  # mut
    acc = acc + p  # mut
    acc = acc + q  # mut
    assert acc == 7
    annotated = 2.5
    assert annotated == 2.5
    inferred = 100
    assert inferred == 100
    shadow = 1
    if True:
        shadow = 2
        assert shadow == 2
    assert shadow == 1
    msg = "Hello World"
    assert msg.contains("World")
    assert not msg.contains("xyz")
    low = "MiXeD".to_lower()
    assert low == "mixed"
    up = "MiXeD".to_upper()
    assert up == "MIXED"
    rep = "a-b-c".replace("-", "+")
    assert rep == "a+b+c"
    print("R2 variables OK")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\01_basics\\var_assign.lz"  # const: str
__package__ = "01_basics"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\01_basics"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
