# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "divide", "double_ps"]

def main():
    total = 0  # mut
    try:
        for x in range(1, 10):
            if x > 5:
                break
            total = total + x
    except _BreakLabel as __bl_scan:
        if __bl_scan.label != 'scan':
            raise
    print(total)
    try:
        try:
            for i in range(0, 10):
                if i == 3:
                    break
        except _BreakLabel as __bl_inner:
            if __bl_inner.label != 'inner':
                raise
        print("inner done")
    except _BreakLabel as __bl_outer:
        if __bl_outer.label != 'outer':
            raise
    print("after outer")
    pass
    count_up(10)
    count_up(20)
    pass
    for n in range(-2, 2):
        validate(n)
        print(f"validated: {n}")
    pass
    None
    print(divide(-10, 2))
    pass
    work(-7)
    pass
    early_exit(0)
    early_exit(5)
    pass
    norm(1)
    pass
    pass
    run(5)
    None
    pass
    apply_f(3)
    out = []  # mut
    pass
    count_down(3)
    print(out)

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\06_control_flow\\block_demo.lz"  # const: str
__package__ = "06_control_flow"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\06_control_flow"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def count_up(ps):
    n = int(ps.args[0])
    print(f"count_up got: {n}")

def validate(ps):
    v = int(ps.args[0])
    if v >= 0:
        pass
    else:
        ps.args[0] = 0
        return
    ps.args[0] = v

def normalize(ps):
    ps.args[0] = (int(ps.args[0])).abs()

def divide(Py_ssize_t a, Py_ssize_t b) -> Py_ssize_t:
    # default_checker: normalize
    return a // b

def work(ps):
    # default_checker: normalize
    print(f"work ps: {ps.args[0]}")

def early_exit(ps):
    if (int(ps.args[0])) == 0:
        return
    print(f"processed: {ps.args[0]}")

def norm(ps):
    print(f"norm: {ps.args[0]}")

def pre(ps):
    ps.args[0] = (int(ps.args[0])) * 2

def run(ps):
    # default_checker: pre
    print(f"run: {ps.args[0]}")

def double_ps(object ps) -> object:
    ps.args[0] = (int(ps.args[0])) * 2
    return ps

def apply_f(ps):
    # default_checker: double_ps
    print(f"apply_f: {ps.args[0]}")

def count_down(ps, out: list):
    n = int(ps.args[0])
    if n <= 0:
        return
    out.append(n)
    count_down(n - 1)

