# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

def main():
    result = []  # mut
    pass
    countdown(5)
    assert result == [5, 4, 3, 2, 1, 0]
    pass
    factorial(5, 1)
    pass
    fib(10, 0, 1)
    visited = []  # mut
    pass
    walk(1, 10)
    assert visited == [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    print("block tailrec tests done")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\06_control_flow\\block_tailrec.lz"  # const: str
__package__ = "06_control_flow"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\06_control_flow"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def countdown(ps, result: list):
    n = int(ps.args[0])
    if n <= 0:
        result.push(0)
        return
    result.push(n)
    ps.args[0] = n - 1
    countdown(int(ps.args[0]))

def factorial(ps):
    n = int(ps.args[0])
    acc = int(ps.args[1])
    if n <= 1:
        ps.args[0] = acc
        return
    ps.args[0] = n - 1
    ps.args[1] = acc * n
    factorial(int(ps.args[0]), int(ps.args[1]))

def fib(ps):
    n = int(ps.args[0])
    a = int(ps.args[1])
    b = int(ps.args[2])
    if n == 0:
        ps.args[0] = a
        return
    ps.args[0] = n - 1
    ps.args[1] = b
    ps.args[2] = a + b
    fib(int(ps.args[0]), int(ps.args[1]), int(ps.args[2]))

def walk(ps, visited: list):
    cur = int(ps.args[0])
    end = int(ps.args[1])
    if cur > end:
        return
    visited.push(cur)
    ps.args[0] = cur + 1
    walk(int(ps.args[0]), int(ps.args[1]))

