# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "safe_div", "safe_div0", "safe_div2", "guard_let_single", "guard_let_in_loop"]

cdef Py_ssize_t main():
    None
    print(safe_div(10, 2))
    print(safe_div(10, 0))
    None
    print(safe_div0(10, 0))
    None
    print(safe_div2(10, 2))
    print(safe_div2(10, 0))
    opt_name = Some("Bob")
    # match opt_name
    name = __scrutinee__[0]
    if isinstance(__scrutinee__, Option) && True  # bind name:    
        print(f"hello {name}")
        opt_age = Some(30)
        # match opt_age
        age = __scrutinee__[0]
        if isinstance(__scrutinee__, Option) && True  # bind age:        
            if age > 0:            
            else:
                return -3
            print(f"age: {age}")
            None
            print(guard_let_single(Some(21)))
            print(guard_let_single(None))
            None
            print(guard_let_in_loop(Some(10)))
            0
        elif True:        
            return -2
    elif True:    
        print("no name")
        return -1

str __name__ = "main"
str __file__ = "DEMO/06_control_flow/guard.lz"
str __package__ = "06_control_flow"
str __path__ = "DEMO/06_control_flow"
str __doc__ = ""
bint __is_macro__ = False
cdef Py_ssize_t safe_div(Py_ssize_t a, Py_ssize_t b):
    if b != 0:    
    else:
        return 0
    a / b

cdef Py_ssize_t safe_div0(Py_ssize_t a, Py_ssize_t b):
    if b != 0:    
    else:
        return 0
    a / b

cdef Py_ssize_t safe_div2(Py_ssize_t a, Py_ssize_t b):
    if b != 0:    
    else:
        return 0
    a / b

cdef Py_ssize_t guard_let_single(object o):
    # match o
    v = __scrutinee__[0]
    if isinstance(__scrutinee__, Option) && True  # bind v:    
        v * 2
    elif True:    
        -1

cdef Py_ssize_t guard_let_in_loop(object o):
    result = 0
    for i in Range(start = 1, end = 3):    
        # match o
        v = __scrutinee__[0]
        if isinstance(__scrutinee__, Option) && True  # bind v:        
            result = result + v * i
        elif True:        
            break
    result

