# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

cdef void main():
    i = 0
    while True:    
        i = i + 1
        ((begin
    # Break

) if i >= 3 else None)
    print(i)
    s = 0
    k = 0
    while k < 4:    
        s = s + k
        k = k + 1
    print(s)
    total = 0
    for n in Range(start = 1, end = 5):    
        total = total + n
    print(total)

str __name__ = "main"
str __file__ = "DEMO/06_control_flow/loop_demo.lz"
str __package__ = "06_control_flow"
str __path__ = "DEMO/06_control_flow"
str __doc__ = ""
bint __is_macro__ = False
