# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["sum_all", "take_until_zero", "first_error", "process_until_fail", "count_from", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__"]

def sum_all(object it) -> Py_ssize_t:
    total = 0  # mut
    while True:
        __wlv_0 = it.next()
        if not (__wlv_0 is not None):
            break
        item = __wlv_0
        total = total + item  # mut
    return total

def take_until_zero(object it) -> list:
    result = []  # mut
    while True:
        __wlv_1 = it.next()
        if not (__wlv_1 is not None):
            break
        item = __wlv_1
        if item == 0:
            break
        result.append(item)
    return result

def first_error(object it) -> object:
    while True:
        __wlv_2 = it.next()
        if not (__wlv_2 is not None and not isinstance(__wlv_2, BaseException)):
            break
        v = __wlv_2
        if v > 100:
            break
    __scrut_3 = it.next()
    if __scrut_3 is not None and isinstance(__scrut_3, BaseException):
        e = __scrut_3
        return e
    elif True:
        _ = __scrut_3
        return None
    else:
        pass

def process_until_fail(object it) -> Py_ssize_t:
    processed = 0  # mut
    while True:
        __wlv_4 = it.next()
        if not (__wlv_4 is not None):
            break
        item = __wlv_4
        if item > 0:
            pass
        else:
            break
        processed = processed + item  # mut
    return processed

def count_from(Py_ssize_t start, Py_ssize_t limit) -> object:
    i = start  # mut
    while i < start + limit:
        yield i
        i = i + 1  # mut

def main():
    r = range(1, 5)
    print(sum_all(r))
    nums = [1, 2, 0, 3, 4]
    print(take_until_zero(nums))
    seq = [5, 10, 15, 20]
    first = 0  # mut
    for item in seq:
        if item == 15:
            break
        first = item
    print(first)
    gen = count_from(0, 5)
    taken = 0  # mut
    for item in gen:
        print(item)
        taken = taken + 1
        if taken >= 3:
            break

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\06_control_flow\\while_let.lz"  # const: str
__package__ = "06_control_flow"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\06_control_flow"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
