# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython
import sys

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

class LZError(Exception):
    def __init__(self, val=None):
        self.val = val
        super().__init__(str(val))

class _BreakLabel(Exception):
    def __init__(self, label, value=None):
        self.label = label
        self.value = value
        super().__init__(label)

class Box:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Box(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Box(' + repr(self._v) + ')'

class Rc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Rc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Rc(' + repr(self._v) + ')'

class Arc:
    def __init__(self, v=None): self._v = v
    @staticmethod
    def new(v=None): return Arc(v)
    def __getattr__(self, n): return getattr(self._v, n)
    def __repr__(self): return 'Arc(' + repr(self._v) + ')'

class Option:
    @staticmethod
    def Some(v): return v
    None_ = None

class Result:
    @staticmethod
    def Ok(v): return v
    @staticmethod
    def Err(e): return LZError(e)

def __go(v): return v  # go 并发降级为同步求值
def push(seq, item):
    seq.append(item)
    return item
def pop(seq):
    return seq.pop()
def map(seq, f):
    return list(map(f, seq))
def filter(seq, f):
    return list(filter(f, seq))
def collect(it):
    return list(it)
def reverse(seq):
    return list(reversed(seq))
def sort(seq):
    return sorted(seq)
def fold(seq, init, f):
    acc = init
    for x in seq:
        acc = f(acc, x)
    return acc

__name__ = "main"
__file__ = "main.lz"
__all__ = ["MyResource", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "process_file"]

cdef class MyResource:
    cdef public str name
    def __init__(self, str name):
        self.name = name
    def __enter__(self) -> MyResource:    
        print(f"acquiring {self.name}")
        return self
    def __exit__(self, MyResource _guard):    
        print(f"releasing {self.name}")

def main():
    __with_res = MyResource(name = "database")  # mut
    res = __with_res.__enter__()  # mut
    print(f"using {res.name}")
    res.__exit__(res.clone())
    _with = print("standalone with block")  # mut
    print("inside standalone with")
    None
    process_file()
    if True:
        pass
    __scrut_0 = 42
    if __scrut_0 == 0:
        print("zero")
    elif True:
        _ = __scrut_0
        pass
    else:
        pass
    print("with and defer demonstrated")
    print("cleanup step B")
    print("cleanup step C")
    print("cleanup step A")

__name__ = "main"  # const: str
__file__ = "F:\\AI\\lang-zone\\DEMO\\06_control_flow\\with_defer.lz"  # const: str
__package__ = "06_control_flow"  # const: str
__path__ = "F:\\AI\\lang-zone\\DEMO\\06_control_flow"  # const: str
__doc__ = ""  # const: str
__is_macro__ = False  # const: bint
def process_file():
    file = "data.txt"
    print(f"processing {file}")
    print(f"closing {file}")

