# Generated by lzcyc (IR backend)
# cython: language_level=3
# cython: boundscheck=False

import cython

class _Moved:
    def __getattr__(self, name): raise RuntimeError('access to moved value')
    def __bool__(self): raise RuntimeError('use of moved value')
    def __repr__(self): return '<_Moved>'
_MOVED = _Moved()
def _MovedCheck(v): raise RuntimeError('use of moved value')

__name__ = "main"
__file__ = "main.lz"
__all__ = ["MyResource", "main", "__name__", "__file__", "__package__", "__path__", "__doc__", "__is_macro__", "process_file"]

cdef class MyResource:
    cdef public str name
    def __init__(self, str name):        self.name = name
    cdef MyResource __enter__(self):    
        print(f"acquiring {self.name}")
        self
    cdef void __exit__(self, MyResource _guard):    
        print(f"releasing {self.name}")

cdef void main():
    res = MyResource(_KwArg(name = "name", value = "database"))
    res.__exit__(res.clone())
    print(f"using {res.name}")
    _with = print("standalone with block")
    print("inside standalone with")
    print("cleanup step A")
    print("cleanup step C")
    print("cleanup step B")
    None
    process_file()
    ((begin
    # Pass

) if True else print("unreachable"))
    # match 42
    if __scrutinee__ == 0:    
        print("zero")
    _ = __scrutinee__
    elif True  # bind _:    
        pass
    print("with and defer demonstrated")

str __name__ = "main"
str __file__ = "DEMO/06_control_flow/with_defer.lz"
str __package__ = "06_control_flow"
str __path__ = "DEMO/06_control_flow"
str __doc__ = ""
bint __is_macro__ = False
cdef void process_file():
    file = "data.txt"
    print(f"closing {file}")
    print(f"processing {file}")

